### ISSUE TITLE
Comment edu.utexas.cs.nn.gridTorus

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#1]
Thoroughly comment the source code in this package

**Comment by schrum2** [comment]
In particular, every method needs a comment, and every class needs a comment at the top.

**Comment by Rollinsa** [comment]
Commented gridTorus classes and methods and other code extensively and changed a little bit of code by commenting it out (agents and the multithreading for the agents was unnecessary and over complicated and did not need to be included, so was commented out)
