### ISSUE TITLE
Comment MatchDataTask in edu.utexas.cs.nn.tasks.testmatch

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#10]
The point of this task is to take a bunch of (input,output) pairs that a network needs to evolve to match, and return a fitness value based on the Mean Squared Error (how far the actual outputs are from the desired outputs)

**Comment by Rollinsa** [comment]
Commented MatchDataTask, especially focusing on the method called evaluate which was the meat of the class, as it found the "Score<T>", which is the fitness level of each individual (each individual being the pairs of inputs/outputs whose actual and desired outputs are compared for average error). All methods and classes were commented along with some code within the evaluate method
