### ISSUE TITLE
Add Check to AfterStateEvaluator to take shorter action list

### ISSUE THREAD

**Issue by Serenamidori** [schrum2/MM-NEATv2#102]
In the TetrisAfterStateEvaluator, you should add a check before adding states to the set and check if the current state exists in the set. Before throwing the new one out, check which action list is shorter, and choose the shorter one to replace the on in the set. (Be sure to remember that you can do this change, export, pull onto the tower server, and to the watch instead of having to re-evolve)

**Comment by Serenamidori** [comment]
This may not be necessary if we simply move the TetrisState.FALL to the front of out action list.

**Comment by Serenamidori** [comment]
Update- Moving TetrisState.FALL to the front of the list causes more holes to appear, and makes the game run shorter.

Edit: This was not the issue, but this allowed us to debug and find another issue that might have been the reason for more holes appearing.

**Comment by schrum2** [comment]
If we have some JUnit tests that confirm the correct lengths of action sequences when using the fall action, then we can close this.

**Comment by Serenamidori** [comment]
We do have JUnit tests for this, labeled "fall_in_action_list"
I went ahead and made the tests hardcoded in so it checks  each end state's action list size and contents.
