### ISSUE TITLE
Behavioral Diversity in Image Match Task

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#104]
Make a batch file for the Image Match task that uses the GeneralNetworkCharacterization characterization. This might be sufficient to get cool results, but if it is not, then you will need to make a domain-specific characterization for the ImageMatchTask. This uses DomainSpecificCharacterization, but also requires you to override the method:
public ArrayList<Double> getBehaviorVector() 
which comes originally from the LonerTask, which the image match task inherits. The behavior characterization should basically be a list of all the pixel by pixel HSB values from the image.

**Comment by leg2015** [comment]
got some batch files running that use the generalNetworkCharacterization but still need to do the domainSpecificCharacterization

**Comment by leg2015** [comment]
got domain specific characterization up and running for image match task
