### ISSUE TITLE
HyperNEAT with Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#106]
There is no Tetris task because it is part of the RL Glue system. However, the HyperNEAT version of Tetris will require a lot of information specific to Tetris. So, extend the RLGlue Task to make a HyperNEATTetrisTask that applies HyperNEAT to Tetris specifically. You should probably consult with Gabby a lot on this.

**Comment by leg2015** [comment]
see #29

**Comment by leg2015** [comment]
Started working on this project. Have it roughly implemented but has not been checked.

**Comment by schrum2** [comment]
I think this works now. I made a few small improvements, but you mostly had it. Play around with this a bit next week. I'll close the issue though, since it does run.
