### ISSUE TITLE
Additional Tetris objectives

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#109]
Create a Tetris objective that specifically counts tetrises (four lines at once). 

We could also make fitness functions for triples, doubles, and singles ... but these are probably not needed for evolution. However, it would be very useful if we could track this information as "other" scores.

**Comment by Serenamidori** [comment]
Not necessary anymore, not sure if we should close this?

**Comment by schrum2** [comment]
Let's leave it open. Even if we don't use these scores for fitness, we probably want to track them as "other" scores. In other words, after doing an evaluation, it might be nice to know exactly how many tetrises occurred, which is different from the overall score. In fact, feel free to work on this task whenever you find time.

**Comment by Serenamidori** [comment]
Added this as an "other" score, by checking the score differences in Tetris.java and using a getter to find the number of each row scored for an agent. Closing this for now,
