### ISSUE TITLE
Setup Image Match Task

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#11]
Create a new package edu.utexas.cs.nn.tasks.testmatch.image that contains required classes to do the following task:

Given an image loaded from a file (will need to be specified in the Parameters class), try to evolve a network (eventually a CPPN) to recreate that image. The inputs to the network will be (x,y) coordinates of the pixels in the image, and the outputs will be the R, G, B values (like the Picbreeder system). The specific task to make in this package is one that uses the actual RGB values from the loaded image as the target output values.

This task will be useful once we have a working CPPN, because it provides a way to test out the CPPNs before moving on to a full version of HyperNEAT

**Comment by leg2015** [comment]
set this task up on friday, forgot to close it though
