### ISSUE TITLE
Comment, Test, Understand edu.utexas.cs.nn.evolution.nsga2.tug (TUG with NSGA2)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#110]
TUG (Targeting Unachieved Goals) is a modification to NSGA2 (Non-dominated Sorting Genetic Algorithm 2). I invented TUG, and it is described here: http://nn.cs.utexas.edu/?schrum:gecco10

Comment the code in this package and do JUnit tests. In particular, the main method of TUGNSGA2 has informal tests which should be transformed into proper JUnit tests.

TUG could be useful in certain domains with multiple objectives, like the pred/prey task.

**Comment by schrum2** [comment]
I transferred this back to Alex since some of his research interests indicate that he might need to use it soon.

**Comment by Rollinsa** [comment]
Extensively commented the edu.utexas.cs.nn.evolution.nsga2.tug package. Also created a test which transformed all of the print statements in the main method of TUGNSGA2 into asserts for a JUnit test case.
