### ISSUE TITLE
Speed up HyperNEAT.

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#114]
Following off of #99, this issue is about speeding up HyperNEAT. To some extent, things can't help but be a little slow because the networks are so big, but we need to identify the exact source of the slow-down. How long does it take to generate a large network from a CPPN? How long does it take to load inputs? How long does the TWEANN process method take when the network is really big?

Use the System.currentTimeMillis() method before and after each of these steps, and compare the difference in the two values to determine how long it is really taking to do these things. If this information points to a specific area of the code that needs speeding up, then we will look for ways to do it.

**Comment by leg2015** [comment]
took a first shot at it

**Comment by schrum2** [comment]
Recommendation for a slight improvement of createNodeLinks:
Instead of using addAll, send the ArrayList as a parameter to loopThroughLinks, which can directly add the link genes to it. See if this causes any noticeable timing differences.

**Comment by schrum2** [comment]
Here's an even bigger change (make sure everything is committed before doing this, and be sure to check the timing both before and after ... if the timing does not improve, you may need to revert the code. However, a better idea is to simply comment out the existing methods but leave them in the code, in case we want to go back):

We might be able to create and cache the list of link genes just once. There is potential savings in this because calling the LinkGene constructor over and over takes up time. However, the problem with this is that every genotype should create its own network ... the link weights should be different in each new phenotype. 

The motivation behind this proposal is the hope that changing all of the link weights in an existing list of genes will take less time that creating them from scratch. You would still need to loop through each coordinate, except instead of creating a new link gene, you would simply change the weight value of the link at that position. Note: this will only work if every pair of neurons that can be connected possess a link. This means you will need to change the code for link expression ... in the current code, link genes are not made if the CPPN activation does not pass a threshold. Instead of this, ALWAYS create a LinkGene, but give a weight of 0.0 to unexpressed links (link weights of 0.0 behave identically to absent links).

**Comment by schrum2** [comment]
When you implement this new a approach, instead of commenting the old version out, leave the code accessible so you can make unit tests comparing the old version to the new version. They should behave identically.

**Comment by leg2015** [comment]
Got some methods and command line parameters to help speed up hyperNEAT. Still need to perform tests. For tests, I need to test that if I create a phenotype with the parameter on and off, the outputs of the process from both phenotypes should be identical. I also need to check that if you create two separate TWEANNs back to back from the genotype with caching on that the architecture is the same but the link weights are different. Also need to make sure changing the link creation from no link being created under the threshold to a link with weight 0.0 doesn't screw up any other part of the code.

**Comment by schrum2** [comment]
I removed the addAll call to speed up loopThroughLinks. This required changing some of your test code. I also modified how link indexes are calculated for the sped-up HyperNEAT.

**Comment by schrum2** [comment]
A lot of the tests in HyperNEATCPPNGenotypeTest fail, but I'm not sure if this is because they are incomplete, or if it is due to changes I recently made. Just wanted to warn you.

**Comment by schrum2** [comment]
The speedUpHyperNEAT option doesn't seem to actually

**Comment by schrum2** [comment]
I checked the timing of getPhenotype, and there is not real speed up. I'm going to remove the speedUpHyperNEAT option because it is unnecessarily complicating the code for little to no gain. I'll leave in some of the more obvious speed up tricks, but I'm going to remove the trick with the links.

I have another idea in mind for speeding up HyperNEAT, but I think it will be a completely different issue, so I'm going to close this issue for now.
