### ISSUE TITLE
getRow method for VizDoomTask

### ISSUE THREAD

**Issue by Serenamidori** [schrum2/MM-NEATv2#116]
We need a way to get the correct row for the input array given a certain ratio of the screen resolution (4:3, 16:10, 16:9, 5:4). Make a method in VizDoomTask that calculates the row given a screen resolution.

**Comment by Serenamidori** [comment]
This is finished, but there is an issue with larger resolutions, I'll come back to this later to work on those but it's not necessary for now.

**Comment by schrum2** [comment]
Look carefully at my commit comments and the diff from this commit (https://github.com/schrum2/MM-NEATv2/commit/5fb9269e7c691273c648d46bb89d8241ef00166a) before returning to this issue.

**Comment by Serenamidori** [comment]
Read through the commit comments and diff, and I believe that getRow should work in place of magic numbers now. Also, getRow was removed from VizDoomTask and left in VizDoomBasicShootTask instead. This should still produce the correct row number. Closing this issue for now.
