### ISSUE TITLE
Comment ResumableRandom and write JUnit tests

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#12]
ResumableRandom in package edu.utexas.cs.nn.util.random needs to be properly commented. This includes removing comments that are no longer relevant or needed (including unused code).

The class also contains a main method whose code can be transformed into a proper JUnit test class named ResumableRandomTests

**Comment by leg2015** [comment]
Commented ResumableRandom class and added appropriate JUnit testing cases

**Comment by schrum2** [comment]
Please make the following minor adjustments:

Comment the top of the class as well, indicating an overall idea of what is
being tested.

Define a static final constant to use instead of the magic number 100.

Give the test() method a more descriptive name

Add another test that is similar to the first, but repeatedly grabs the
seed and then uses the hard seed set, just like the main method in the
ResumableRandom class

Once this test exists, go ahead and completely remove the main method from
the ResumableRandom class

On Wed, May 11, 2016 at 11:49 AM, leg2015 notifications@github.com wrote:

> Commented ResumableRandom class and added appropriate JUnit testing cases
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/schrum2/MM-NEATv2/issues/12#issuecomment-218519632

## 

Jacob Schrum, Ph.D.
Assistant Professor of Computer Science
Department of Mathematics and Computer Science
Southwestern University
1001 E. University Ave.
Georgetown, TX 78626

Office: Mood-Bridwell Hall 141
Mail: SU Box 7341
Off-Campus Phone: (512) 863-1712
On-Campus Extension: x1712
E-mail: schrum2@southwestern.edu
WWW: http://southwestern.edu/~schrum2
