### ISSUE TITLE
Comment edu.utexas.cs.nn.breve2D

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#120]
This domain has a similar setup to the PredPrey task. It is my attempt to reimplement a domain I used in several of my early papers ... here's an example: http://nn.cs.utexas.edu/keyword?schrum:cig09

The domain seems to work fine, but I never really managed to re-create the results I had in my earlier 3D version. Still, there might be some interesting research we can accomplish with this domain. In order to learn more about it, comment the code, and maybe even play around with the available batch files (there are very few batch files ... you may find it appropriate to create more).

**Comment by Rollinsa** [comment]
Looked into the Breve2D domain (looked through all the code and looked a bit at the "Evolving Multi-modal Behavior in NPCs" paper. Commented and cleaned up Breve2DExec.

**Comment by Rollinsa** [comment]
Commented the Breve2DTask

**Comment by schrum2** [comment]
Breve2DGame still needs extensive comments, as does Breve2DGameView

**Comment by schrum2** [comment]
I've split this up between Darwin and Isabel. You can either work on it together, or leave it to whoever gets to it first (other issues are generally higher priority)

**Comment by DarwinJohnson** [comment]
Added Header Comments to all methods in Breve2DGame. More body comments  could be useful, but the uses of each method is now clear.
