### ISSUE TITLE
LEO in HyperNEAT

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#122]
There is an alternative link expression scheme for HyperNEAT known as LEO: Link Expression Output. Add a command line parameter "leo" that enables this. In this approach, every CPPN output is replaced with two outputs. Instead of having one output determine both the presence and value of a synaptic link, there is now a separate output for each. If the expression output has a positive value, then the link output defines the weight of the new link. If the expression output is 0 or negative, then no link is created (or the weight is 0, same thing).

**Comment by schrum2** [comment]
Instead of making the expression distinction be positive or negative, make it depend on the linkExpressionThreshold. This is more general, and if we want the scheme I described above, we can set it to 0.

**Comment by schrum2** [comment]
I don't know if this will help or make things more confusing, but the original LEO paper is at this link: http://eplex.cs.ucf.edu/papers/verbancsics_gecco11.pdf

**Comment by leg2015** [comment]
Got it implemented and old junit test still works. Do need to add some junit tests that involve leo however

**Comment by leg2015** [comment]
Got junit test to run! Therefore, leo is implemented
