### ISSUE TITLE
New RL Glue domain: Pinball Domain

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#126]
This Java domain has an RL Glue interface:
http://www-all.cs.umass.edu/~gdk/pinball/

It will hopefully be fairly easy to incorporate into our code.

**Comment by schrum2** [comment]
This is another RL Glue domain. Start by copying the code into MM-NEAT and then committing that. Afterward, we can talk about how to actually integrate the code.

Alice has a similar issue ( #204 ) so the two of you should share notes.

**Comment by schrum2** [comment]
Now you need to add some code to the task so that whenever CommonConstants.watch is true, the Pinball evaluation will be shown in the GUI rather than happen in the background. Modify the oneEval method so that entirely different code is run if CommonConstants.watch is true. In fact, it would probably be best to separate the code out into visual and non-visual eval methods that get called from oneEval.

**Comment by schrum2** [comment]
Currently, the oneEval method loads a file called pinball_simple_single.cfg. Although the path (directories) leading to this file should always be the same, there is another file in this directory that users may also want to use. Therefore, the value "pinball_simple_single.cfg" should be stored in a String Parameter called pinballConfig specified in parameters. The default value will be "pinball_simple_single.cfg", but the user could also specify the other config file. 

In fact, the current batch file you have should renamed to be "Simple" instead of "Control" so that you can also make a batch file for the other configuration file (you'll have to change the saveTo directory and other parameters in the batch file itself).

**Comment by DarwinJohnson** [comment]
I tried to run the PinballTask class after implementing the new PinballViewer, and the console states "Ball or target not loaded in data/pinball/pinball_simple_single.cfg" when trying to evaluate the Parents. I haven't edited this file, nor have I changed the filepath, filename, nor the Parameter referring to the config file. However, the PinballViewer appeared for a brief second the first time, so I think that part of the code may work after this issue is fixed.

**Comment by DarwinJohnson** [comment]
The PinballViewer now functions properly, and the PinballTask runs as expected. The Pinball config files are no longer being overwritten, and the oneEval method appears to be working.

**Comment by schrum2** [comment]
The batch file Pinball-Basic-Simple.bat should just be called Pinball-Simple.bat, but you also need to make a Pinball-Hard.bat batch file that loads the other cfg file. See how well evolution performs in the harder maze too.

**Comment by schrum2** [comment]
I'm closing this issue. The domain clearly works, and all current problems with it are small, specific issues which are described elsewhere.
