### ISSUE TITLE
Super Mario!

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#127]
Download and integrate the Mario AI competition code from this site:
http://www.marioai.org/gameplay-track/getting-started
Play with the code a bit in its own project for a while and see that you can get it to run. Then, once you understand it a bit, integrate it into our MM-NEAT project!

**Comment by schrum2** [comment]
I added Gabby to this. You don't necessarily need to work on this soon (you have plenty of other tasks) but it is here waiting for you if/when you are ready. You can work on it together!

**Comment by Serenamidori** [comment]
Update to this- we're going to be using the 2009 code, I'll be implementing this hopefully soon 
http://julian.togelius.com/mariocompetition2009/gettingstarted.php

**Comment by Serenamidori** [comment]
From what I've found, the java file can run and let us play the game, or the hard coded agent can play the game. Not sure how to integrate this into the project, but I've downloaded all the files so we can do this later.

**Comment by Serenamidori** [comment]
https://groups.google.com/forum/#!forum/mariocompetition this is for later

**Comment by schrum2** [comment]
Look at the source code and figure out which class is the main class. Try loading the code into its own Eclipse project and see if you can launch different types of mario games from there instead of from the command line. This should give you a sense of how to integrate it into our code.

Incidentally, you should check out the code for the Pred/Prey task and maybe MsPacMan to see how other domains have been integrated into MMNEAT.
