### ISSUE TITLE
Java Fighting Game Competition

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#128]
There is a simple Java fighting game with an associated competition happening in September. We still have plenty of time to enter! To get started, you'll need to download the Java code here:
http://www.ice.ci.ritsumei.ac.jp/~ftgaic/index-2.html
Try working with the project on its own to get it running. Then, once you understand the code a bit, try to integrate it with MM-NEAT and evolve a fighting agent!

**Comment by Serenamidori** [comment]
After setting up and going through this code, it's probably not worth the time to figure out another way to run these files to get our AI to evolve. The program is set up in such a way that integrating it into our project file would be very difficult, and it would be best to leave the environment and agents as their own projects. For this reason, we're going to close this issue and not integrate this domain in our project.

What I understood is that you need a project for the AI itself that uses AIToolKit.jar and implements their AI interface. You would code the AI there, export the jar file, then add the file to the AI folder in the FightingICE project folder. From there, you'd need to set up the project to run itself and choose with AI to use. This isn't ideal as the main class is hidden and we don't know exactly how to recreate it without using the display (we wouldn't want it turned on while we evolve).

So I'll be closing the issue now, this would be interesting to do, but it takes away too much focus for our AI research and my time could be better spent with VizDoom issues.
