### ISSUE TITLE
Troubleshoot and JUnit test RawTetrisStateExtractor

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#129]
Note that I've assigned this to both of you. Work together and share knowledge to figure this issue out.

The RawTetrisStateExtractor is meant to be used with HyperNEAT (I renamed it: see https://github.com/schrum2/MM-NEATv2/commit/02d93501cef224b0f789077f20f11388c9ca371e ). However, it can also be used without HyperNEAT. There are batch files for both options.

Unlike HyperNEAT in the Pred/Prey domain, this code seems to run at about the same speed as usual (in Tetris, the RL Glue components are probably the speed bottleneck). However, the performance of HyperNEAT using the raw extractor is poor. Fortunately (?) the performance using regular NEAT with the raw extractor is also poor. This isn't too surprising ... it's hard to learn from raw features, though we would like HyperNEAT to do better (being able to learn from raw features would be an impressive research accomplishment).

The first step in doing this is to JUnit test the new extractor, and also do informal troubleshooting to verify that the TetrisAfterStateAgent is correctly assessing the information returned by this extractor.

**Comment by schrum2** [comment]
Related to this:
There is a command line parameter called "absenceNegative" that is already used elsewhere. Make it so that if this parameter is set to true, then empty Tetris squares create an input of -1.0 instead of 0.0. This should also be unit tested, but ultimately, the point of this is to see if a different sensor modality makes it easier to easier to assign good utility scores to the different after states.

**Comment by Serenamidori** [comment]
I'm written JUnit tests for the methods, and I can confirm the inputs are always 1 or 0. I'll try to add something to it now to test for absenceNegative and -1 instead.

**Comment by Serenamidori** [comment]
Just setting "absenceNegative" to true in the command line for the tests doesn't change anything, so I've tried adding a check in the extract method. Unfortunately, using Parameters.parameters.booleanParameter("absenceNegative") gives a null pointer. Shouldn't it at least be false since it's set that way initially?

**Comment by schrum2** [comment]
Change the extract method of RawTetrisStateExtractor so that if (and only
if) absenceNegative is true, result contains values of -1 and 1. Currently,
it contains values of 0 and 1.

**Comment by Serenamidori** [comment]
The extractor tests work now, so setting the parameter will allow the extractor to set 0 inputs as -1.

**Comment by schrum2** [comment]
The recent changes that I made to fix the after state agent seem to have broken two of the extractor tests in RawTetrisStateExtractorTests. Specifically, extract_test and extract_negative_test.

**Comment by Serenamidori** [comment]
I've figured out why it's not working for these tests- the mobile piece is visible in the extracted inputs. I can't remember how we figured this out before, or if we ever did, so this needs the same/similar change.
