### ISSUE TITLE
Draw activation functions when drawing CPPNs

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#130]
The draw method is responsible for drawing neural networks when the showNetworks option is true. I would like this method to visually distinguish between different types of activation functions in the nodes of the network. An easy way to do this would be to have a different color for each activation function (the colorFromInt method in CombinatoricUtilities would be an easy way to do this). However, the color of the nodes is already used as an indicator of other things, such as the input/hidden/output and preference vs policy neuron distinction. I don't want to lose these distinctions.

So, we have two options. One is to find some other way to distinguish the neuron types while maintaining the current color information. I'm interested in any ideas you have.

The other option is simpler, but not as cool. Basically, if the "allowMultipleFunctions" parameter is true, then the neurons should be color-coded based on activation function. Otherwise, the current color coding method is used.

While doing this, please clean up and comment the code for the draw and associated methods. It's not very nice code. A good idea for testing this would be to evolve a CPPN for the imagematch task (just a few generations) and then keep using the post watch on it every time you change how the networks will be drawn. This way, you can avoid breaking what already works.

**Comment by leg2015** [comment]
puts a border around the neuron that corresponds to the activation function of the neuron
