### ISSUE TITLE
VizDoom Parameters

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#135]
Remove the static constants SCENARIO_WAD, GAME_WAD, DOOM_MAP, and DOOM_EPISODE_LENGTH from the VizDoomTask and turn them into command line parameters.

**Comment by Serenamidori** [comment]
All the static variables have been changed to parameters and they are changed to be specified in the batch file now.

**Comment by schrum2** [comment]
After talking with you and seeing how some of these parameter don't really make sense given the way we are defining tasks, I think the following changes should be made:

The following are still ok to have as parameters: doomEpisodeLength and gameWad

However, let's remove the following Parameters and set them according to each specific task: scenarioWad, doomMap

Sorry to flip back and forth on this.

**Comment by Serenamidori** [comment]
It's okay! I do wonder how we'll be able to move those calls tot he specific tasks, where do they go? Under the super() call?

**Comment by Serenamidori** [comment]
Adding those two calls to BasicShootTask allows it to only play for a little while with watch on true, not sure why this wouldn't work

**Comment by Serenamidori** [comment]
I added these parts under the super() call in each specific task, but Defend the Center isn't using the map it needs now, and using the maps call isn't changing it.

I've committed and synced the changed still, but I'll wait until you can check on this to close anything again.

**Comment by Serenamidori** [comment]
The "issue" above was my bad, it does work to allow only certain parameters, so I'll be closing this now
