### ISSUE TITLE
Modify VizDoomBasicShootTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#137]
Change this task to that the agent is not always forced to shoot. Allow it to move left or right without shooting, and also to shoot while staying still. This way it can avoid being punished for coincidentally starting far away from the monster (less punishment for missed shots)

**Comment by Serenamidori** [comment]
The actions have been added and I can verify I saw them working, but this was with the initial runs on Eclipse. I'll run it for a few generations and update here before closing this issue

**Comment by Serenamidori** [comment]
Left out "move left and shoot," "move right and shoot," and "stand still" so we are back to three actions, but you can only move and then shoot. it works, so closing this for now.
