### ISSUE TITLE
VizDoom: Defend the Center

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#138]
Another cool video on the VizDoom website (http://vizdoom.cs.put.edu.pl/) is the Defend the Center video.

There isn't any code for this scenario, but there is a defend_the_center.cfg and a defend_the_center.wad in the vizdoom subdirectories. Play around with these files. Try making a DefendTheCenter test in the vizdoom.examples package first, and once you get this working, create a proper task to evolve in: VizDoomDefendTheCenterTask

**Comment by Serenamidori** [comment]
Started this, and still having trouble starting. We'll look over this tomorrow.

**Comment by Serenamidori** [comment]
After changing back the parameters in #135, I can't get this game to run on the correct map. Changing what you pointed out in the main class won't let it run at all now. I get the following error and have no idea how to go about it. All I've figured out is that in TWEANN, numIn =/= inputs.length and we get an out of bounds error

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 200
    at edu.utexas.cs.nn.networks.TWEANN.process(TWEANN.java:689)
    at edu.utexas.cs.nn.tasks.vizdoom.VizDoomTask.oneEval(VizDoomTask.java:171)
    at edu.utexas.cs.nn.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:91)
    at edu.utexas.cs.nn.tasks.vizdoom.VizDoomDefendCenterTask.main(VizDoomDefendCenterTask.java:110)

**Comment by schrum2** [comment]
Check the number of inputs and outputs to the network. Also try running with asserts enabled. You can ask Alex how to do this.

On June 2, 2016, at 11:16 AM, Gab notifications@github.com wrote:

After changing back the parameters in #135, I can't get this game to run on the correct map. Changing what you pointed out in the main class won't let it run at all now. I get the following error and have no idea how to go about it. All I've figured out is that in TWEANN, numIn =/= inputs.length and we get an out of bounds error

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 200
at edu.utexas.cs.nn.networks.TWEANN.process(TWEANN.java:689)
at edu.utexas.cs.nn.tasks.vizdoom.VizDoomTask.oneEval(VizDoomTask.java:171)
at edu.utexas.cs.nn.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:91)
at edu.utexas.cs.nn.tasks.vizdoom.VizDoomDefendCenterTask.main(VizDoomDefendCenterTask.java:110)

**Comment by Serenamidori** [comment]
The Defend Center task works, but not well. I need a way to set certain actions to have rewards, would this be done in the config file, the specific task file, or both?

Additional issue- the view will not turn off when evolving outside eclipse, is there a way to figure out why? I've set watch to be false everywhere

**Comment by Serenamidori** [comment]
Located another issue- While I can change the size of the screen, the drawGameState method in VizDoomTask is not working for any resolution. It is working perfectly with the basic shooter task, so I'm wondering if the image buffer is different between this and that task?

**Comment by Serenamidori** [comment]
After letting the current build task run for a few hours, it's steadily getting better (6 generations so far since I can't turn watch off and it's taking longer). Still, none of the above issues are solved, and I can't figure out why the image buffer isn't working correctly for this task. I'll work with you tomorrow on this.

**Comment by Serenamidori** [comment]
I read the github comments- can you explain why we aren't utilizing health, ammo, or time anymore? I thought those were the necessary inputs for Defend the Center?

**Comment by schrum2** [comment]
We might add some of them back later, but for now I want to keep things
simple and uniform. I actually think the health and ammo may be more useful
in calculating fitness/reward values, but we'll see.
