### ISSUE TITLE
Comment code in package edu.utexas.cs.nn.tasks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#14]
Focus on the following classes:
LonerTask
NoisyLonerTask
SinglePopulationTask
Task

Others can be ignored for now

**Comment by Rollinsa** [comment]
Commented the LonerTask, NoisyLonerTask, SinglePopulationTask, and Task classes, with specifications of which portions were domain specific (some pacman variables that only applied for if pacman is the domain being used), as well as commenting out a small part of the LonerTask (the subPanels portion, which was used in HierarchicalTWEANNGenotype code that later become commented out and subPanels was no longer being changed from null prior to its later usage so was dead code)
