### ISSUE TITLE
Allow for various fitnesses for each population in cooperative coevolution

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#141]
#19 Allow for various fitnesses for each population in cooperative coevolution. Currently the code implements a basic cooperative coevolution domain where each population has a copy of the same set of fitness objectives (they just receive different fitness scores according to the average of the scores that they got on each team they were a part of). Extend it to allow for a different set of fitness scores/objectives altogether for each population

**Comment by Rollinsa** [comment]
PredPrey: Created four very specific fitness functions (2 pred and 2 prey), fixed a bug, added parameters. The four fitness functions are meant for cooperative coevolution, along with command line parameters for each of the functions, but they could also be used for any predPrey task, and may be desirable to try in the TorusPredPreyTask vs static controllers because of their simplicity and multi-objective properties. They are not yet being used in the code. Also, I fixed a bug with the PredatorMinimizeDistanceFromIndividualPreyObjective which would cause the minScore to be incorrect.

**Comment by Rollinsa** [comment]
Implemented the very specific new four fitness functions into the TorusPredPreyTasks (for either evolved prey vs static predators or evolved predators vs static prey without coevolution). Also updated the batch files (deleted one, added three) to support the change, and added the new functions to other scores as well (in the future, may want to take them away from the other scores since there will be so many). The original "IndivDist" batch file is now labeled "IndivPreyDist" (teams of predators vs individual preys), the "IndivPredDist" batch file is for individual predators against teams of prey, and the "IndivAllDist" batch file is for individual predators vs individual preys.

**Comment by Rollinsa** [comment]
Generalized the objectives and other scores lists in the predPrey world so that it is a list of lists, so that it can essentially contain various lists of objectives for each different population for coevolution. Currently, the code is still the same by just using only the 0 index of the double arrayList and putting everything as normal in that index as an arrayList, but now all of this code can be used by coevolution to make different sets of fitnesses for each population. I also compiled the adding of all of the objectives into a single method in the parent torusPredPreyTask that is simply called by the predator and the prey tasks and can be used later by cooperative coevolution. I also added a ToDo to make the double arrayList counterpart for objectives in the main MMNEAT class.

**Comment by schrum2** [comment]
Unless you can think of a compelling reason not to, I think we can restrict
all "other" scores to population 0. This should clear up clutter in results
when doing post-evals. Each population will have its own set of actual
fitness functions that influence selection, but only the first population
should track "other" score information.

**Comment by Rollinsa** [comment]
Caused only the first population to be given otherScores for less clutter and computation and greater efficiency.

**Comment by Rollinsa** [comment]
Fixed an error causing the cooperative coevolution not to run, found when attempting to generalize the code to add objectives for each population rather than just the first. This was because the otherScores were only being given to the first population so when the code attempted to read in the otherScores for the second population, there was an index out of bounds error. Fixed by making only the first population in otherStatsPerPopulation have the number of otherScores and having all of the other populations have a size of zero.

**Comment by Rollinsa** [comment]
Generalized the objectivesPerPopulation method for both predators and prey of the cooperative torusPredPrey task. This would have been an error in the future if the populations had a different number of fitnesses. Also cleaned up code in the cooperative task and torusPredPreyTask from when I was testing for errors

**Comment by Rollinsa** [comment]
Generalized the fitness functions ArrayList to be a double ArrayList so that it can support coevolution with different sets of fitness functions for each population. In order to support non-coevolution, the original single list of fitness functions, which is copied for each population, is just placed into the first index of the double arrayList in the case that coevolution is not happening.

**Comment by Rollinsa** [comment]
Created a new fitness function for the prey which takes an index for the individual prey to score for and gives it a score based on maximizing its distance from the closest predator to that prey. Added this new fitness to the prey otherScores. Created a new parameter for the predator and a new parameter for the prey for a cooperative coevolution setup giving the predator/prey multi CCQ to each agent individually and giving the predator/prey only the distance function(s) that correspond to that agent itself, not the whole team (so the predators and the prey will have different sets of fitness functions, although still the same number of objectives). Created batch files to run each of these new experiments, and ran these experiments on the server along with the other, original cooperative ones that have the same fitness functions. NOTE: (very important): still need to check that various sets of fitness functions will work with varying number of objectives, I suspect they probably won't.

**Comment by Rollinsa** [comment]
Created new fitness function for the predators for herding the prey (minimizing distance between the prey). Created a cooperative coevolving experiment with the evolved predators where the first predator is given this herding fitness and all other predators are given multi CCQ with the distance for that specific agent. Fixed errors across many classes preventing various numbers of fitnesses per populations from working (log, MMNEAT register fitness, etc). Now the ObjectiveBestTeamsExperiment and the postProcessing needs to be generalized to work for various numbers of fitnesses per population (coevolution in general) because right now they just assume that the first population's objectives are used for every population.

**Comment by Rollinsa** [comment]
Commented out the printing and processing of the objective scores in the ObjectiveBestTeamsExperiment because printing all of the other scores from the first population is enough information since other scores holds all fitness objectives. Altered NoisyLonerTask to be able to support only printing the other scores in the scoreSummary. This was all to clarify that the eval was actually still valid for coevolution with different sets of fitnesses by only looking at the first population for this reason (other scores from first population has all info required). Got postProcess working for coevolution (for various objectives for various populations)
NOTE: postProcess hyperVolumeProcessing only happens for the first population because it does not work with various fitnesses per population (coevolution)
