### ISSUE TITLE
fix cooperative coevolution for predPrey so that it can run (alter MMNEAT class)

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#142]
a189dad598072c2c379f9af47204c6dc7debf738

**Comment by Rollinsa** [comment]
Attempted to finish implementation of CooperativePredPrey, still needs work. Currently when the coevolution task is run, there is a null pointer exception at CooperativeCoevolutionMuLambda line 76, which refers to the size of genotypeExamples in MMNEAT. I assume that it is necessary to implement a utility method for the cooperative coevolution tasks which sets up the coevolving task, just like cooperative coevolving mspacman tasks in the MMNEAT class, but I am unsure how to do this.

**Comment by Rollinsa** [comment]
886a08b9dc98da0c3b5cbc41d33fbe8f6dc65afc

**Comment by Rollinsa** [comment]
#19

**Comment by schrum2** [comment]
There are still cooperative coevolution issues overall, but I think this particular issue is complete.
