### ISSUE TITLE
VizDoom: Use more of the screen

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#143]
Set up an option for all of the VizDoom tasks so that instead of using input from a specific row, they can use input from the whole screen. This can be a boolean command line parameters: doomFullScreenInput. Be sure to implement this in a way that it can easily be applied to any of the VizDoom subtasks.

I think that the default for the full screen input would be to include all values (RGB for all pixels). However, this is a lot of inputs, and may crash the system. Try also making a version that takes data for all pixels, but using only a particular color (R, G, or B).

When playing with this, test it at the lowest resolution and see if any progress is made.

**Comment by Serenamidori** [comment]
I looked into this while working on the issues with #138, and I think we will run into issues with the buffer considering what happened with Defend The Center, so I'll keep this issue on the back burner for now

**Comment by schrum2** [comment]
You should be able to move forward on this now, but try to implement the code that grabs the sensors using a static method in the VizDoomTask. That way it will be accessible to all sub-classes. Also, make sure there is a command-line parameter to choose between row inputs and full screen inputs.

**Comment by Serenamidori** [comment]
I've implemented the parameter and tested it so that it works, and added those changes to all the tasks as well. They should all be able to use the full screen for inputs given you set "doomFullScreenInput" to true in the batch file.
