### ISSUE TITLE
SelectiveBreedingEA (for Picbreeder)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#144]
Make a class called SelectiveBreedingEA that is an Evolutionary Algorithm you can use with Picbreeder. It should implement SinglePopulationGenerationalEA<T>.

The initialPopulation method can simply call the method with the same name in PopulationUtil

getNextGeneration should assume you are using a SinglePopulationTask<T> so that you can call the evaluateAll method. Then, create the next generation like so: discard any individuals with a score of 0, and keep any individuals with a score of 1. Then, fill newly opened slots in the next generation by mating and randomly mutating the survivors of the last generation.

The close method should close open logs (which should also be written to in the getNextGeneration method ... compare to the code in MuLambda)

**Comment by schrum2** [comment]
See #151

**Comment by leg2015** [comment]
Finished this task a few days ago. Still need to do some work on #151 but will close this issue for now and work on the other one
