### ISSUE TITLE
Implement save feature for picbreeder

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#147]
Add code that allows user to click on one or more pictures in screen and save them

**Comment by schrum2** [comment]
The best way to do this is probably with additional buttons below each image button. Each of these buttons would be labelled "save" and would give you a chance to specify a file name.

On June 2, 2016, at 1:54 PM, leg2015 notifications@github.com wrote:

Add code that allows user to click on one or more pictures in screen and save them

**Comment by leg2015** [comment]
Got a button up and running, everything works except the actual save itself

**Comment by leg2015** [comment]
Okay got the save working as well! It now saves to the MMNEATv2 directory!!
