### ISSUE TITLE
Improving Picbreeder

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#149]
Once #95 is complete, here are some improvements.

Add a restriction that makes sure the user selects at least one image on the screen before clicking evolve. In other words, clicking evolve without clicking some images first should either give a gentle error message (user is asked to try again without anything crashing), or should simply not be possible (button is grayed out and can't actually be clicked).

Also add a button in the top panel called Reset, which replaces the population with a completely new population.

**Comment by leg2015** [comment]
restrictions for all added. Got reset function working but right now it's hardcoded with a random TWEANN. Need to find a way to fix that, but going to go ahead and close this issue till we can work on thast
