### ISSUE TITLE
Comment Tetris Code

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#15]
The code can attempt to learn Tetris using a program called RL Glue (this will only work on Windows). It doesn't do very good though. The first step to getting a better Tetris-playing system is to understand the code better.

I didn't write this code. It is defined in the package org.rlcommunity.environments.tetris and its sub-packages. Comment this code, and clean it up a bit, for example by fixing compiler warnings and removing magic numbers.

**Comment by Serenamidori** [comment]
At this point, I've cleaned and commented most of the Tetris code, and enough to understand RL-Glue and tetris.
