### ISSUE TITLE
Implement network save feature for picbreeder

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#153]
save network along with image #147

**Comment by schrum2** [comment]
This should use Easy.save to create an xml file containing the network.

In general, I think it would be nice if clicking save actually prompted the user to enter a file name (which would be applied to both the picture and the network).

This will take some searching the internet, but there should be a way for clicking the button to trigger a pop-up window with a field to enter a name in, and both OK and Cancel buttons to click.

**Comment by leg2015** [comment]
gave it a shot trying to get a save name figure out but didn't go as planned. Will try again..

**Comment by leg2015** [comment]
Tried again, still not successful..

**Comment by schrum2** [comment]
Some more details in these comments would be useful.

Even without the file name prompt, saving the network xml file using Easy.save should be fairly easy.

**Comment by leg2015** [comment]
Got this done in issue #154
