### ISSUE TITLE
Competitive Coevolution (Pred/Prey)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#155]
I think that once you complete #141 you might be able to extend CooperativeTask to create a competitive coevolution variant of pred/prey. Despite the name, I think the code in CooperativeTask is actually general enough to handle both types of coevolution, though you will of course need to specialize the task that extends CooperativeTask to implement competitive coevolution in the Pred/Prey domain. If this works, we will rename CooperativeTask to indicate that it works in both contexts.

The first shot that you take at competitive coevolution in the pred/prey task should work as follows:
There are two populations: one for prey, and one for predators. The preys will have their sensors and the predators will have their sensors (they may be different), and (importantly) the prey and predators will definitely have different fitness functions. Because there are only two populations, the individual from the predator population will be copied into all members of the predator team, and the individual from the prey population will be copied into all members of the prey team. This is how things ran in the original static enemies version you started with.

The reason CooperativeTask should work depends on a change in how you think about some of the variable names. Think of "teams" as "match-ups" or "challenges". Either way, you need to select members from each population. Since each population will have its own fitness functions, and already evolves independently, competitive and cooperative should work the same ... but be sure to post about any problems you encounter.

**Comment by Rollinsa** [comment]
Implemented competitive coevolution. It extends the cooperative coevolution task in the torusPredPrey world, so in the future I will correct all of the cooperative references that are being used now by both competitive and cooperative coevolution. These false references are in both the torusPredPrey domain and also scattered throughout the overall coevolving domain (nsga thing). TODO: change cooperative names

**Comment by Rollinsa** [comment]
Fixed the monitorInputs for PredPrey competitive coevolution
00a0b4bae47cf2e97eec90c71a190c6add65fe69

**Comment by Rollinsa** [comment]
Fix postProcess #205 and change cooperative names to more general names since many are also used by competitive coevolution

**Comment by schrum2** [comment]
I did the mass rename of files with commit e8450f669725e89e5c107a531170b259e79af46e . This removes the term Cooperative when the class is actually more general.

I believe I've also changed the needed parameters in all of the batch files. However, one of the batch files crashed when I ran it. I wasn't sure if this was my fault, or caused by the previous addition of competitive coevolution. So, be sure to check that all of the coevolution batch files run. Once you confirm they all work, you can close this issue.

**Comment by schrum2** [comment]
Also, some of the post processing experiments may need to have cooperative removed from their names as well, which would also require changes in the batch files. Make these decisions on a case-by-case basis.

**Comment by Rollinsa** [comment]
Along with getting post processing to work for competitive coevolution, I would also like to get competitive coevolution to work better in general. Experiments showed behavior of the predators as very poor, never able to catch much prey at all, even with some fluctuation as the two evolved together. This might be fixed by doing cooperative and competitive coevolution together (at the same time), so that is what I am doing next (after post process for comp coevolution).

**Comment by Rollinsa** [comment]
Completed #209 
See #207 for making competitive coevolution better (by adding cooperative coevolution to it).
