### ISSUE TITLE
HyperNEAT: different substrate alignment for Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#157]
The loopThroughLinks method in HyperNEATCPPNGenotype applies the same coordinate frame for all HyperNEAT substrates. This does not make sense in every domain. For example, in Tetris, the bottom of the screen should have a y coordinate of 0, but the default approach centers y in the game world.

We need a general solution to this. 

The trick is to replace the calls in loopThroughLinks to CartesianGeometricUtilities.centerAndScale with something more general. I would like for there to be a class parameter in the command line that defines how coordinates are mapped and scaled in the HyperNEAT substrate. Essentially, we an interface called SubstrateCoordinateMapping with a single method: 
transformCoordinates(Tuple2D toScale, int width, int height)

The current way we do things could be represented by a class called CenteredSubstrateMapping whose transformCoordinates simply calls CartesianGeometricUtilities.centerAndScale.

Then you could make an alternative mapping for Tetris ... this would scale the y values from 0 to 1, but the x values would still go from -1 to 1.

**Comment by leg2015** [comment]
Look at class cartesianGeometricUtilites at centerAndScale method

**Comment by Serenamidori** [comment]
We've implemented the new interface SubstraeCoordinateMapping and created a class parameter called substrateMapping to allow us to choose which mapping to use in the batch file. There is a center and a bottom version, where the bottom one is new and uses center to map x coordinates, but a new bottom scaling method to map the y coordinates.
