### ISSUE TITLE
Comment  and JUnit test MLP class

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#158]
We may need to use a more efficient network representation for HyperNEAT than the TWEANN. This will require generalizing the MLP class, but first we need to understand it. Comment the class and create JUnit tests.

The JUnit tests should involve the creation of very small MLPs combined with tests that check for exact outputs occurring in response to particular inputs. For example, let's say an MLP has one input, one hidden neuron, and one output. Because the activation function is tanh, an input x would have this output:

tanh(weight_output \* tanh(x \* weight_hidden))

Then, if the network had two inputs and two hidden neurons, and one output, then inputs x1 and x2 would result in:

tanh(wo1_tanh(x1_wh11 + x2_wh21) + wo2_tanh(x1_wh12 + x2_wh22) )

These tests and a few others should be conducted.

**Comment by leg2015** [comment]
FYI I was reading Togelius's paper on car racing coevolution where he used MLPs and had some interesting objections to using MLPs for evolution. Might wanna take a look at it http://julian.togelius.com/Togelius2007Multipopulation.pdf

**Comment by schrum2** [comment]
Directly evolving MLPs can be problematic, but with HyperNEAT we're
actually evolving the CPPN. The CPPN then creates an MLP, but this
side-steps the difficulties of evolving the MLPs directly.

**Comment by leg2015** [comment]
Finally got junit test done on MLP class
