### ISSUE TITLE
Create after-state evaluator for Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#16]
The current evolved Tetris play performs poorly because it makes a primitive action on every time step of simulation. A more reasonable course is to make a new decision on each piece. Specifically, given the emergence of a new piece, consider each location and orientation in which is could be placed, and pick the placement that results in the best after-state. In other words, given features about the game state, which placement leads to the best state?

First there will need to be code that, for a given game state and a given Tetris piece, determines every possible placement/orientation of that piece in the game state. A related function that is also needed is one that returns the resulting after states for each possible placement.

A Tetris playing agent needs to be created that takes each new piece, gets all possible after-states from each possible play with that piece, applies some function evaluator (like a neural network) to each after-state to get a score, and then picks the placement resulting in the best score.

Finally, given a chosen placement, there needs to be code that performs the required sequence of primitive actions to cause that placement to happen.

This issue will obviously need to be completed in several steps. Add follow-up comments to this issue as each step along the way is completed or worked on.

**Comment by schrum2** [comment]
Look at the edu.utexas.cs.nn.tasks.rlglue.featureextractors.tetris package as well when working with this code.

**Comment by Serenamidori** [comment]
To update, we have added the TetrisAfterStateGenerator that goes through every position for every orientation and figures out each resulting "end state" with the actions on how to get to that state. So far, we still need a way for this to talk to the feature extractor and a way to score these end states (Easiest way would be to also check the score after rows are cleared and figure out which is best, ties being resolved by random)

**Comment by Serenamidori** [comment]
Update: Currently testing our files to see how the AfterStateAgent works in the RLGlue Tetris Environment. We've been slowly improving the Agent and Generator files, testing them both as well as the BertsekasTsitsiklisExtractor, but I believe we have more work for the Generator before closing this issue.

**Comment by Serenamidori** [comment]
Update: Going to close this issue, because the TetrisAfterStateGenerator was created and completed, and the Tetris agent can utilize it. Any improvement can be made into another issue.
