### ISSUE TITLE
Picbreeder pop size, rows, height

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#160]
Having to set these three different commandline parameters seems a bit complicated.

The mu parameter should definitely set the population size, but the row and height parameters should only be for display purposes ... the pop size can be more than rows \* height. However, this will require a more complicated user interface that supports a scroll bar to go through images that don't fit on screen.

**Comment by leg2015** [comment]
Changed it so the number of columns is a set constant, 4 and then the smallest factor that is larger than mu when multiplied by 4 is set to the number of rows. I then reset mu to be the number of rows so there are no empty buttons. That will mean that the number set as mu does not always correspond to the number of buttons but that is okay I think in the framework of the project. Still working on a scroll bar though

**Comment by leg2015** [comment]
I think adding a scroller is not necessary. In the original implementation of picbreeder the size of the population was fixed. Don't see why it's wrong for us to partially fix the size too

**Comment by schrum2** [comment]
I just think it would be nice to work with bigger populations.

An alternative to the scroll bar would be to scale the images to a smaller size if the population is really big.

This isn't necessarily a high priority issue, but I would still like to keep it open as a possibility, so I'm re-opening this issue.

**Comment by leg2015** [comment]
Got mu all fixed. Still haven't added the functionality where scroll bar can be employed and num columns is still constant

**Comment by leg2015** [comment]
Got resizing of JFrame to fit

**Comment by schrum2** [comment]
I'm happy with the resizing ... we can leave out the scroll bar. I'm going to close this.
