### ISSUE TITLE
implement undo method

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#162]
This also requires getting the generational log up and running properly so that the previous generation can be called and displayed.

**Comment by schrum2** [comment]
Although we had a really rough time implementing this, I have an idea that might make it easier.

The PicbreederTask already saves the scores of the population being evaluated in a global array list. Add another array list of scores called previousScores. Whenever evaluateAll is called, before resetting the scores list, copy all of its contents over to previousScores. Then, if UNDO gets clicked, replace all images being displayed with images generated by CPPNs in the previousScores list. Then empty out previousScores.

This approach will only allow UNDO to be successfully clicked once ... it won't be possible to keep going back through the history, but this would still be a cool feature. However, I think that code should be added that disables the UNDO button from even being clicked when previousScores is empty. This is very common in user interfaces ... buttons get grayed out, and can't be clicked.

Don't worry about fixing the generation number or logs. We'll just double-count the generation where UNDO is clicked.

**Comment by leg2015** [comment]
added the previousScores method like you said, got it up and running I think. Still weird errors though. The undo button does in fact undo the action, but as soon as it's done putting all the pictures up, it throws an arrayOutOfBounds error. It's to do with the score.size() and I tried troubleshooting why it wasn't working. Will try again tomorrow for troubleshooting

**Comment by leg2015** [comment]
Got undo button to finally work! Still only goes back one generation but that may be all we need at this point
