### ISSUE TITLE
Add check boxes corresponding to each activation function in picbreeder

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#163]
The idea is to have checkboxes at the top of the screen where the user can choose which fitness functions to include

**Comment by schrum2** [comment]
Clarification: we're not turning "fitness" functions on and off, but rather "activation" functions.

**Comment by schrum2** [comment]
All that checking/unchecking the boxes should do is call Parameters.parameters.setBoolean for the corresponding activation function.

**Comment by leg2015** [comment]
Added checkboxes and got that working. Parameter booleans for functions are changed. However, it appears as nothing is happening. I think it may be that the parameters are being changed but are not being reloaded into MMNEAT. I looked for a method that might do this, but I couldn't find one. Checkboxes should be ready to roll and functional once this problem is fixed

**Comment by schrum2** [comment]
I believe I've fixed this issue with my latest commit. However, please test
it to make sure it works.

Additionally, I think check boxes for other activation functions (that we
haven't really tried with Picbreeder yet) should also be available,
although disabled by default. However, if this leads to weird results, feel
free to disable them again.

I also have one more kind of cool idea in mind, but feel free to drop it if
it ends up being too difficult: What if each of the check boxes has the
same color coding at the neurons in the network when the network view is
chosen? It would help us understand what is happening with the evolved
networks.

**Comment by leg2015** [comment]
Got this all working
