### ISSUE TITLE
monitorSubstrates for HyperNEAT

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#170]
Make a parameter that can be used with HyperNEAT tasks called monitorSubstrates. This will create a visualizer for each substrate of the HyperNEAT phenotype, and allow us to see not just the inputs, but the hidden activations. This essentially replaced monitorInputs, which is used normally for NEAT networks, but actually goes beyond because it monitors the hidden activations as well.

In fact, you may want to look at how the command line parameter called "animateNetwork" is used. This actually animates a controller network as it is used in a task by changing the sizes of the different neurons as an indication of activation level. The substrate visualizer should essentially be based on the same principle: whenever the network processes activations, the animated values change.

**Comment by Serenamidori** [comment]
Added the parameter (9f0a4024d80e2a55c3d08576e114fc60c60574e7) but not sure where to check for it, waiting until other bug is fixed

**Comment by schrum2** [comment]
Should be able to make progress using the code that Lauren started and I elaborated on: https://github.com/schrum2/MM-NEATv2/commit/fc6b6ec6faa37b03e3f1b5361c76638468c8d59a

There is already code in the process method of the TWEANN class that animated networks under normal circumstances. The substrate animation code should be executed from the same place, but only when HyperNEAT is being used.

**Comment by leg2015** [comment]
got monitorSubstrates working along with animateSubstrate!
