### ISSUE TITLE
stepByStepTetris parameter

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#171]
A new command line parameter for Tetris called stepByStepTetris. This is specifically meant to be used with the after state agent. It does NOT pause the game after each action ... rather, it pauses the game after the after-state agent checks each possible after state. Nothing on the game screen should change as a result of this, but if monitorInputs or monitorSubstrates ( #170 ) is being used, then this ability would allow us to closely monitor how the network analyzes each after state.

**Comment by Serenamidori** [comment]
Parameter has been added, and an if check in TetrisAfterStateAgent makes sure to pause after each policy call.
