### ISSUE TITLE
Change/Mutation rate for Picbreeder

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#173]
It would be nice to have a slide bar in picbreeder for specifying the amount of change between subsequent generations. Basically, you can put the mutate calls in SelectiveBreedeingEA inside of loops. The default would be for those loops to run once, but the slide bar in Picbreeder could be used to increase the iterations of that loop up to some limit (say 10). This could allow for more divergence between generations.

**Comment by leg2015** [comment]
Got slider up and running but needs some interface fixes, such as resizing on default screen and adding labels

**Comment by leg2015** [comment]
Got the sizing all figured out and got labels to show up on slider as well
