### ISSUE TITLE
Make a method called drawSubstrates

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#176]
Should draw all relevant substrates and color them based on color scheme blue = neg input red = pos input for input layer and for output layer have it be scaled from -1---0---1 to 255R----0----255B so the hue values match the activation. For output, use ColorFromInt method to assign a different color to each afterState that colors output layer

**Comment by schrum2** [comment]
Duplicate of #177

**Comment by leg2015** [comment]
Tried adding JUnit tests to see if your version works, but didn't make much headway. Having trouble setting up a task where we can extract substrate information adequately

**Comment by leg2015** [comment]
Finally got it working and places substrates in order so they are more easily visible
