### ISSUE TITLE
Turn VizDoom into a HyperNEAT Task

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#178]
Even though we don't quite have HyperNEAT working, you can still make the VizDoomTask implement the HyperNEATTask interface so that it can implement all of the necessary methods. Lauren should be able to give you guidance on how to do this, and you can also look at how it is done in the HyperNEAT tetris task.

**Comment by Serenamidori** [comment]
So far we've set up for substrates to be created and we've testing a smudge and row version of inputs to see if the agent can learn better. Also, I'm slowly adding the correct calls for outputSubstrateSize with issue #208 :+1:
