### ISSUE TITLE
PDF Plot file for post processing

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#179]
The plotAverageFitnessesFile method of the ResultSummaryUtilities class is responsible for making the plot of the averages across several evolutionary runs. Add code so that an additional plot file that creates a PDF plot is also created.

**Comment by schrum2** [comment]
In fact, make sure all methods in this class that produce a plot file (plotHypervolumesFile and plotInfoFile, but check for others) also produce a PDF version, but avoid duplicating code (you can probably generalize the methods, and then simply call them twice with a pdf parameter set to true then false.

**Comment by Rollinsa** [comment]
Implemented the automatic creation of pdf files when plot files are created for the postProcessing. Note: PostProcess as a function still does not work for coevolution.
