### ISSUE TITLE
Grid-World Pred/Prey World Agents: Add Stop Action

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#18]
Agents in the Pred/Prey torus grid world should have access to a "do nothing" action that allows them to simply stay still. The availability of this action should be optional (depending on a command line parameter), and there should also be an ability to grant the action to some agents (predators) but not others (prey).

**Comment by Rollinsa** [comment]
Implemented the Do Nothing action option for both prey and predators.  A boolean parameter option was added for each and is determined as a command line parameter. Neither, one and not the other, or both can be allowed to perform the do nothing option. There was a commit error that was resolved when adding it to the master and synching, but this stopped me from providing a descriptive comment on the gitHub add (after Gabby did the merge on the command line). This all required some changes or small tweaks/additions to the gridTorus, gridTorus controllers, and tasks.gridTorus project classes, as well as the two added boolean parameters
