### ISSUE TITLE
Provide additional critical values for the t-test

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#180]
The tValue method in ResultSummaryUtilities is newly added, but pretty limited. The t-test is a statistical test for determining if two seemingly different outcomes are really different in a statistical sense (if two average values are different enough to tell that one is actually better than the other).

The test depends on critical t-values which are difficult to calculate. It isn't worth our time to try writing the code to properly do these calculations ... in fact, it's not really worth anyone's time. Most people use a table, like this one: https://www.medcalc.org/manual/t-distribution.php

Hard code additional values into the tValue method for rows DF = 1 through 29 (runs = 2 through 30), using the column with 0.95 over 0.05. When you do this, note that the table value DF is one less than the number of runs in the tValue method. This is why when runs == 30, the value 2.045 is returned, which corresponds to DF = 29.

**Comment by schrum2** [comment]
Also, this method should be moved to the StatisticsUtilities class.

**Comment by leg2015** [comment]
Moved the method to StatisticsUtilities, added the other values and added a testing method to the corresponding JUnit test case
