### ISSUE TITLE
Cleanup MMNEAT

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#181]
The MMNEAT class is a bit of a mess. However, a lot of important code is here, so it can be a bit dangerous to muck around in it. I would like you to refactor it without changing anything, in the following way.

Note that most of the code is static methods ... in particular, many are specifically associated with Ms. Pac-Man. However, some are specifically associated with other tasks. I want you to move the code associated with specific tasks to other classes.

For example: Make a class called MsPacManInitialization in a new package edu.utexas.cs.nn.tasks.mspacman.init. Move the static methods in MMNEAT that are exclusively associated with MsPacMan to this new class. However, if the method deals with other tasks in addition to MsPacMan, do not move it. There are a lot of methods for various types of coevolution in Ms Pac-Man, but not all coevolution code is for Ms Pac-Man ... some of Alex's Pred/Prey code uses it now, but you can check with him if you are uncertain.

Do the same for RLGlue (though setupRLGlue might be the only method in the class you make).

After cleaning out all of the complicated Ms. Pac-Man methods, take a shot at commenting the methods that remain in the MMNEAT class.

**Comment by Serenamidori** [comment]
Currently done with moving the MsPacMan methods, moving on to RLGlue

**Comment by Serenamidori** [comment]
Moved RLGlue and started doing some comments, closing this for now!
