### ISSUE TITLE
Generalize launchMultiple.bat

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#182]
Currently, this file takes a parameter N and launches experiments with run numbers 0, 1, ..., (N-1)

Modify this to take two parameters A and B instead, then run experiments with numbers A, (A+1), ..., (B-1), B.

This generality will provide us more flexibility.

Also, make it so that each individual experiment that is launched uses the START command so they can run asynchronously (see here: http://stackoverflow.com/questions/1449188/running-windows-batch-file-commands-asynchronously). This should provide us a way to launch several jobs simultaneously ... however, we'll have to be careful we don't launch too many at the same time. In fact, here is one more change:

Multiple processes running asynchronously in the same window will create garbled output to the console ... this doesn't matter too much, but there is a chance we might want the output. Therefore, every experiment launched from the batch file should send its output (using >) to a log txt file instead of the console.

**Comment by Rollinsa** [comment]
Generalized the launch multiple batch file so that the user specifies the starting and ending run numbers. Also allowed the batch file to be able to handle two different sets of experiments in one run. Now I will create a batch file that will do all of the same things as this one, except that it will run the experiments asynchronously rather than simultaneously

**Comment by Rollinsa** [comment]
Created asynchronous launchMultiple, which runs all of the specified experiments at the same time in different command line windows. This way, each experiment can still be seen as they run. WARNING/DISCLAIMER: do not give this batch file too many experiments at once, or your computer may explode
