### ISSUE TITLE
Generalize ResultsSummaryUtil to work with Coevolution

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#183]
Currently can't process coevolution experiments, but when looking at the code, it looks like it should. The process method in MMNEAT actually has special cases set up for a MultiplePopulationTask. Maybe the file names are just off. Try to track down the issue.

**Comment by Rollinsa** [comment]
Fixed problems causing postProcess to not work with coevolution. Specifically, it now works with cooperative coevolution with the torusPredPrey. Some work arounds had to be done and may need to be changed later, especially once various sets of fitness functions for each population are implemented. These work arounds are marked with TODO comments in the code.
