### ISSUE TITLE
JUnit test SubstrateMLP

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#188]
After #186 

Once completed, this new class should behave identically to the TWEANNs generated by HyperNEATCPPNGenotypes. Therefore, the way to unit test them is to take a HyperNEATCPPNGenotype and first use its getPhenotype() method to get a TWEANN, then use the CPPN to create a SubstrateMLP. 

Then generate a bunch of completely randomized inputs for these two different types of networks, and verify that for any given inputs, each different type of network produces exactly the same outputs.

**Comment by schrum2** [comment]
Additionally: since this new type of network should behave the same as a TWEANN in terms of input/output mapping, its only purpose is to be faster than the TWEANN. Verify that this is the case. Given a list of 100 (or more if needed) input sequences, time how long the SubstrateMLP takes to process them vs the TWEANN. This should actually be a JUnit test ... verify that the SubstrateMLP takes less time.

**Comment by leg2015** [comment]
Made some good headway on this but there appears to be a genuine bug in the MLP class that gives us improper outputs

**Comment by schrum2** [comment]
Please resolve any remaining tests needed here. In particular, do the timing test. We need to know if this new approach is actually faster (if not, then all of this work is for nothing).

Note: there are some minor speed ups still possible in the SubstrateMLP class, so even if it is not faster at first, we may be able to make it so. Then again, if the gains are small, then all of this extra complexity is pointless.

If the speed tests have good results, then we can focus on creating a Genotype class whose phenotype is a SubstrateMLP.

**Comment by leg2015** [comment]
Added a new test for speed and it appears that the mlp is almost twice as slow as the tweann, which is not reassuring. Not probably going to be worth exploring the substrateMLP avenue anymore so will close this issue
