### ISSUE TITLE
Intelligent scaling of eval times

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#189]
In many domains (like VizDoom) evaluations are very costly. Additionally, they are noisy (different evals have different outcomes). However, early in evolution, agents are fairly bad, so it probably isn't worth evaluating them multiple times to make the scores more accurate.

Once possibility to help this problem is to scale the number of evaluations across generations. Basically, in early generations, we do fewer trials per network, then as the number of generations increases, we do more trials per network (since we really care about well these agents perform).

There should be a parameter (boolean) that decides whether we want to scale the number of trials. Then, the actual number of trails for evaluation at each generation would be something like:

(int) Math.ceil((((double)currentGen)/finalGen)*numTrials)

**Comment by Serenamidori** [comment]
Note- this will be in NoisyLonerTask, and it'll only need 1 parameter

**Comment by Serenamidori** [comment]
Having trouble proceeding- Where in evaluate() should this be calculated? And how to I get access to the current generation number?

**Comment by Serenamidori** [comment]
Also- I just found the method trialsByGenerationUpdate in CommonConstants- is this something that can help? It looks like it does something similar to what you described, but I only see it being used by MuLambda.

**Comment by Serenamidori** [comment]
The parameter is added, tested, and synced now :+1:
