### ISSUE TITLE
Coevolution in Pred/Prey Grid-World

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#19]
After generalizing the pred/prey world a bit to evolve predators or prey separately, create a new class/task that performs coevolution between agents of each type.

**Comment by schrum2** [comment]
There are several options here. You may want to break them into several separate "issues." 

Cooperative: Adjust your current system so that the prey are still static, but each predator agent comes from a different population. You would essentially have one sub-population per predator agent, but the prey would still be static (naturally, this could be swapped around to have static predators and evolving prey). This probably isn't as interesting, but would be easier, and good practice to working toward the next approach.

Competitive: There are two evolving populations ... one that supplies a brain to all predator agents, and one that supplies a brain to all prey agents. You would need to create a new EA, but it could probably take advantage of multiple instances of NSGA2 (something like what the existing cooperative coevolution class does).

**Comment by schrum2** [comment]
If/when you make a coevolution algorithm, but sure that it is general enough to potentially be used in other domains, for example Breve2D #120 and Ms. Pac-Man. Once again ... feel free to create new issues to handle all of the different facets of this problem.

**Comment by Rollinsa** [comment]
Created batch files for the new cooperative coevolution tasks

**Comment by Rollinsa** [comment]
Finished up with cooperative coevolution. Now for competitive coevolution!
SEE #155
