### ISSUE TITLE
Create MarioTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#191]
Super Mario is now integrated into our code. It's time to make a MarioTask so that we can evolve agents using out system. This will require changes in many parts of the code, but we basically want to set up a neural network to play the game.

The code in the ch.idsia.scenarios.Evolve seems to already do this, but we want to evolve agents using our system instead of their simple EA. Still, looking at that code should give you an idea of how to set up an evaluation for Mario.

**Comment by Serenamidori** [comment]
I tried to run play like you said on 856a2c9a6cc6dc0f7f0fc2cb418733855d1aec04 but I get an error. Is there something I should do to fix file paths or something? (javax.imageio.IIOException: Can't read input file!)

**Comment by Serenamidori** [comment]
Thanks to your help, we've got a MarioTask, NNMarioAgent, and a hook in MMNEAT. It's now currently able to run by batch file, but it's just not evolving anything yet.

**Comment by Serenamidori** [comment]
Task's been created, and I'll be focusing on sub-issues now
