### ISSUE TITLE
Consolidate stepByStep parameters

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#196]
Instead of having stepByStepPacMan, stepByStepVizDoom, and stepByStepTetris parameters, just have one stepByStep parameter that is used in all of these places.

Additionally, when doing a step-by-step evaluation in Tetris, print to the console the evaluation score (from the network) of the evaluated state on each pause.

**Comment by schrum2** [comment]
Also, once you have done this, add a new batch file called postBestObjectiveWatchStepByStep.bat.
It should be identical to postBestObjectiveWatch.bat, except it sets the stepByStep parameter to true.

**Comment by Serenamidori** [comment]
Consolidated the stepBySteps (4ac80c8b091c8862bdd02b8389bd2bdc1dc6b373) and I'll be making that post.bat now

**Comment by Serenamidori** [comment]
And added postBestObjectiveWatchStepByStep.bat 5c8f2e6bb404f9d56077d6c4260376a510be1c7f :+1:
