### ISSUE TITLE
New substrate mapping function for Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#206]
This one should be just like the BottomSubstrateMapping, except it should always return an x coordinate of 0. This will make all columns be copies of each other in terms of their link weights, which might make sense in Tetris. Call the class Bottom1DSubstrateMapping, and make a corresponding batch file for using it.

**Comment by leg2015** [comment]
Added the new substrate mapping to the Tetris task. Will start running tests on the server now using it
