### ISSUE TITLE
Add VizDoom Task

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#21]
I just added VizDoom as a domain. The vizdoom.examples package has basic examples of running the VizDoom domain. The file Basic class has a very simple example of an agent trying to shoot a single monster. Make a NoisyLonerTask that evolves an agent for this Basic version of the game.

**Comment by schrum2** [comment]
Created VizDoomBasicShootTask and VizDoomTask. The VizDoomBasicShootTask emulated the Basic example provided for VizDoom, but so far it just makes random actions. It doesn't actually use a neural network to make decisions. Need to figure out how to read screen info and feed it to the network. Might want to start small and do something very simple instead of actually reading raw screen pixels.

**Comment by Serenamidori** [comment]
Currently we have RGB Helper methods for debugging and basic implementation for neural networks, but we run into this error when trying to run the second episode:
[Exception in thread "main" vizdoom.ViZDoomIsNotRunningException: Controlled ViZDoom instance is not running or not ready.]
Our next move is to figure out how to get the next games to play, and then we can start to work on features/fitness.

**Comment by schrum2** [comment]
Once you complete an evolutionary run of this (even if it is only a few generations and the visuals are still turned on) go ahead and close this issue.

**Comment by Serenamidori** [comment]
We need to find a way to make VizDoom actually evolve, we have the inputs pieces in place but it's not actually learning anything

**Comment by Serenamidori** [comment]
Vizdoom is evolving now, will comment results and close when you tell me to

**Comment by schrum2** [comment]
I think this one is good to close. I'll give you new issues for more specific VizDoom task variants.
