### ISSUE TITLE
Parameter: extraHNTetrisLinks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#212]
Make a parameter extraHNTetrisLinks that adds extra connections between HyperNEAT substrates in the HyperNEATTetrisTask. Basically, all this parameter does is add an extra pair to the substrate connections so that the input layer will be connected directly to the output layer (in addition to the processing layer).

Make a batch file for trying out this new parameter using the Bottom substrate mapping, and test it out on the server. Try it with the 1DBottom mapping as well.

**Comment by leg2015** [comment]
Added this parameter and necessary changes to hyperNEATTetrisTask. Running in a test batch file now. Will close once I check batch file tests

**Comment by leg2015** [comment]
It works for sure, so going to close this issue and start some runs on the server using extraLinks
