### ISSUE TITLE
Split up edu.utexas.cs.nn.experiment package

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#213]
Add sub-packages beneath edu.utexas.cs.nn.experiment for edu.utexas.cs.nn.experiment.evolution and edu.utexas.cs.nn.experiment.post. Refactor/move the post-eval experiments into the post package and the evolution experiments to the evolution package. You will also need to update many batch files ... check ALL of them.

**Comment by Rollinsa** [comment]
Split up edu.utexas.cs.nn.experiment package into experiments for post and experiments for evolution
