### ISSUE TITLE
Improvement to substrate monitoring

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#214]
If a neuron in the substrate network has no outgoing links, then it doesn't matter what its activation is. Therefore, in the visualization, I would like all of these grid cells to have the color gray. This will display the dead neurons have hopefully give us greater understanding.

**Comment by leg2015** [comment]
Should be up and running. Am doing a batch file experiment right now to check.

**Comment by schrum2** [comment]
Fixed with 03d1cad78f674b7f76b71e7a92173c0c809a48eb
