### ISSUE TITLE
Raw Tetris: sense holes differently

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#215]
If the latest HyperNEAT Tetris experiments are still mediocre, then here is another idea to try. Add a parameter (you decide the name) that senses the holes differently in the raw extractor. Specifically, the sensors should return the following values:

1 if there is a block there
0 if it it empty, but not a hole
-1 if it is a hole

A hole is an empty space that is underneath at least one block (ask Gabby if clarification is needed). It may still be accessible from the side if a piece can be slid in, but these still count as holes.

By the way, this new feature is incompatible with the absenceNegative option, so in the constructor an error message followed by System.exit(1) should occur if both this new option and absenceNegative are true.

Once the code is in place, make a new batch file to test it and run in on the server.

Note: if this still does not work, then another option is to have two completely different input substrates: one for the blocks and another for the holes. However, let's put this off until we've tried everything else.

**Comment by leg2015** [comment]
Think I got this working. Am running batch files now to confirm

**Comment by leg2015** [comment]
It's finally working! Have started some batch files with this parameter on in the server so by tomorrow we'll be able to see how well it does
