### ISSUE TITLE
Use multi-modal in the PredPrey domain

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#216]
Use and test multi-modal domain with homogeneous preds, cooperative preds, homogeneous competitive, and cooperative competitive coevolution

**Comment by Rollinsa** [comment]
PredPrey: Created batch files to run multiModal in predPrey world. Updated batch file naming. Fixed bug with multiModal and cleaned up code with sensorLabels.

**Comment by Rollinsa** [comment]
The above comment is for multiModal with homogenous predators against static prey

**Comment by Rollinsa** [comment]
PredPrey: Created batch files to run multiModal in predPrey world for homogeneous predators vs static prey. Updated batch file naming. Fixed bug with multiModal and cleaned up code with sensorLabels.

**Comment by Rollinsa** [comment]
Created batch files to run and test multiModal usage for Cooperative Pred

**Comment by Rollinsa** [comment]
Allowed for multiModal in cooperative predPrey

**Comment by Rollinsa** [comment]
Created batch files to run and test multiModal usage for Competitive Predators, and they run (so it works with competitive multi-modal predPrey after fix for cooperative multi-modal predPrey)

**Comment by schrum2** [comment]
Running some experiments using multimodal extensions is also something we should pursue soon, after the sensor issues are fixed.
