### ISSUE TITLE
Bias inputs for HyperNEAT substrate networks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#217]
We've already discussed how bias inputs for networks are theoretically important. The network may have trouble learning certain things without a bias.

The CPPNs themselves have a bias input, but the substrate networks don't. We could simply add a bias input to each HyperNEATTask, but since the bias is not part of the task geometry, this would mean having an extra 1X1 substrate for each task, and making sure that the inputs included this constant bias. This is not very clean.

An alternative way of doing this that other HyperNEAT implementations use is the following: Add yet another output per pair of connected layers to the CPPN. So, if layers A and B are connected, we will now have one output for the link weight, we might have another output for LEO, and now we might have another output defining the bias (this option should be controlled by a command line parameter).

Here is how the bias output of the CPPN is used. We will be defining a different bias value for each neuron.This is the same as having a bias input connected to each neuron by a different weight ... we're basically skipping the constant bias input of 1 and going straight to storing the result of 1*weight (which wouldn't change) in each of the receiving neurons.

To figure out the bias value of a neuron, make (X1,Y1) = (0,0), and may (X2,Y2) be the coordinates of the neuron in question. Then read off the value of the bias output for the particular layers being connected in the CPPN. You'll get one value corresponding to each neuron in that layer.

We will need to save these bias values somewhere ... I'm not sure what the best way to do this is yet. We'll probably need to edit the Node class within the TWEANN class so that each neuron can store its internal bias ... whenever the Node gets reset/flushed, its sum would need to be reset to its bias rather than 0. This saving of node bias values in the neuron would need to happen when creating the phenotype in HyperNEATCPPNGenotype. The best place is probably inside of the createNodeLinks method ... you could call another method that fills out the bias values for each node (The Node class in TWEANN would need to have a setConstantBias method added)

**Comment by leg2015** [comment]
Added new boolean command line parameter, evolveHyperNEATBias

**Comment by leg2015** [comment]
Added to MMNEAT so index of output from cppn is updated correctly

**Comment by leg2015** [comment]
Added bias to node class in both tweann and tweannGenotype

**Comment by leg2015** [comment]
Implemented bias in hyperneatcppngenotype. All that is left is some testing

**Comment by leg2015** [comment]
Got it set up and junit tested. Therefore, will close this issue
