### ISSUE TITLE
Make a JUnitTestingTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#22]
The way I've been resolving the errors with some of my informal testing code is by adding "task:edu.utexas.cs.nn.tasks.breve2D.Breve2DTask" to the initializeParameterCollections command. The reason this is needed is that when MMNEAT.loadClasses() is called, it does some specific setting up of global variables related to general network configurations based on the task. Using the Breve2D task is probably not the best idea. There should be a simplistic dummy task for testing purposes only that is used instead. This task should create small networks (say 5 inputs and 3 outputs). Change all informal tests to use this newly created task instead of the Breve2D task.

**Comment by leg2015** [comment]
Added a simple 5 input, 3 output neuron to class running package. Also removed the parameters for the command line that allows for main method tests in the MMD, MMR, and MMP files and the TWEANNcrossover main method test.
