### ISSUE TITLE
Sanity check for Tetris: Piece restrictions

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#220]
It's frustrating to watch the HyperNEAT Tetris agents do things that seem smart, only to mess up and make complete mistakes. Therefore, I have a sanity check in mind tat could also be useful for other purposes. For each type of piece in Tetris, make a boolean parameter that indicates whether or not that given piece is allowed. The parameters could have names like tetrisAllowLine, tetrisAllowZ, tetrisAllowSquare, etc.

Once this is in place, we can try a scenario where only line pieces are allowed. This should be trivially easy. Then, perhaps down the line, we might even try SZ Tetris, the difficult version discussed in that paper.

**Comment by Serenamidori** [comment]
Synced those changes, there are parameters for each piece that you can set to false to disallow them in a game. However, we still need to test it and use it for the sanity check itself.
