### ISSUE TITLE
Split holes and blocks in Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#221]
For HyperNEATTetris, have an option that splits the holes and the blocks across two separate input substrates. This should be a boolean parameter.

You will need to change the substrate list to have two separate input substrates, but you will also need to add some code to the RawTetrisStateExtractor to allow both the original input style and this new input style. Several changes are needed here:

numFeatures() would be twice as big.
extract would return an array twice as big. When sensing holes, make the index in result be (TetrisState.worldHeight \* TetrisState.worldWidth + i)
featureLabels() also needs to be fixed to have additional labels for whether each location is a hole.

**Comment by leg2015** [comment]
added the two input substrates to the hyperNEATTetris task but there are a few other places where I need to add stuff, just not sure where those spots are. Will hunt them down tomorrow

**Comment by leg2015** [comment]
Got it working. Running batch files with the feature on. Will close issue though because it is done
