### ISSUE TITLE
showCPPN

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#223]
Currently, when the network is shown in a post-eval from HyperNEAT, it shows the substrate network. However, it would be useful to see the CPPN as well. Add code to the call() method inside the EvaluationThread of the LonerTask. After the if (genotype instanceof TWEANNGenotype) check, have an additional check to see if the genotype is the HyperNEATCPPNGenotype, and if so make a separate display panel for the CPPN as well.

Control the display of the CPPN using an option showCPPN. This parameter should be false by default, but you should set this parameter to true in every batch file that does a post watch.

**Comment by leg2015** [comment]
Added a new parameter called showCPPN and the necessary code to get the CPPN to be visualized and it works! Also added the new parameter to all relevant post watch batch files
