### ISSUE TITLE
Stretched tanh function

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#224]
Add a new stretched version of tanh as described in this post: http://stackoverflow.com/questions/13632976/neural-network-with-tanh-wrong-saturation-with-normalized-data

Try using it as the ftype in HyperNEAT experiments.

Make sure it can be added or removed from the CPPN function set as well.

**Comment by leg2015** [comment]
Added a new parameter and activation function called stretchedTanh. Changed in all relevant places as well.
