### ISSUE TITLE
Mario Jump Problem

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#227]
I checked out how the jump button responds when playing it myself, and the amount of time that the jump button is held down definitely affects the height of the jump. However, we still need to address the problem of being stuck when holding jump forever. Add a static final JUMP_TIMEOUT value to the NNMario agent. 

The agent needs to have a counter for the number of time steps JUMP has been pressed in a row. Whenever jump is not pressed, reset the counter to 0. However, if the counter surpasses the JUMP_TIMEOUT, then the jump action is not performed, despite the NN wanting to do it. Also reset the counter in this case.

**Comment by Serenamidori** [comment]
We've added the check for this in the code that's set up by parameter, but not tested yet

**Comment by schrum2** [comment]
Was this resolved?

**Comment by Serenamidori** [comment]
Closing this for now- we have two timeouts and we only really use one of them. The Stuck Timeout makes sure that when mario is stuck, after a given time limit he will be expected to move again or it will end that game
