### ISSUE TITLE
JUnit tests for MMD

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#23]
This is Module Mutation Duplicate. This means that the newly created module should have behavior identical to the previously existing module. This can be tested with lots of random inputs. Each of the two modules should always have the same outputs, no matter what the inputs are. In fact, the main method of MMD has some code you can use for this purpose.

You can also have tests that look closely at the structure of the new network links.

**Comment by leg2015** [comment]
Commented and added JUnit testing to the MMD class
