### ISSUE TITLE
Mario: stuck timer killing Mario while he is still running?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#234]
Keep the completed results on the server and try to fix code. If you replace the jar file, you can run the post eval, but have extra output trying to explain what the problem is. If you find an error, you can also see if your changes fix the problem with an already evolved result.

**Comment by schrum2** [comment]
Was this resolved?

**Comment by Serenamidori** [comment]
No- haven't looked into it because this happened a little while ago. We need to replicate the error, because I'm not sure when/where it would have happened.

**Comment by Serenamidori** [comment]
Fixed it! :+1:
