### ISSUE TITLE
Identify dead neurons in VizDoom substrates

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#236]
There is a new substrate feature allowing dead neurons to be identified. Dead neurons are neurons (typically input or output neurons) that cannot affect the network's behavior. Therefore, it is a waste of time to define links leading into or out of them. Mario already has some of his D-pad neurons identified as dead ... these show up as grey in the substrate monitor. Identify the dead neurons in output substrates for VizDoom as well. This is done at the part of the code when the output substrates are created, which I believe is done in VizDoon with a special overridden method for each subtask.

**Comment by Serenamidori** [comment]
Done, but needs to be tested :+1:

**Comment by Serenamidori** [comment]
Fixed and tested, I added coordinates backwards for some tasks.
