### ISSUE TITLE
Get all JUnit tests in src running 

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#238]
Also, finish all tests that aren't finished and if there are tests that are empty, either make the test or get rid of it

**Comment by leg2015** [comment]
For hyperNEATGenotype test, it appears that for each test that runs, an extra 2 outputs get added to the CPPN each time which is quite odd. Not sure why this is happening or how to fix it...

**Comment by leg2015** [comment]
Also, if you run the substrateMLP on its own, it passes every time. However, when you run it with all other JUnit tests, the TWEANN and MLP no longer match, which is also very interesting

**Comment by leg2015** [comment]
The statisticsUtilities class is doing the exact same thing. It passes every time it is run separately, but when run with all other JUnit tests, the argmax tests no longer pass. Not sure what is going on but this warrants further investigation...

**Comment by schrum2** [comment]
For each tests, make sure that the setup clears all classes (there is a
method in MMNEAT for this) and also clears out the parameters. We may need
to explicitly destroy the original parameter instance and reinitialize it
from scratch ... I feel like some leftover, unchanged parameter is causing
the problem. For example, evolved HyperNEAT bias is now the default, which
is one way that extra outputs could be added to the network.

On Fri, Jul 1, 2016 at 9:46 AM, leg2015 notifications@github.com wrote:

> The statisticsUtilities class is doing the exact same thing. It passes
> every time it is run separately, but when run with all other JUnit tests,
> the argmax tests no longer pass. Not sure what is going on but this
> warrants further investigation...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/schrum2/MM-NEATv2/issues/238#issuecomment-229966012,
> or mute the thread
> https://github.com/notifications/unsubscribe/AIAhtK7CR_HyH4gyDb8AB5z04z7I1Q3uks5qRSg-gaJpZM4JDMAW
> .

## 

Jacob Schrum, Ph.D.
Assistant Professor of Computer Science
Department of Mathematics and Computer Science
Southwestern University
1001 E. University Ave.
Georgetown, TX 78626

Office: Mood-Bridwell Hall 141
Mail: SU Box 7341
Off-Campus Phone: (512) 863-1712
On-Campus Extension: x1712
E-mail: schrum2@southwestern.edu
WWW: http://southwestern.edu/~schrum2

**Comment by leg2015** [comment]
Need to make sure every JUnit test class has a tear down method that  clears the classes in MMNEAT. If that doesn't fix the problem with the junit tests, then will have to expore another path

**Comment by leg2015** [comment]
Got them finally working!
