### ISSUE TITLE
JUnit tests for MMP

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#24]
This is Module Mutation Previous. The unit tests need to assure that the structure of the network is what is expected, meaning that the new network module gets its inputs exclusively from the pre-existing module. The main method of MMP provides a way of checking this visually, but you need to do it algorithmically

**Comment by schrum2** [comment]
Reassigned this to Lauren since she already created a test class, though the test itself seems incomplete. Is this a duplicate issue?

**Comment by leg2015** [comment]
No, not a duplicate issue. I started working on creating a junit test a few days ago but forgot to reassign it to my self when I did

**Comment by leg2015** [comment]
Added some more tests to file. I'm not sure if I'm doing it correctly though so I won't close the issue

**Comment by schrum2** [comment]
For this test, perform MMP, and then check the network structure. You will
need to use the neuronsPerModule value. Basically, if you have an output
layer with the following neurons and innovation numbers:

(-1) (-2) (-3)

Then module mutation could lead to

(-1) (-2) (-3) (-4) (-5) (-6)

(Numbers not precise). The following links should exist

---

 |       ______|___
 |      |           |     |
(-1) (-2) (-3) (-4) (-5) (-6)

You can check for the existence of those links.

On Wed, May 18, 2016 at 10:32 AM, leg2015 notifications@github.com wrote:

> Added some more tests to file. I'm not sure if I'm doing it correctly
> though so I won't close the issue
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/schrum2/MM-NEATv2/issues/24#issuecomment-220064736

## 

Jacob Schrum, Ph.D.
Assistant Professor of Computer Science
Department of Mathematics and Computer Science
Southwestern University
1001 E. University Ave.
Georgetown, TX 78626

Office: Mood-Bridwell Hall 141
Mail: SU Box 7341
Off-Campus Phone: (512) 863-1712
On-Campus Extension: x1712
E-mail: schrum2@southwestern.edu
WWW: http://southwestern.edu/~schrum2

**Comment by leg2015** [comment]
Finally got MMP test up and running!
