### ISSUE TITLE
Most activated substrate output

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#240]
In some HyperNEAT domains, like Ms Pac-Man, it would be useful to identify the outputs in terms of relative rank rather than in terms of absolute activation. There should be a command-line parameter that handles this. In fact, I can see two different approaches:

Simple: Do the substrate coloring like usual, but color the most activated output neuron (that's not dead) green. It is important to ignore the dead neurons, since although they will have outputs of 0.0, it is possible that all live neurons have negative outputs.

Hard: Given all live outputs, sort them in terms of activation amount and color them accordingly with different shades of green (the green makes it clear we are not doing the typical activation interpretation.

I think it is worth doing both of these with different command line parameters. Do the simple approach first, and then we'll talk about the hard version if there is time.

**Comment by leg2015** [comment]
Got both done. There are now parameters that are associated with both and can work in tandem or separately.
