### ISSUE TITLE
Fix torusPredPreySensors so that agents don't sense themselves

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#241]

**Comment by schrum2** [comment]
This is an issues that you should try to address reasonably soon. After implementing it, you should also check to make sure it doesn't break any existing JUnit tests. In case you don't already have them, you should definitely have some tests that check for specific expected sensor values given a torus world state.

**Comment by Rollinsa** [comment]
Made it where pred/prey agents in the Torus Grid World do not sense themselves.

This actually ended up requiring a lot of changes. I also changed the JUnit tests to
accomodate the changes and tested everything (also with a trial of monitorInputs and
watch set to true) and everything seemed to work great, although all that was tested
was the preds with proximity pred sensors, and there are no JUnit tests to test the
prey, although I also did these not sensing self changes to them as well and checked it
multiple times and no existing tests are ruined, so hopefully it actually does work.
