### ISSUE TITLE
HyperNEAT weight visualization

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#246]
Add a way of visualizing the HyperNEAT substrate network's link weights geometrically. Specifically: for each layer with incoming links, have a grid where each cell represents one of the neurons with incoming links ... then, within that cell, sub-divide the cell to have the geometry of the incoming layer, so that the position in the cell is the source of the link, and the coloring of that position is the link weight.

**Comment by schrum2** [comment]
Distinguish the color of positive, negative, and missing/absent links.

**Comment by leg2015** [comment]
Added some methods to the TWEANN class to support the visualization for the weights. Made some headway but need some clarification on whether to start with the input or output nodes for first layer. Also will need some help traversing down the links and scaling the window correctly.

**Comment by schrum2** [comment]
There should be one visualization window for each set of links entering a layer. Essentially, you can go through the list of substrate From-To pairs and create a window for each To-layer. Divide that window to have one rectangle per neuron in the layer, and then each of those sub-rectangles is divided to contain one colored dot (perhaps 3 by 3 pixels? define a final constant) per incoming synaptic link in the layer below.

**Comment by schrum2** [comment]
I think I've resolved this with the latest commit. We'll do some more testing and then close this issue if everything seems to work

**Comment by schrum2** [comment]
Add spacing around each neuron group with width of 1 pixel. This is low priority however.
