### ISSUE TITLE
realTest in DeleteLinkMutationTest sometimes fails

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#248]
There is some randomness in the test that makes it work sometimes and fail at others.

**Comment by schrum2** [comment]
Specifically, this is a mutation operation that deletes an individual link in a NEAT network (TWEANN). This mutation operator generally isn't used, but could arguably be useful in some cases. I think the mutation operation works, but that the test fails because, like all mutation operations, there is some randomness involved. 

You will need to "catch" the error by running the test multiple times until it fails. You will need to add some debugging output to discern how it is failing. There are also some utilities that allow you to visualize a network ... these could be useful in troubleshooting the mutation operator as well.

In the end, the test should always succeed, and if there actually happens to be an error in the mutation operation itself, then it should definitely be fixed.

**Comment by alicequint** [comment]
not only does it sometimes succeed and fail, but occasionally the test will yield no result.
no-result (gray bar) is the only case where the text printed to the console is different, ending with 
"No links to choose from. All are frozen!"

**Comment by alicequint** [comment]
made it so that DeleteLinkMutation cannot 'delete' a link when there are none left
