### ISSUE TITLE
Write JUnit tests for RandomNumbers class

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#25]
Write tests for each method. Essentially, you need to confirm that all random numbers are in the appropriate range, and never outside of that range. Other tests may also be appropriate. See the main method of this class for examples.

**Comment by schrum2** [comment]
Avoid using assertFalse and assertTrue for this test class and others. assertEquals, assertNotEquals, and various other assert comments are all preferred.

**Comment by Serenamidori** [comment]
Just saw your newer comment, so the next time I focus on the tests again I'll go through and change the previous in addition to making more.

**Comment by Serenamidori** [comment]
Finished and sync'd!
