### ISSUE TITLE
Sense only some of the prey

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#250]
Something we might do soon is an experiment in which there are many prey (say 10) but the predator is only able to sense the nearest 2 or 3. This restriction will keep the number of sensors possessed by the predators reasonable. There would need to be a boolean command line parameter that specifies whether the sensors should be restricted in this way, and then an int parameter that specifies the number of prey to sense.

**Comment by Rollinsa** [comment]
Allowed pred/prey agents to sense only a specified number of agents. Made it where you can also say which agents can sense how many of which agents.

**Comment by Rollinsa** [comment]
The limiting sensors seems to not be working. At least the new batch file ("manyAgentsSenseTwo") does not work. The new batch file for an experiment with teammate sensors off also does not work. So I need to figure out why these two experiments do not work (the other 4 in the setup added in my last comment as a folder of batch files labeled 9/16 do work though), and fix them then restart the experiments

**Comment by Rollinsa** [comment]
861d966149fb6543c9e89a748e7902a95ca135b8
