### ISSUE TITLE
Randomize weights of seed networks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#256]
In the PopulationUtil class, in the initialPopulation method:

When seedExample is true, after copying the seed but before adding it to the list of parents, have an option (command line) that goes through the structure of the seed and completely randomizes the weights. Note that this method is so general that it operates on Genotypes ... this special option will require you to cast the genotypes to TWEANNGenotypes to cycle through and randomize the weights.

Use RandomNumbers.fullSmallRand() to define the new random weights.

After adding this command line option, set it to false by default, but set it to true in all HyperNEAT Seed Tetris experiments.

**Comment by leg2015** [comment]
added boolean parameter and set up necessary code in MMNEAT to support it. I am confused about which method is general enough to work on genotypes. Am I supposed to create a randomizeWeights method that's generalized or is there one that exists that I need to modify to have a special option for TWEANNGenotypes?

**Comment by schrum2** [comment]
We will assume that if the special parameter is used, then the user knows that some form of TWEANNGenotype is being used. This will allow you to cast the Genotype to a TWEANNGenotype and randomize the weights.

**Comment by leg2015** [comment]
added a weightRandomizationReplace mutation into the mutation.tweann package. I was not able to find the randomized link creation in the random tweann constructor, but have a rough method outlined.

**Comment by leg2015** [comment]
Checked the genotype files of a few networks with randomizeWeights on and the links are indeed a different weight so the weight randomization is working as hoped. I will close this issue for now.
