### ISSUE TITLE
Change ftype from Picbreeder interface

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#260]
ftype (for function type) determines the default activation function used to create new networks. Although this can be set from the command line, it would be useful if the Picbreeder interface allowed us to change this ... though it would only be useful when pressing the reset button. The idea is that the user could select a different ftype before clicking reset (or maybe clicking reset pops up a dialog that asks which ftype to use?).

**Comment by schrum2** [comment]
When reset is pressed, randomize the activation functions of all neurons of all networks in the new population by getting random activation function choices based on those that are checked as available in the Picbreeder interface. If only one option is checked, then that only option will be "randomly" picked repeatedly.

Implement this as a separate mutation operator that randomly changes all activation functions in a network.

**Comment by leg2015** [comment]
Added a new TWEANNMutation function that mutates the ftypes of the nodes to whatever functions checked currently. Works like a charm now.
