### ISSUE TITLE
Option to turn off each Picbreeder input

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#261]
In the Picbreeder interface, have check boxes for turning off each possible CPPN input. Turning the input off would mean that the input value is always 0, rather than whatever it would otherwise be. This should be applied the x, y, radius, and bias inputs.

The interface is starting to get cluttered ... you may want to make the space taken up by the images overall slightly smaller to accommodate more buttons. Or you could make the existing buttons at the top slightly smaller.

**Comment by schrum2** [comment]
I'm reassigning this to Darwin. Lauren already made the buttons at the top smaller, so that is finished (though their display could maybe be improved ... some compromise between Mac and Windows was required, since each one displays things differently).

However, the main issue here is still that, in order to fully explore the range of images that can be created, there should be a way of turning off certain CPPN inputs. Refer to the original Picbreeder paper for clarification on this, but the way images are drawn is using four CPPN inputs: x, y, distance from center, and a constant bias value of 1.

Add some checkboxes to the Picbreeder UI that are checked by default ... these checks allow each particular input to be used as normal. If a box is unchecked, then it should change the normal input to always be 0. This should result in all of the drawn images being refreshed, and should hopefully result in some interesting outcomes.

**Comment by DarwinJohnson** [comment]
The option to turn off each effect within Picbreeder has been fully added; checkboxes are used to control if the effect appears or not.
