### ISSUE TITLE
Add Rectified Linear Units as a type of activation function

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#262]
Specifically, add:
1) Rectified Linear Units
2) softplus
3) Leaky ReLU (using threshold of 0.01)

All of these are defined here: https://en.wikipedia.org/wiki/Rectifier_(neural_networks)

**Comment by leg2015** [comment]
I have added the new functions to the activation functions class. Just need to hook them into the picbreeder task now

**Comment by schrum2** [comment]
When you added these, did you forget to add entries to Parameters.java? I just tried messing with the code, and it is complaining about these parameters not being present. I just wanted to make sure you didn't have a pending commit that solved this. Since it should be a small/quick fix, please address soon so I can fiddle with some other issues.

**Comment by leg2015** [comment]
Sorry, I totally forgot to commit the changes I made from before Thanksgiving. It all should work now but I'll run a few tests to make sure before closing the issue

**Comment by leg2015** [comment]
I added JUnit testing for the activation functions and they're working just fine. Also forgot to make the activation function methods public so changed that as well. Should work as normal now.
