### ISSUE TITLE
Small error in package declarations of populationUtil

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#267]
The import of edu.utexas.cs.nn.evolution.mutation.tweann.ActivationFunctionRandomReplacement claims that it can't resolve the package. Not sure why it's not resolving because said package still exists and not sure how to fix it

**Comment by schrum2** [comment]
This is probably an issue with your GitHub sync or, more likely, with Eclipse. Sometimes you have to make Eclipse refresh its code to reflect what is actually stored on the disk. I'm not seeing any problems in my version of the code.
