### ISSUE TITLE
Comment LimitedSinglePopulationGenerationalEAExperiment

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#269]
Find the LimitedSinglePopulationGenerationalEAExperiment and add appropriate Javadoc style header comments to each method, including @param and @return tags

For the LimitedSinglePopulationGenerationalEAExperiment() constructor, say:
Creates a default instance based on parameters loaded from the commandline

For the other LimitedSinglePopulationGenerationalEAExperiment constructor:
Creates experiment instance with specified parameters.
(then describe the parameters)
ea is an evolutionary algorithm that works on a single population
example is a template for the initial genotype of the population
maxGenerations is the number of generations of evolution
lastSavedDir last directory to which genotypes were saved, if saving occurred (null or "" otherwise)

For the shouldStop method:
Indicates that the experiment should stop once the maxGenerations have been reached

**Comment by twerisa** [comment]
Took care of issue; commented all method headers.
