### ISSUE TITLE
CPPNs for HyperNEAT

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#27]
A CPPNGenotype class should be made that extends the TWEANNGenotype. The getPhenotype() method should query a substrate to generate a TWEANN. However, this requires some sort of definition for substrates.

**Comment by leg2015** [comment]
a very (very) rough implementation of this has been created. Still needs a lot of work but this specific task is complete so I'm going to go ahead and close this as more specific tasks to refine hyperNEAT should be created
