### ISSUE TITLE
Comment RealBehaviorVector

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#270]
Find the RealBehaviorVector class and provide full Javadoc header comments for each method, including @param and @return tags

First, remove the part at the top that starts: "To change this template ..."

The class comment should say:
Characterization of agent behavior consisting of a fixed-length number of real (double) values. For use with the Behavioral Diversity approach.

The RealBehaviorVector(ArrayList<Double> v) constructor:
Simply creates a behavior vector out of a provided array list

The RealBehaviorVector(int[] i) constructor:
Takes the provided array values and places them in the array list of the behavior vector.

The RealBehaviorVector(double[] d) constructor:
Takes the provided array values and places them in the array list of the behavior vector.

For the distance method:
Calculates the Euclidean distance between this behavior and the provided behavior vector. The shorter of the two vectors is padded with zeros first if necessary. The resulting return value is the distance between the two vectors in behavior space.

**Comment by DarwinJohnson** [comment]
Appropriate comments have been added to the RealBehaviorVector class, as assigned.
