### ISSUE TITLE
Comment and JUnit tests for BooleanUtil

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#272]
Find the class BooleanUtil. It needs a comment at the top describing its general contents. Also, you should create a JUnit test file that thoroughly tests its two methods. Comment the tests to explain the rational behind them as well.

**Comment by DarwinJohnson** [comment]
The Class Comment has been added, and the JUnit Test Cases have been created and run. Test comments have been included. The methods are working correctly.
