### ISSUE TITLE
Better comments and tests for CartesianGeometricUtilities

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#273]
CartesianGeometricUtilities is mostly well-commented, but there are some methods that are lacking either header and/or body comments. Provide these. Additionally, although CartesianGeometricUtilitiesTest exists, it does not test all methods of CartesianGeometricUtilities, and the tests it does provide could be made more thorough. Provide more/better tests, and explain them (as well as the existing tests) with helpful comments.

**Comment by twerisa** [comment]
This issue has been addressed: comments were added to utility methods, and additional tests/comments were provided in the JUnit tests to account for methods that were not tested and special cases.
