### ISSUE TITLE
Comments and JUnit tests for Box2D

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#277]
The Box2D class represents a rectangle. The main point of it is to help determine whether a particular location is inside of the box.

This class needs to be commented (proper header comments especially with param and return tags specified), and it also needs to have an associated JUnit test file created.

**Comment by DarwinJohnson** [comment]
Header and Body comments have been added where necessary, and a JUnit Test Case has been created and filled. Code appears to be working properly, but additional tests will be added to check edge cases.

**Comment by DarwinJohnson** [comment]
Added more JUnit Test Cases to ensure the code was working properly. Everything appears to be functioning well.
