### ISSUE TITLE
Fix ExtendedBertsekasTsitsiklisTetrisExtractorTests: number_of_holes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#280]
The ExtendedBertsekasTsitsiklisTetrisExtractorTests is a feature extractor for Tetris. This means that it looks at a Tetris game state and reduces it to an array of numerical values. This JUnit test is supposed to verify correct functioning of the extractor. I'm pretty sure that the extractor works, but that the test is broken (though wouldn't it be interesting to find otherwise!). Fix the test, and the corresponding code if necessary.

**Comment by alicequint** [comment]
probably actually unrelated to #282, which seems to have been a problem only on one machine

**Comment by DarwinJohnson** [comment]
The Parameter loading error at the SetUp() portion of the JUnit Test has been fixed. It appears that this was the reason why the number_of_holes test was failing. Now the test passes successfully.
