### ISSUE TITLE
HyperNEATCPPNGenotypeTest improvements

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#283]
I'm a bit skeptical that all of the tests in HyperNEATCPPNGenotypeTest make sense, and I know for certain that it does not thoroughly test some new changes to the HyperNEATCPPNGenotype class. First, there need to be tests assuring that CPPNs have the correct numbers of input and output neurons under various configurations of parameters settings (substrateMapping, evolveHyperNEATBias, leo, different HyperNEAT tasks). Some tests exist to check these, but they should be strongly scrutinized. The tests currently pass, but I think use of the HyperNEATDummyTask might be too simplistic.

**Comment by schrum2** [comment]
This is a pretty challenging task because you need to understand what HyperNEAT is before you can start on it. You will need to read some papers first. Start by going to the HyperNEAT users page:
http://eplex.cs.ucf.edu/hyperNEATpage/
Scroll down to the "HyperNEAT Publications from EPlex" and read 
(2) A Hypercube-Based Encoding for Evolving Large-Scale Neural Networks
I also recommend reading the paper that Lauren wrote with me on applying HyperNEAT to Tetris:
http://people.southwestern.edu/~schrum2/SCOPE/gillespie.gecco17.pdf

Once you have read these papers, you can work on this task together, but you will probably need to ask me many questions as well.

**Comment by schrum2** [comment]
Provide an update on this, describing actions taken or not taken, and why. Specifically, I know that there are some "tests" for which a formal automated testing procedure does not make sense. Describe them here.

**Comment by twerisa** [comment]
We decided that tests could be improved, but are very muddled at the moment, so it's best to work on other things especially since it's clear that HyperNEATCPPNGenotype works.
