### ISSUE TITLE
HyperNEATUtil comments and tests

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#284]
The HyperNEATUtil class also needs some more comments and improved testing.

**Comment by schrum2** [comment]
This is a pretty challenging task because you need to understand what HyperNEAT is before you can start on it. You will need to read some papers first. Start by going to the HyperNEAT users page:
http://eplex.cs.ucf.edu/hyperNEATpage/
Scroll down to the "HyperNEAT Publications from EPlex" and read 
(2) A Hypercube-Based Encoding for Evolving Large-Scale Neural Networks
I also recommend reading the paper that Lauren wrote with me on applying HyperNEAT to Tetris:
http://people.southwestern.edu/~schrum2/SCOPE/gillespie.gecco17.pdf

This task is also related to #283

**Comment by schrum2** [comment]
Do you think this issue is complete? Describe outstanding issues here if there are any, otherwise close the issue.

**Comment by alicequint** [comment]
HyperNEATUtilTest (my half) has been finished, although its worth noting that several of the tests here are are for methods whose only function is displaying graphical information, and so the tests just call the method without the possibility of failure.

looking at HyperNEATUtil, @DarwinJohnson  's half, it seems thoroughly commented, so I'm closing this issue. _*confetti*_
