### ISSUE TITLE
Integrate microRTS

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#286]
This is a simplified real-time strategy game: https://sites.google.com/site/micrortsaicompetition/home

This should be much easier to work with than Starcraft (#285), so maybe consider doing this first/instead.

**Comment by alicequint** [comment]
package 'ai.evaluation' contains an abstract class EvaluationFunction, as well as a few hard coded classes derived from it that determine how preferable a GameState is. 
We can eventually put something like 'EvolveNeuralNetwork" here.

**Comment by schrum2** [comment]
The next time you work on this issue, go ahead and copy all of the code from the microRTS project into the MM-NEAT project. Just copy all of the code over, and then do a commit and sync to get all of the files in our system. Then we'll talk about integrating the rts code with the MM-NEAT code

**Comment by schrum2** [comment]
Now you need to find out how to launch a given configuration without the visual display ... a feature that I certainly hope exists. I should be surprised if it did not.

**Comment by alicequint** [comment]
Micro.tests.RunConfigurableExpirements seems to be the file that we're looking for, although it seems rough or unfinished (there is some dead code)

**Comment by schrum2** [comment]
Rather than try to use micro.tests.RunConfigurableExpirements, you should try copying the code from micro.tests.GameVisualSimulationTest to a new class.

Make a class 
MicroRTSTask that extends NoisyLonerTask<T extends Network> extends NoisyLonerTask<T> implements NetworkTask, HyperNEATTask
This should go in a new package: edu.utexas.cs.nn.tasks.microrts

The oneEval method should basically run the code in the main method of GameVisualSimulationTest, but with several changes.

The edu.utexas.cs.nn.tasks.microrts package also needs an 
NNMicroRTSOrganism<T extends Network> extends Organism<T>
and an
NNMicroRTSAgent<T extends Network> extends AIWithComputationBudget

**Comment by schrum2** [comment]
The microRTS task seems to be able to evolve. We still need to put a lot of work into improving it, but I'm going to close this issue. Future issues should be more specific when relating to this domain.
