### ISSUE TITLE
Integrate General Video Game AI Competition code

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#287]
The website is here: http://www.gvgai.net/

We would be interested in the learning track.

The actual code is here: http://www.gvgai.net/software.php

**Comment by schrum2** [comment]
I think that this code is designed to be pretty easy to get up and running. It is meant to be highly accessible Java code. Anyone who takes on this task should run the code first in its own project, and then try integrating it into MM-NEAT afterward.

**Comment by schrum2** [comment]
Games can be played now.

The next step is to make a package: edu.utexas.cs.nn.tasks.gvgai and put several classes in it.
An NNGamePlayer that extends AbstractPlayer
A GVGAITask that loads a game and plays it with the NNGamePlayer

Many commandline parameters specifying the game to be played, etc. will likely be needed.

Recall that details on the competition are here: http://www.gvgai.net/
Our focus would be the Learning track, but  we could also try the Level Generation track ... the interactive evolution code used by @twerisa could be used with CPPNs to create brand new levels. If we decide to go that route, then it should be a separate GitHub issue.

This particular GitHub issue can be closed once it is possible to evolve an agent for single player games. 
A list of several GVG-AI papers is here: http://www.gvgai.net/papers.php
Although I have not read it yet, the following paper looks particularly promising:
http://www.diego-perez.net/papers/NeuroevolutionGVG.pdf

**Comment by DarwinJohnson** [comment]
Check out the createController method in the ArcadeMachine class in the GVGAI code.

**Comment by DarwinJohnson** [comment]
The GVGAI code is now integrated into the MMNEAT code; it's possible to run a GVGAI game as a Task using an agent with a Genotype-based Network. As of now, Post Evals do not work visually, but this error will soon be fixed with Issue #442. With the functionality we have now, this Issue can be closed.
