### ISSUE TITLE
Generate sensor inputs for substrate

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#29]
There needs to be some kind of correlation between substrate configurations and input sensors. The extra complication arising from this is that it needs to be done in the context of a specific domain. Once we figure out which domain to apply HyperNEAT to first, this issue can be properly addressed.

**Comment by leg2015** [comment]
this issue is completed in terms of the pred/prey torus domain

**Comment by schrum2** [comment]
I think that we've completed the general framework for this, so I'm going to close this issue, but leave the two domain-specific issues open
