### ISSUE TITLE
VizDoom comments and test-drive, and maybe fix

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#293]
I was fiddling with the VizDoom code we developed last year, but it wasn't working properly. I'm hoping this is just some compatibility issue with Windows 10, but we'll find out when we run the code on the lab machines.

Regardless, the code in the edu.utexas.cs.nn.tasks.vizdoom package needs comments. Start with VizDoomTask, which is inherited by most of the other classes. 

I also added a new batch file in commit 42d5df7b4109b2b97add9df6dd3fe640d7883622 that you should be able to use to evolve agents with the visualization on. However, this is the code that didn't work for me ... the Doom window froze. Test this out and see if it works ... if not, then we need to figure out how to fix it.

Something else you might try just to gain some familiarity with the code is to run any Task class that has a main method ... some of these, like VizDoomBasicShootTask, actually did work for me. It shows an example eval with a new neural network.

**Comment by schrum2** [comment]
The row-based input scheme seems to work fine. It seems that the problem that was caused with the other approach was an out of memory error, which makes sense given the size of the network, but I thought that it worked before. Maybe tweaking the parameters to deal with smaller networks will allow for some progress with the other approaches.

**Comment by schrum2** [comment]
Running the VizDoomDefendCenterTask class (right-click and run as a Java application) also works, and shows off how inputs are extracted. A narrow region of the visible area is focused on and shown as black/white activation values.

I also added another batch file that will let you visualize the input space in this commit: 747f60ef631bc1d1abc17a8050618acfdf5ff17e

While going through and commenting the VizDoom classes, also check ALL of the batch files. Track a record here in this GitHub issue of which ones work, which ones don't, and why (explain what happens ... crash or freeze, but be sure to give enough time to load).

My current impression is that the HyperNEAT batch files are the ones having problems, but check everything to see what happens.

Also, for any batch file that successfully runs, be sure to do a postBestObjectiveWatch after running it for a few generations to see if the visualization works.

**Comment by schrum2** [comment]
Good job on the testing. I'm making some changes to the batch files myself now. Mostly, I'm reducing population sizes to see if a single generation can actually complete in a reasonable time.

I would like you to take the VizDoom subdir in the batch directory and replace it with several subdirs organized by task. For example, VizDoom-Basic, etc.

I will be deleting batch files for some tasks entirely (it looks like certain tasks never fully worked), but for those that still have at least one representative, I would like you to make sure that each possible evaluation approach is considered: Control, Row, HyperNEAT, Smudge, and HNSmudge. You have a bit of freedom in deciding the details on how this works, and we should probably talk about what exactly smudge, row, etc. are doing.

However, since you need to comment all of these tasks anyway, you will hopefully get some idea of what is going on from looking at the code.

**Comment by schrum2** [comment]
I've been looking at your report, but some of the conclusions are invalid because of errors in the batch files. Whenever you launch an experiment, it checks to see if the designated save directory already exists, and resumes from that point. This also means that saved parameter values get used instead of what is specified in the batch file. 

The reason there is a problem is that some of the batch files were saving to the wrong locations. In particular, many of them were saving to the same directory as other batch files. The consequence of this is that whichever batch file you ran second would have been loading incorrectly.

I have fixed some of these issues: 89f43ffafea32cc6d2f2398ebb563198c5299dab 1723654db650306e0a130a3f27ece8b4c1ea26c6 5fb8f9939772c7abf2386ccad655d5474f2f28c2 dc1e1bfd82619f20d24e3e54e5eb408c3d641b78

I have also edited your Google Drive file, putting an X next to files that I have checked myself. I also added some commentary. The others may need to be fixed and re-assessed ... keep this in mind when moving the batch files into subdirectories as explained above.

**Comment by schrum2** [comment]
This issue is close to being done. Simply do the following things:

"I would like you to take the VizDoom subdir in the batch directory and replace it with several subdirs organized by task. For example, VizDoom-Basic, etc."

Also, make sure that the log and saveTo directories of ALL batch files match the batch file names.

Once you do this, close the issue.

**Comment by DarwinJohnson** [comment]
The VizDoom subdir has been broken up into several subdirs organized by Task. The Batch Files all have the correct log and saveTo directories. Everything is organized now.
