### ISSUE TITLE
Organize Picbreeder interface

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#295]
The new Picbreeder features are great, but they really don't fit on the screen. The four checkboxes that turn input signals on and off should be moved up so that they are immediately to the right of the mutation slider bar. Hopefully, this will leave enough room for all parts of the interface.

**Comment by DarwinJohnson** [comment]
Moved the Effect CheckBoxes. Will change the Action Buttons at the top to have the full image shown.

**Comment by DarwinJohnson** [comment]
The Action Buttons are now scaled with their proper images still showing. There is two Global Final Int Variables at the top of the Class used to change the Width and Height of the Action Buttons, if further change is desired.
