### ISSUE TITLE
Sound from CPPN

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#299]
Although this is a new issue, the code for this can go inside of SoundUtil.

Basically, we want a static method that takes a Network parameter (which should generally be a CPPN) and generates an array of amplitude values, which are then played as a sound (this might actually be two distinct methods).

The CPPN will only have one output: the amplitude.  What is unclear is what the input(s) should be, so some experimentation is needed. At the very least, we need a constant bias input of 1.0, and a time input. It might also make sense to include a sine of t (or sin(2*pi*f*t)?) input, as was done in the breedesizer paper.

After this, you can also consider remixing an existing sound. Give a sound file to a method, extract the double array of amplitudes, and use the amplitudes of the file at time t as one of the inputs to the CPPN to get a new sound result.

**Comment by twerisa** [comment]
CPPN method is functional and has been moved over to SoundAmplitudeArrayManipulator.java
