### ISSUE TITLE
Comment edu.utexas.cs.nn.tasks.gridTorus

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#3]
Comment code in this package

**Comment by schrum2** [comment]
In particular, every method needs a comment, and every class needs a comment at the top.

**Comment by Serenamidori** [comment]
Commented the code in the package, but I may have forgotten some comments at the tops

**Comment by schrum2** [comment]
Please add comments at the tops of classes, methods and constructors, and
also describe the parameter lists. Here are some additional comments about
your comments so you can remove the questions and write comments with
certainty:

NNTorusPredPreyAgent can represent either a predator or a prey. It is fully
general. However, there is currently no support for evolving the predators.
getController is a general method that returns an agent's brain (neural
network).
getAction determines the action for agent me, but it needs the complete
list of all agents of each type in order to make an informed decision.
sensorLabels: There is a network visualization option that shows you the
input values during evaluation. The labels help you know what each sensor
does.
TorusPredPreyTask: the super() is for NoisyLonerTask, because it is the
extended task. "implements" is for interfaces, which don't have
constructors.
npcs is for Non-Player Characters ... however, this naming convention isn't
great. You could use the Refactor/Rename option to call this something
better.
CommonConstants is used in conjunction with Parameters to store parameter
values that are frequently used, but rarely change.
startingGoals are used by TUG ... don't worry about it too much for now.
minScores are also used by TUG.

On Wed, May 11, 2016 at 9:22 AM, Gab notifications@github.com wrote:

> Commented the code in the package, but I may have forgotten some comments
> at the tops
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/schrum2/MM-NEATv2/issues/3#issuecomment-218474545

## 

Jacob Schrum, Ph.D.
Assistant Professor of Computer Science
Department of Mathematics and Computer Science
Southwestern University
1001 E. University Ave.
Georgetown, TX 78626

Office: Mood-Bridwell Hall 141
Mail: SU Box 7341
Off-Campus Phone: (512) 863-1712
On-Campus Extension: x1712
E-mail: schrum2@southwestern.edu
WWW: http://southwestern.edu/~schrum2
