### ISSUE TITLE
Comments and JUnit testing for ArrayUtil

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#30]
This class is already fairly well commented, but could use more. Also, the individual methods should be properly unit tested. The class is in the edu.utexas.cs.nn.util.datastructures package

**Comment by schrum2** [comment]
Take a break from the pred/prey domain at some point to tackle this issue

**Comment by schrum2** [comment]
Accidentally duplicated this issue as #88. Should have just reassigned. Instead of taking a break from pred/prey, it will be taking a break from Tetris. Still, this is lower priority.

**Comment by Serenamidori** [comment]
Started this, will work on when I get stuck on harder issues or I have no current tasks

**Comment by Serenamidori** [comment]
Done, all tests have been committed
