### ISSUE TITLE
"stepByStep" for Pinball

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#301]
Search the code to see how the "stepByStep" parameter is used, and then add support for this parameter to the Pinball domain when being visualized. I would like to see how a successful agent performs at a speed I can understand.

Once this is working, you can use the postAllBestObjectiveWatchStepByStep.bat file to see how a successfully evolved champion PInball agent performs (let me see too).

**Comment by DarwinJohnson** [comment]
postAllBestObjectiveWatchStepByStep.bat works well with both Pinball-Hard and Pinball-Simple. Discovered that the "solution" of doing nothing has developed. Will fix by creating a Multi-Objective version of Pinball Batch files. Otherwise, the stepByStep and postAllBestObjective functions work.
