### ISSUE TITLE
create maps folder for microRTS #286 inside MMNEAT

### ISSUE THREAD

**Issue by alicequint** [schrum2/MM-NEATv2#302]
create directory MMNEAT/data/maps/(all the things) instead of MMNEAT/maps

**Comment by alicequint** [comment]
#286

**Comment by schrum2** [comment]
Although you may have moved the folders into the appropriate directory, the files themselves do not seem to have committed to GitHub. New directories are generally not detected and added to the project unless they are in the src directory, so a special command in the GitHub shell is required to actually add the directory to the project. Get my help with.
