### ISSUE TITLE
Pinball fitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#303]
For the Pinball task, there should be a boolean Parameter called "moPinball" (for multiobjective pinball). If this parameter is set to true, then you should register an additional fitness function called "Distance From Goal" and compute this number to return from oneEval (one more element of the first array in the Pair you return). This value should be the negative distance from the goal location. A computation of this might already exist in the Pinball classes. However, all you really need to do is extract the ball location (this is already a sensor input) and the goal location (not sure how to get this) and use one of my pre-existing Util methods to compute the distance (see how Tuple2D computes distance)

**Comment by DarwinJohnson** [comment]
Created a moPinball boolean in the Parameters class and tried to implement the Multi-Objective evaluation based on MO Mario. Found a way to calculate the distance to the goal using the Pinball Point class, and used that as another Objective, labelled as "Distance." Commit 91b7dec referenced #126, but applies to this Issue as well.

**Comment by schrum2** [comment]
Is this done? Close it if it is

**Comment by DarwinJohnson** [comment]
The only thing left for MO Pinball is to apply Behavioral Diversity, as described by Issue #308. This issue is done.
