### ISSUE TITLE
Fitness Function for MicroRTS

### ISSUE THREAD

**Issue by alicequint** [schrum2/MM-NEATv2#304]
fitness function (different from evaluation function!
(make oneEval method better in class MicroRTSTask)
Gradient : way to go from bad to good

**Comment by alicequint** [comment]
may have to track information from during the game

**Comment by alicequint** [comment]
as is, the fitnessFunction seems to be in a pretty good place, i don't see myself changing it any time soon.

**Comment by schrum2** [comment]
This issue is done, but #328 deals with creating new fitness functions.
