### ISSUE TITLE
Design agent with Game Tree Search using NN

### ISSUE THREAD

**Issue by alicequint** [schrum2/MM-NEATv2#305]
in the same package as MicroRTSTask, give it an evaluation function to call for determining the fitness of organisms.

**Comment by alicequint** [comment]
extend evaluation class thats already defined in micro, 
using a pre-evolved agent

**Comment by schrum2** [comment]
Be sure to assign yourself to the microRTS issues you create

**Comment by schrum2** [comment]
I think that an agent that uses minimax search for planning already exists in the collection of agents that come with the microRTS code. The trick to making it work is to define an EvaluationFunction using an NN, and simply use the existing minimax agent.

**Comment by alicequint** [comment]
actually still need to do normalization!!!! NNEvaluationFunction is not quite there yet!

**Comment by schrum2** [comment]
I think that so far you have tested your evaluation function with some variant of a UCT agent (correct me if I'm wrong).

Please track all pre-packaged agents from the microRTS code that you have successfully tested your evaluation function with (try all that you can find).

**Comment by alicequint** [comment]
When running the batch file , the first eval goes okay, but subsequent evaluations cause strange problems + dont really happen. something isnt being fully reset in MicroRTSTask

**Comment by schrum2** [comment]
I have a theory as to why the agent seems to take no actions. All agents in the game say something about having a computation budget. This means they have a limited time to make a decision, and return the best decision they could think of within the time limit. This means that they are storing their best action so far in some why. However, I think that in the MicroRTSTask we may have disabled the pausing of fixed duration between moves (compare the oneEval method with whatever code it was originally copied from). This would mean that the agent has no time to find a worthwhile move, and thus always does the default of nothing.

This is just a theory ... I haven't looked at the code, but keep it in mind. You may need to add some pauses back.

**Comment by alicequint** [comment]
we've been able to conduct several successful tests using the agents already in microrts with evaluation functions that use NNs, so i'm going to close this issue
