### ISSUE TITLE
Our own variant of breedesizer

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#306]
Now we have a way of generating sounds from a CPPN. Let's copy and improve upon breedesizer: http://bthj.is/breedesizer/ In doing so, let's try to understand the differences between what we have an what they have (why do we need such long dense waves vs the simple ones in breedesizer? What is the FFT actually doing?).

However, simply getting something cool to work is really what matters the most.

You will want to make an interface just like Picbreeder's except the images on the buttons will be the sound wave plots (you may need to design better/additional plotting functions in GraphicsUtil in order to accomplish this). In Picbreeder, clicking an image means you are selecting/deselecting it for breeding. In breedesizer, clicking the image should also play the sound (with some frequency).

Eventually, though not at first, we should also have a keyboard interface that generates the sounds with different frequencies, like in breedesizer.

**Comment by schrum2** [comment]
By the way, when doing this, it will be important to generalize the code from Picbreeder. Rather than simply copy it, you will need to extract out the functionality common to both, so that Picbreeder and breedesizer are just slight variants of a general class.

Specifically, I think that you will need to make an InteractiveEvolutionTask, and have both PicbreederTask and your new BrredesizerTask extend the InteractiveEvolutionTask. Functionality common to both tasks (the applet layout, selecting which individuals survive each generation, certain buttons and check boxes) will be in InteractiveEvolutionTask, and then Picbreeder and Breedesizer will simply override certain methods so that they can each be slightly different.

**Comment by twerisa** [comment]
Last part of this issue (creating a keyboard interface) has been moved over to a new issue (#312).
