### ISSUE TITLE
Make MicroRTSTask able to switch between Watch and no-watch modes?

### ISSUE THREAD

**Issue by alicequint** [schrum2/MM-NEATv2#307]
other classes have the ability to be run with Watch (global variable?) set to true,
i think this would be useful for testing the use of evaluation functions, because we could look at the individual steps that the individuals are taking.

**Comment by alicequint** [comment]
#305

**Comment by schrum2** [comment]
Is this done? I feel like we were on the verge of finishing it

**Comment by alicequint** [comment]
yes! it is done
