### ISSUE TITLE
Apply Behavioral Diversity to Pinball

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#308]
Behavioral Diversity is a way of searching the behavior space when fitness stagnates in a deceptive domain. I've used it before in this paper: https://suscholar.southwestern.edu/handle/11214/150

There is a more thorough and focused paper by the original inventor at this URL:
https://pdfs.semanticscholar.org/3d59/d453eaa1b59c4533f0deb01ea7b03c6edd29.pdf

Implementing it in my existing code is fairly straightforward. 

In the PinballTask, you need to override the getBehaviorVector() method. It currently returns null.

A sensible way of characterizing the behavior is the final position that the ball ends up at when the evaluation ends. However, since this is a noisy domain, the agent gets evaluated multiple times. We should save and return all end locations. Here is how we can do it.

Make the list of final coordinates a global variable. Then override the prep() method. Whenever this is called, set the list of coordinates to be empty (use an ArrayList of Doubles). In oneEval, add the x and y coordinates to this list after each evaluation. For the sake of tidiness, override the task's cleanup() method as well to set this ArrayList to null.

After changing the code, you will need to make a batch file that launches the evaluation using BDNSGA2 as the "ea" parameter, and DomainSpecificCharacterization as the "behaviorCharacterization" (this actually seems to be the default). I have not done this in a long time, and I can't seem to find any example batch files to build off of, but there may be other settings you need.

**Comment by DarwinJohnson** [comment]
The Pinball-MOBDHard Batch File runs perfectly, and running it shows that the Ball now travels all the way to the Target without getting stuck on the Obstacles. The Behavioral Diversity works perfectly.
