### ISSUE TITLE
One Step Evaluater for Board Games

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#313]
This is an easier task that #309 and should be attempted first. Define a general BoardGamePlayer that works as follows. Its constructor take something of type T where T extends Network is true. Whenever you want the player to make a move, it uses the method that gets all possible next states. Then, it gets the state description for each of those states (array of numbers) and treats those as inputs to its neural network. Use the neural network's process method on each set of state inputs to get an output for each state. The agent should pick the state that resulted in the highest network output.

**Comment by schrum2** [comment]
Is this done? I guess that once we are sure it works with at least one more game, we can safely close it.

**Comment by DarwinJohnson** [comment]
If we test this with one more game, then this issue can be closed.

**Comment by DarwinJohnson** [comment]
OneStepEval works with Othello. It appears to be working.

**Comment by schrum2** [comment]
I re-opened this. Before starting on #309 you should generalize the OneStepEval player to use a proper HeuristicFunction. The BoardGameHeuristic interface should simply have a single method that takes a T that extends BoardGameState and returns a double. One example of such a heuristic function would be an NNBoardGameHeuristic that takes a T that extends Network on construction, and uses it to compute a utility value from the game state.

Once the OneStepEval is generalized to potentially use any heuristic, you can proceed to implement the minimax player ( #309 ) in the same way.

**Comment by schrum2** [comment]
I think this is done.
