### ISSUE TITLE
General random board game player

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#314]
Replace your RandomTicTacToe and RPS players with a single class called RandomBoardGamePlayer. The takeAction method of this class simply uses the BoardGameState to randomly select one of the next possible states.

Looking more closely at this, I now realize that the possibleBoardGameStates method in the BoardGame interface should actually be moved into the BoardGameState interface in order to accomplish this task (and probably #309 and #313  as well)

**Comment by DarwinJohnson** [comment]
The current General Random BoardGamePlayer should function with any game, so long as the possibleBoardGameStates method works in each specific BoardGameState.
