### ISSUE TITLE
Fitness functions for board games

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#315]
A board game typically has a clear outcome: win or lose. Some games have scores, but a lot of the classics (Tic Tac Toe, Chess, etc.) do not. Therefore, how can you tell if you are getting better?

Some approaches come to mind. For example, if you are playing against a skilled scripted player, but could force it to make random moves some percentage of the time, and play multiple games against it. Your fitness would be the number of times you win, and as you get better, you could decrease the randomness.

Of course, if you already have a good scripted player, then why would you need to evolve one? Instead, you could coevolve agents to play the game against themselves.

There are many more approaches, but it is not an easy issue. You should spend some time searching the literature and saving research articles you find in a sub-directory of our shared Google Drive Artifacts. You should also maintain a document in that directory that briefly summarizes the approach used in each paper.

A good initial paper to put there would be the HyperNEAT Checkers paper.

**Comment by schrum2** [comment]
When you do the literature search for this, you should come across plenty of GGP papers #351 . Be sure to pay attention to General Game Playing when searching the literature.

You will find lots of work that does NOT use evolution, but these papers are still important. Save the papers you find in the Google Drive and catalog useful reference information about them.

**Comment by schrum2** [comment]
Issue #357 is an example fitness function that is an offshoot from this issue. I want you to take what you have learned from your literature search and mention/propose a few more possible fitness functions here, be they general of game-specific. I'll peruse them and direct you toward some options that seem within reach and useful to implement.

**Comment by schrum2** [comment]
Here are some Othello papers you should add:
http://www.wfg.csse.uwa.edu.au/publications/WFG2007g.pdf
http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=10AB4B0966FEE51BE133255498065C42?doi=10.1.1.580.8400&rep=rep1&type=pdf
http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6762937

**Comment by DarwinJohnson** [comment]
The Othello Papers have been added.

**Comment by schrum2** [comment]
This general task has led to some specific issues already, and we will simply create more as needed. However, this high-level general issue can be closed now.
