### ISSUE TITLE
Evolved Animations?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#319]
Evolving 2D images (picbreeder) and 3D shapes (endless forms) have been done. It's cool to recreate these systems, but they are still not original. Even our work evolving sounds, though different in the details, is based on pre-existing work.

However, I don't think anyone has evolved animations before, and I feel that it should be fairly easy to do. You just need to give a CPPN that produces images an extra input for time, and then you can query several images across a timeline. 

I'm guessing that the results would be trippy, undulating images, like this:
https://giphy.com/gifs/trippy-weed-psychedelic-SYrMAmJZT4YcU
But who knows? We won't know unless we try.

Although creating the individual images should be easy, some work needs to be done to figure out how to smoothly animate them.  A quick search has pointed me to this tutorial on an animation applet (http://docs.oracle.com/javase/tutorial/uiswing/components/applet.html), and this tutorial on creating animated gifs (http://stackoverflow.com/questions/16649620/is-there-a-way-to-create-one-gif-image-from-multiple-images-in-java), though I have no idea if they will help.

**Comment by twerisa** [comment]
Have a separate class that I think should be able to create an animation from a set of images. However, the parameters for the applet have to be initialized. Some of the resources I've read about applet parameters say that a separate web page has to be create that specifies the parameters, and then the applet has to be launched in that webpage. I need to look at applet parameter specifications, because I think creating a webpage probably isn't the way to go.

**Comment by schrum2** [comment]
Java Applets always have the option of being run inside of a webpage, but
it is a bit tricky and unnecessary. Don't try to involve a webpage.

**Comment by schrum2** [comment]
You can start on the AnimationBreeder class now. In order to show the animations to the user, I think the best way to set it up is to have the button animate when the mouse hovers over the button. onMouseOver is a method that can be associated with the applet if you specify the appropriate interface. When this happens, the actual animation updates should be executed in a separate thread. However, in order to make the animations smooth, I think the Image[] associated with each button should be computed at the beginning of each generation and saved in advance. There should be a method in a util class somewhere that returns the Image[] produced by an animating CPPN.
