### ISSUE TITLE
JUnit tests for StatisticsUtilities class

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#32]
All methods in the StatisticsUtilities class need JUnit tests. For each method, several examples with known answers should be tested for correctness.

**Comment by schrum2** [comment]
I transferred this to Gabby to balance workloads, but this is still a pretty low-priority issue. Save it for when there is nothing else to do.

**Comment by Serenamidori** [comment]
Worked on this for a bit, but I'm not sure what does what, so more testing will happen as I understand these uncommented methods

**Comment by schrum2** [comment]
Some of these are complicated, but I can help you out. You can probably also look up some formulas online. However, the following should be familiar to you:

median
mode
maximum
minimum
average
sum
argmax
argmin

**Comment by Serenamidori** [comment]
DONE :+1:
