### ISSUE TITLE
Implement Othello

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#324]
Another board game that should be pretty easy to implement is Othello. I did some work with Othello a long time ago, though no published research came of it. I can teach you how to play if you are unfamiliar.

Note that Othello is also known as Reversi.

**Comment by schrum2** [comment]
Once it seems to work, be sure to verify it both by playing it as a human and by by creating a batch file that will evolve against a random player.

Regarding human play: It might be possible to generalize your human player to any game, rather than making a specific one for each board game .... at least, I feel that you could make a general human player that could play any game involving a simple 2D rectangular board, such as TTT, Othello, and Checkers.

**Comment by DarwinJohnson** [comment]
The Batch File set to evolve against a Random Player appears to be working; the program evaluates both Parents and Children and saves the appropriate files in the correct directories. So far, the Players appear to be evenly matched; it always ends in a Tie right now.

**Comment by DarwinJohnson** [comment]
When selecting a place to Move to, if more than 1 piece can Move to that Space, then all Enemy Pieces form both Moves will be converted. Need to change the code to allow for this.

**Comment by DarwinJohnson** [comment]
Now that the Game's Mechanics are fully implemented, even with extending the TwoDimensionalBoardGame classes, I think Othello is complete. If any more errors arise, we can re-open this Issue, but it should be fully functional right now.
