### ISSUE TITLE
VizDoom: Defend Center Task

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#325]
Looking through your report on all the batch files ( #293 ) reminds me that we had previously put a lot of effort into making the VizDoom Defend the Center task work. It certainly seems to have the most batch files associated with it.

Try running and, if necessary, tweaking the batch files we have to produce good performance in this task. Consider approaches we haven't done yet.

Also, I believe the current best strategy I've seen evolved is to constantly spin while shooting if necessary. This actually works pretty well, but is not optimal, and I'm wondering what we can do to curtail this local optimum.

**Comment by schrum2** [comment]
Launch one of the Defend Center HyperNEAT batch files first thing in the morning and let it run all day ... track what the resulting performance is in this issue. Also note how many generations complete with one day of execution, and note the population size and number of trials in this issue as well.

**Comment by DarwinJohnson** [comment]
Ran VizDoom-DefendCenter-moHNSmudgeRow with a population size of 10 with 5 trials each. Test completed 104 generations before being stopped manually.
Final Values:
Time Spent Alive: Max: 530 Avg: 475 Min: 410
Targets Hit: Max: 3.2 Avg: 2.7 Min: 2
Doom Reward: Max: 4.2 Avg: 3.3 Min: 2.0

**Comment by DarwinJohnson** [comment]
Ran VizDoom-DefendCenter-moHNSmedgeRow with a population size of 50 with 5 trials each. Test completed 72 generations before being stopped manually.
Final Values:
Time Spent Alive: Max: 1008 Avg: 801 Min: 561
Targets Hit: Max: 7.2 Avg: 5.3 Min: 3.4
Doom Reward: Max: 11.8 Avg: 8.4 Min: 5.1

**Comment by DarwinJohnson** [comment]
Ran VizDoom-DefendCenter-moHNSmudgeRow with a population size of 100 with 5 trials each. Test completed 282 generations over the weekend before being stopped manually.
Final Values:
Time Spent Alive: Max: 1590 Avg: 1270 Min: 915
Targets Hit: Max: 12.0 Avg: 9.3 Min: 6.2
Doom Reward: Max: 20.0 Avg: 15.3 Min: 10.0

**Comment by schrum2** [comment]
Please run VizDoom-DefendCenter-moHNSmudgeRowAllColors.bat as well, but
change the pop size and trials to match this previous result.

Something else to consider, which would actually require changing the code,
is changing the fitness to punish missed shots.

A bit of searching around indicates that the agent starts with 26 bullets
in this task, and the enemies in this task die with a single shot.
Therefore, it should be possible to at least sometimes achieve a kill score
of 26. I would like to find a way to reach that threshold, and the first
thing to try is adding all colors to the agent's perception.

**Comment by DarwinJohnson** [comment]
Ran VizDoom-DefendCenter-moHNSmudgeRowAllColors with a population size of 100 with 5 trials each. Test completed 101 generations at the time of this log; will keep running over the weekend to see if any improvement occurs. As of right now, these are the scores:
Time Spent Alive: Max: 1474 Avg: 1171 Min: 823
Targets Hit: Max: 10.5 Avg: 8.1 Min: 5.8
Doom Reward: Max: 19.0 Avg: 14.6 Min: 10.3

**Comment by schrum2** [comment]
After you modify the VizDoom tasks to use the new substrate construction methods from #394 make a new batch file for DefendTheCenter task. Copy VizDoom-DefendCenter-moHNSmudgeRowAllColors into two new files.

First is VizDoom-DefendCenter-moHNSmudgeRowAllColorsConvolution. Add the parameter convolution:true to the file. This allows for a special type of network configuration that I've been working on lately. Let's see how it does.

Also, copy VizDoom-DefendCenter-moHNSmudgeRowAllColorsConvolution again to make VizDoom-DefendCenter-moHNRowAllColorsConvolution. This is the same as the previous (still has convolution) but you should remove the screen smudging (convolutional networks have fewer links, so it's reasonable to have more inputs).

Run these two batch files for a while and see what happens.

**Comment by DarwinJohnson** [comment]
The VizDoom-DefendCenter-moHNRowAllColorsConvolution Batch File has an OutOfMemoryError: GC overhead limit exceeded. The Stack Trace is as follows:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.utexas.cs.nn.tasks.vizdoom.VizDoomDefendCenterTask.interpretOutputs(VizDoomDefendCenterTask.java:157)
	at edu.utexas.cs.nn.tasks.vizdoom.VizDoomTask.oneEval(VizDoomTask.java:202)
	at edu.utexas.cs.nn.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:103)
	at edu.utexas.cs.nn.tasks.LonerTask$EvaluationThread.call(LonerTask.java:92)
	at edu.utexas.cs.nn.tasks.LonerTask.evaluateAll(LonerTask.java:207)
	at edu.utexas.cs.nn.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:363)
	at edu.utexas.cs.nn.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
	at edu.utexas.cs.nn.MMNEAT.MMNEAT.run(MMNEAT.java:812)
	at edu.utexas.cs.nn.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:980)
	at edu.utexas.cs.nn.MMNEAT.MMNEAT.main(MMNEAT.java:940)

**Comment by schrum2** [comment]
So even though convolution reduces the number of links, it's clear that we still need to smudge the input screen in order to handle the massive number of inputs ... at least if we are using all three colors: R, G, B. Try making a batch file with convolution and no smudging that only uses one of the colors (this is what most of them do) and see if this can run without memory problems

**Comment by schrum2** [comment]
Any update on this?

**Comment by DarwinJohnson** [comment]
Tried to run VizDoom-DefendCenter-moHNRowConvolution overnight, but the file didn't complete a single generation even by morning. It appears that having no smudging at all simply takes too long to test efficiently.

**Comment by DarwinJohnson** [comment]
Check if the postEval is working for this Task. Document the results.

**Comment by schrum2** [comment]
With the closure of #416 I would like you to redo from scratch all of the experiments that used convolution. I recall that one had a memory problem as well, but try running it again anyway. For the one with the memory problem, try adding the parameter receptiveFieldSize. The default value is 3, and the value MUST be an odd integer. Try increasing this value (3,5,7, ...) until you reach a number that does not cause a crash due to memory problems.

**Comment by DarwinJohnson** [comment]
Ran VizDoom-DefendCenter-moHNSmudgeRowAllColorsConvolution over the weekend. The Fitness Scores appear to be not improving much. The File completed 67 Generations so far, but it may not improve by a significant margin if left running. It shall be kept running until otherwise told to stop it. Here are the results so far:
Time Spent Alive: Max: 1570 Avg: 1309 Min: 823
Targets Hit: Max: 12.0 Avg: 9.5 Min: 5.5
Doom Reward: Max: 20.0 Avg: 16.2 Min: 9.4

**Comment by DarwinJohnson** [comment]
We looked at a number of ways to improve the VizDoom Scores, but we appear to be hitting a ceiling of 12 Targets Hit. Perhaps future research will be able to break through this ceiling, but this will be postponed for now.
