### ISSUE TITLE
VizDoom and HyperNEAT visualization problem

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#326]
There is definitely a problem with VizDoom when postAllBestObjectiveWatch.bat is used on agents evolved with HyperNEAT. Specifically, the problem seems to be an ArrayIndexOutOfBoundsException when drawing the graphics for the final output substrate.

Figure out what the issue is and fix it. An example that you can use to recreate the issue is
VizDoom-DefendCenter-moHNSmudgeRowAllColors.bat

**Comment by DarwinJohnson** [comment]
Apparently applies to board game tasks as well

**Comment by DarwinJohnson** [comment]
Will re-create the issue using the run config in Eclipse to track down the issue.

**Comment by DarwinJohnson** [comment]
Correction to the previous Commit: The VizDoom Visualization Error was, in fact, caused by the same Error in TicTacToe. The issue has been resolved; HyperNEAT VizDoom Tasks can now be seen using postAllBestObjectiveWatch.
