### ISSUE TITLE
Generalized and improved fitness functions for microRTS

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#328]
Design a MicroRTSFitnessFunction abstract class or interface (whichever seems appropriate) and have your current fitness function extend/implement it. Allow the fitness function for microRTS to be designated as a command-line parameter.

Note that the fitness labels needed by the registerFitnessFunction calls in the task constructors will have to come from instances of this new fitness function class.

Additionally, once you have a general way of specifying different fitness functions, try making a better fitness function. Specifically, make one that tracks information throughout the course of the game and uses that for scoring purposes. Information that might be useful includes the average number of player/enimy units throughout the course of the game, the average player/enemy unit differential, and the time it took for your base to be destroyed (scaled against the total duration of the match).

You will probably need to track this information in the oneEval method regardless of which fitness function is being used, but as long as the information is available to any fitness function that needs it, that should work.

Note that in general, it is not a good idea to evolve with more than three separate objectives, as multiobjective methods can have trouble handling lots of objectives, though sometime you get lucky ... it really depends on the nature of the objectives. Just don't go crazy adding too many objectives.

**Comment by schrum2** [comment]
Classes related to these fitness functions should be in a new package:
edu.utexas.cs.nn.tasks.microrts.fitness

**Comment by alicequint** [comment]
finished in ...microrts.fitness.ProgressiveFitnessFunction
