### ISSUE TITLE
Make all board game tasks into HyperNEAT tasks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#331]
The different board game tasks (static, coevolution, etc.) should be HyperNEAT tasks. This means they need to return substrate information. However, this substrate information should come from the BoardGame instances. However, I wonder if we can avoid duplicated code by making a general TwoDimensionalBoardGame abstract class that implements BoardGame, and is extended by TTT, Othello, Checkers, etc. These games all have 2D boards, and they probably have some other common functionality.

Focus on making a TwoDimensionalBoardGame class first that is between BoardGame and each of the games you have already made (except for RPS). Then, have that class return general substrate information: One substrate for the board, one processing layer that is the same size, and an output layer with one neuron.

**Comment by schrum2** [comment]
This is the next high-priority issue. Try to get a working example of an agent evolved with HyperNEAT against a random tic-tac-toe player. You will need to make a new batch file for this.

**Comment by DarwinJohnson** [comment]
HyperNEAT TicTacToe appears to be working, and other BoardGames can likely run as HyperNEAT Tasks as well. However, there is a visualization error when using PostAllObjectiveBestWatch.bat, similar to the VizDoom issue #326. This specific issue can be closed, and the lingering visualization error will be fixed soon.
