### ISSUE TITLE
TwoDimensionalBoardGameViewer

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#335]
Scrap the BoardGameViewer class and replace it with a TwoDimensionalBoardGameViewer class. However, remove the code and start from scratch. The game should be drawn using the DrawingPanel class, which is fairly easy to use. 

All 2D games should be drawn as a rectangle of squares whose size is determined by the getBoardWidth and getBoardHeight methods.  You should add a method to TwoDimensionalBoardGameState that is like getPlayerSymbols, except it associates each player index with a Color instance.

For now, let's assume all games have simple white grids for a background (don't worry about color) and that all player pieces are colored circles (even the X in TTT). We can get fancy later.

**Comment by schrum2** [comment]
Change the CommonConstants.watch portions of the board game tasks to actually use the 2D board game viewer in the case that the game being played is a 2D board game. This basically boils down to updating the graphics in the viewer each time a move is about to be made. A special case may be needed to show the final game state after the last move.

This will probably flash by extremely fast, but if the "stepByStep" parameter is used, then it should allow a user to watch a game unfold one move at a time.

**Comment by DarwinJohnson** [comment]
The TwoDimensionalBoardGameViewer is fully implemented and tested. It runs perfectly now.
