### ISSUE TITLE
Make a List of All Agents that can Definitely be used in MicroRTSTask

### ISSUE THREAD

**Issue by alicequint** [schrum2/MM-NEATv2#336]
the list will go on the google drive, and will include the path that is needed for entering it into the command line or a batch file as a parameter. i'll do this as soon as i finish tying out and integrating all the agents ive found

**Comment by alicequint** [comment]
https://docs.google.com/document/d/1ts3FOQuAvKO9xtwv6Eov3AIFpfm5q2AVNJO6dv6THaU/edit

**Comment by schrum2** [comment]
I found a very useful site with information about the MicroRTS domain. It
lists out all of the agents included in the code, and event has several
links to papers describing rudimentary experiments with the different types
of agents. Use this list to make sure you are fully exploring all possible
agents, and also to compare performance they achieved in experiments with
our own performance. See how they evaluate agents, and in general look for
interesting ideas we can steal or improve upon.

Here is the site:
https://github.com/santiontanon/microrts/wiki/Artificial-Intelligence
