### ISSUE TITLE
SinglePopulationCompetativeCoevolutionMicroRTSTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#337]
Create a new SinglePopulationCompetativeCoevolutionMicroRTSTask that extends the SinglePopulationCoevolutionTask. This approach would pit evolved agents using two different evolved neural networks against each other in an attempt to create better and better agents.

This class would share a lot of code with the original MicroRTSTask, so you should make a MicroRTSUtility class that stores static methods common to each of the two tasks. In particular, a generalized evaluation function should be in this class.

**Comment by alicequint** [comment]
MicroRTSUtility as well as SinglePopulationCompetativeCoevolutionMicroRTSTask  exist and work

**Comment by schrum2** [comment]
Re-opening this so you can address the fitness tracking issue: Each individual that is evaluated needs its fitness stored/tracked separately.

**Comment by schrum2** [comment]
Did your recent fitness function improvements make co-evolution work correctly? If so, then you can close the issue.

**Comment by alicequint** [comment]
yes, coevolution seems to be working fine
