### ISSUE TITLE
Implement and test Checkers

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#342]
You have already put a lot of work into Checkers, so I figured I would make it an official issue (feel free to open issues about code you are working on). Finish implementing Checkers, and afterward write JUnit tests for the CheckersState, since that is definitely a complicated class with lots of possible room for error.

It is also pretty clear that Checkers breaks some of the assumptions of out 2D board game and 2D board game viewer, in that it is a game in which a player can have more than one type of piece. The fact that Checkers also allows one player to make a series of moves at once also complicates things. It is possible that we will need to change the 2D board game class in order to fully accommodate Checkers, so look out for ways to make the code more flexible.

**Comment by DarwinJohnson** [comment]
The CheckersState Test Cases function perfectly. The game runs as expected. Checkers is now fully implemented.
