### ISSUE TITLE
Piece Differential BoardGameHeuristic

### ISSUE THREAD

**Issue by DarwinJohnson** [schrum2/MM-NEATv2#345]
Create a BoardGameHeuristic that returns the number of Player Pieces minus the number of Enemy Pieces on any given BoardGame. A Player using this Heuristic will value Moves that increase the number of Player Pieces and/or decreases the number of Enemy Pieces.

**Comment by schrum2** [comment]
I think this is correctly implemented. Go ahead and close this issue after you have a running batch file against a one-step-eval opponent that uses the piece differential heuristic.

**Comment by DarwinJohnson** [comment]
There are now two Othello Batch Files that have an Opponent that use the PieceDifferentialHeuristic. This Issue should be done for now.
