### ISSUE TITLE
OutOfMemory error in MicroRTS

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#346]
This could be an issue with the Monte Carlo agent that comes with the microRTS code, or it could be an issue with how you re-organized code to generalize the standard and coevolution tasks. The problem is likely a memory-leak (or the Java equivalent of one).

If you are not able to close this issue quickly and easily, then track all details associated with the bug here. Also, I can show you how to use a memory profiler to help troubleshoot the problem, but try figuring out the issue without this first (it is a hassle to set up)

**Comment by alicequint** [comment]
the code Can run for multiple trials,
whenever it stops, it is on pa1.getAction()

**Comment by schrum2** [comment]
Please indicate which batch file or run parameters are consistently creating the crash

**Comment by alicequint** [comment]
batch file: MicroRTS-2D-Progressive.bat
program crashes after a few minutes,
does not crash if fileio is false

**Comment by schrum2** [comment]
I'm currently having trouble re-creating this. If it happens to be fixed, then that's great! However, if the error ever occurs again then be sure to mention it here.

If we don't encounter this error again for a while, then I will close the issue.

**Comment by schrum2** [comment]
I'm closing this since it doesn't seem to be a problem anymore.
