### ISSUE TITLE
ActivationFunctionMutation

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#35]
Add an activation function mutation to the package edu.utexas.cs.nn.evolution.mutation.tweann. Model it on the other mutation operators in this package. Define a corresponding double parameter for the mutation rate ... give it a default value of 0.0. As with the other mutation operators, it may be appropriate for the code that modifies the genes to be in TWEANNGenotype, and simply be called from the mutation class that you create.

**Comment by schrum2** [comment]
Also be sure that this mutation operator is called in the mutate method of TWEANNGenotype along with the other mutation operators, but ONLY if the boolean parameter allowing for multiple activation functions is set to true.

**Comment by leg2015** [comment]
Added an activation mutation function

**Comment by schrum2** [comment]
I made some slight changes to this. Mainly, each mutation type needs a parameter associated with it that defined the mutation rate. Please go back and comment the updated file.

**Comment by leg2015** [comment]
Commented the updated file, specifically the part addressing the new command line parameter added
