### ISSUE TITLE
Behavioral Diversity in Board Games

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#350]
Implement a default domain-specific behavior characterization for board games that simply puts the getDescription results into an ArrayList (there is a method in ArrayUtil that can take care of this for you). Note that the actual handling of this should be via a static method in the BoardGameUtil class so that if we change our mind about the default behavior characterization, it will affect all variants of the board game task (static, coevolution, etc.)

Then create a batch file to evolve board game players against static opponents using behavioral diversity in Othello. See how it works!

Next, we should try applying this approach to co-evolution of board games as well, though I am not sure if that will be as easy to do.

**Comment by schrum2** [comment]
Have you run any of the BD batch files for a while? I'm curious about the results.

**Comment by DarwinJohnson** [comment]
Ran Checkers-MOBDStaticAlphaBetaPD for 96 generations with default settings, including the SimpleWinLoseDraw FitnessFunction.
Final Results: Max: 0.1 Avg: -1.0 Min: -2

Ran Othello-MOBDStaticAlphaBetaPD for 28 generations with default settings, including the SimpleWinLoseDraw FitnessFunction.
Final Results: Max: 0.4 Avg: -0.6 Min: -1.4

**Comment by schrum2** [comment]
I'm interested in a side-by-side comparison. Properly doing this requires a lot of runs, but for now, run a single experiment with Othello against the weighted piece counter, and run another experiment that is identical in every way, except that it uses Behavioral Diversity. Then we can check the results side by side.

Be sure to set the minimax search depth high, say 5, for each of the batch files you create to run these experiments.

**Comment by DarwinJohnson** [comment]
Running the two Othello games on the Tower of Power. Will run overnight and document the results. minimaxSearchDepth is set to 5 for both, trials = 10, mu = 100, and maxGens = 500.

**Comment by DarwinJohnson** [comment]
Small update: the Othello-MOBDStatic and Othello-Static tasks running on the Tower of Power have completed Gen 0. Maybe it's just really, really slow. I've noticed that Othello Batch Files take longer than Checkers Batch Files to run, though I don't know why. Or, maybe the Tower was asleep overnight and just now woke up enough to complete that Gen. The Othello-MOBDStatic and Othello-Static tasks running on the regular work computer has yet to complete the parents of Gen 0, so it's unclear as of yet. More details as details arise.

**Comment by DarwinJohnson** [comment]
Othello-MOBDStatic and Othello-Static had completed Gen 0 after approximately 16 hours. The minimaxSearchDepth was too large to run experiments with any speed at all. Both Batch Files now have a minimaxSearchDepth of 2, and both are running on the Tower of Power. All other variables remain the same, and results will be documented.

**Comment by DarwinJohnson** [comment]
As of right now, the Othello-MOBDStatic has completed 165 Generations, and Othello-Static has completed 175 Generations. Both use the SimpleWinLoseDraw Fitness Function. Here are the current results:
MOBD: Max: 1 Avg: -0.02 Min: -1.1
Static: Max: 1 Avg: 0.25 Min: -1.1

**Comment by schrum2** [comment]
At this point, I think it's ok to go ahead and terminate these runs and close the issue.
