### ISSUE TITLE
Game Tree Search overrides for win and loss states

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#354]
For the NNBoardGameHeuristic, make it so that a terminal win state returns a result of 1 instead of the network's evaluation, and a terminal loss state returns a result of -1 instead of the network's evaluation. A terminal win state should return a 0.

Actually, make a boolean command line parameter that makes this overriding an option. Call it something like  "heuristicOverrideTerminalStates". If it is true, then do what I said above, but if it is false, then listen to the evolved network no matter what.

**Comment by DarwinJohnson** [comment]
The "heuristicOverrideTerminalStates" Parameter has been added, and the appropriate changes have been made to the NNBoardGameHeuristic.
