### ISSUE TITLE
Launch evolved network from the microRTS frontend GUI

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#358]
As a stepping stone to creating a standalone entry for the competition, simply figure out how to load an evolved agent using the GUI front end within the MM-NEAT project. I'll associate a commit with this issue soon pointing out how I think you can do this in the code.

**Comment by alicequint** [comment]
done in MMNEAT, moving on to doing the same in the stand alone MicroRTS

**Comment by schrum2** [comment]
Reminder: once it works in the stand-alone microRTS project, you will need to go one step further and extract only the classes/packages relevant to our specific entry. Once this works, you will actually need to create a GitHub project in your own GitHub account to host those files (a requirement of the project is making your code readily accessible in this manner)

**Comment by alicequint** [comment]
this has already been done. the only thing left, to my knowledge, is evolving a good enough neural network for the evaluation function to load

**Comment by schrum2** [comment]
I think this is done, though related work in the separate SUai code still needs to be completed ... perhaps you can track that work here? I know that the next thing you need to do is define the Parameter options for the SU agent.

**Comment by schrum2** [comment]
Closing this since it deals with code in a separate repository. However, the Frontend class in MM-NEAT is capable of running our evolved agents, as long as the xml file is correctly specified in the code.
