### ISSUE TITLE
Othello Weighted Piece Counter

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#361]
A standard type of heuristic player that has been particularly successful in Othello is a weighted piece counter. A weighted piece counter evaluates board states by associating a weight with each board position and adding that weight to the board's game score if a piece is present there. If the enemy piece is present there, then the weight at that position is multiplied by -1.

Create a general weighted piece counter heuristic that can be applied to any 2D board game.

Once that works, make a specific StaticOthelloWeightedPieceCounterHeursitic. Once constructor takes a 2d (or 1d?) array of doubles to define the weights. However, the default constructor should load the specific pre-defined weights on page 2 of this paper:
http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=10AB4B0966FEE51BE133255498065C42?doi=10.1.1.580.8400&rep=rep1&type=pdf

Once this works, evolve against it (make a batch file)! Our neural networks should be able to beat it.

**Comment by DarwinJohnson** [comment]
Created the general WeightedPieceCounter Heuristic and the OthelloWeightedPieceCounter Heuristic. Created several Othello Batch Files that use the new Heuristic. Batch Files run successfully.

**Comment by schrum2** [comment]
Try playing a game, as a human, against the Weighted Piece Counter. Confirm that it is a decent player. Once you are convinced of this, you can close this issue.

Side note: all Othello batch files for evolving against a static opponent should be against this opponent ... no point keeping the piece differential and random opponent batch files around.

**Comment by DarwinJohnson** [comment]
After a series of tests, I believe that the Weighted Piece Counter is a decent Heuristic. While the first batch of evolved opponents weren't particularly skilled, they made Moves that made sense and were challenging to play against. It will be interesting to play the fully evolved opponents. For now, we can be assured that this Heuristic makes sense to use, and provides a challenge to play against.
   The Batch Files for Othello will be cleaned up to ensure that no Agents use the Piece Differential Heuristic; all Othello Batch Files will use the Weighted Piece Counter.
