### ISSUE TITLE
"other" score for co-evolution: performance against static agent

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#362]
In co-evolution, it can be difficult to assess whether or not your population is actually improving. Generally, the way to do this is to compare members of the population against a fixed opponent, even tough such comparisons will not affect the fitness of the co-evolving agents.

Scores like this are the reason that "other" scores are allows in MM-NEAT (Alice has some experience with this, so check with her). Basically, you can assign a score to each agent that is tracked/associated with the agent, but does not affect fitness.

If you are co-evolving board game players, then once scores with tracking is how well the evolved agent performs against a fixed static opponent, such as a minimax player using the piece differential heuristic, or a weighted piece counter ( #361 ) heuristic. In fact, I was reminded about this idea from this paper: http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=10AB4B0966FEE51BE133255498065C42?doi=10.1.1.580.8400&rep=rep1&type=pdf

Create a class that computes an other score for a board game playing agent by pitting it against a static opponent that is designated in the constructor of the class.

**Comment by schrum2** [comment]
There is one thing we could do to improve this. Here is how I think this currently works in a coevolution context:
Coevolution picks two agents, then play each other, and afterward each one plays a game against the static opponent. Unfortunately, these same agents will be picked again to go against different opponents, but be required to play against the static opponent again! This is a waste of resources.

Here is how to improve this:

This fitness function class should store a HashMap of Long to Double. At the beginning of each generation, the contents of the HashMap should be emptied (need to figure out where in the code to do this). Then, every time that a fitness value for a new network is asked for, the fitness function should first check to see if the value is already stored in the HashMap. The HashMap will associate Long genotype IDs with Double fitness scores. If there is no entry in the map for the given genotype ID, then a game against the static opponent is played ... afterward, the score is saved in the HashMap so that if it is asked for again, it can simply be retrieved rather than computed again.

**Comment by DarwinJohnson** [comment]
The Hashmap appears to have cut down on the evaluation time of the Coevolved Agents; Checkers-HNSinglePopCompCoevolveAdvanced completed 15 Generations within 4 hours, and Othello-HNSinglePopCompCoevolve has completed 10 Generations. This is an improvement from the last run times.

**Comment by DarwinJohnson** [comment]
With the added optimization, this Issue can now be considered complete.
