### ISSUE TITLE
HumanVisualBoardGamePlayer

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#366]
Now that the 2D game viewer works, create a new board game player that can be used as long as the board game viewer is active. It works by waiting for the human player to click on a valid location to make a move. This should be easy for Othello and TTT, though extra work may be needed to get Checkers to work ... don't worry about that just yet.

In fact, this should be a pretty low-priority issue, but we definitely want to play against evolved opponents eventually.

**Comment by DarwinJohnson** [comment]
The Human 2DBoardGamePlayer is now fully implemented and has been tested. Everything appears to be working now. Further details are included in the previous commit: 1711beb .
