### ISSUE TITLE
Do post evals work for single population coevolution?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#369]
Multi-population coevolution requires special post-watch batch files and "experiment" classes, but what about single-population coevolution? What happens when you run a post eval on a board game result evolved with single-population coevolution? Does it crash, or does it actually show a game ... if it shows, a game, then who are the opponents that face off?

This task should probably be completed after #368 . Try running the standard post eval to see what happens. I bet it doesn't work. Look in the package edu.utexas.cs.nn.experiment.post. This is where all experiment variants are that are used for post-evaluation.

Even if the standard post-eval doesn't crash, I bet it does not do what we need it to do. In particular, we need to have the ability to take the best results from coevolution, and pit them against another benchmark agent, such as a weighted piece counter, or even a human player. The exact experiment class created for this may need to be specific to board games, like a BoardGameBenchmarkExperiment.

At first, simply try to accomplish the following: load the best results from coevolution, and pit them one by one against a human player. Note that the way all post-eval batch files work is that they load a finished experiment's parameters, but then the parameters specified in the batch file override the original experiment parameters. This allows you to have access to all of the settings from the previous experiment, such as the type of board game played, and chance others.

Once play against a human player is possible, we'll look into how best to designate other benchmark opponents.

**Comment by DarwinJohnson** [comment]
Is there an easy way to access the Parameter data in a given Batch File run? There are several Parameters in the BoardGameBenchmarkExperiment that need to be initialized to the same variables as the original Batch File run in order to maintain consistency. For example, the BoardGame, FitnessFunction, and HeuristicFunction need to be identical to those specified in the original one.

**Comment by DarwinJohnson** [comment]
Need to create a Batch File in the Root Directory that calls the BoardGameBenchmarkExperiment.

**Comment by schrum2** [comment]
Remind me: what is left before this issue is resolved?

**Comment by DarwinJohnson** [comment]
I don't think there's anything left. The postEvals work with both Static and SinglePop Coevolved Agents, though we are unsure if it works with Multipop Coevolved Agents. I remember you said you wanted to clean up the Batch Files that called this postEval and make them more user-friendly, but I think that's it.

**Comment by schrum2** [comment]
Basically, I want it to be easy to pit the evolved agents against opponents besides the human opponent. I was hoping this could be easily specified with a command line parameter, but the opponent and its accompanying heuristic are both length class names, so I don't think that's practical.

Instead, I think the appropriate thing to do is to have some extra batch files for opponents we would want to use as post benchmarks. Right now, the only one that fits this category is the Othello weighted piece counter with alpha-beta pruning. Make a batch file for benchmarking against this agent instead of the human player (make the minimax depth very deep, say 10).

Once this file exists, close the issue (if we create better benchmark players for other board games, then we will create batch files for them as well)

**Comment by DarwinJohnson** [comment]
There is now a Batch File for having a Coevolved Othello Player play against an AlphaBetaPruning Minimax Player with a minimaxSearchDepth of 10 and a Weighted Piece Counter Heuristic. The Batch File allows you to visually watch the game stepByStep.
