### ISSUE TITLE
Fitness awarding aggression and/or destruction of enemy units

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#372]
Preliminary results with MLPSMCTSIterativeHYPER indicate that the agents can sometimes fend off the opponent, but they often wander aimlessly and never finish off the base.

Some component of the fitness function needs to reward the destruction of enemy units. However, we have to be careful ... simply granting fitness for each enemy unit destroyed could backfire if it means that our agent stupidly allows the enemy to create lots of units.

Instead, I think we should reward our agent based on the percentage of all enemy units that it destroys. If the enemy doesn't make any units before being destroyed, then our agent gets a score of 100 percent. However, if lots of units are made, and our agent still wins, then that is also 100 percent.

For the sake of this fitness function, I think that enemy buildings should also count as "units" to assure that the agent also has a pressure to destroy the enemy base.

**Comment by alicequint** [comment]
this is now a part of progressive fitness function,
if the results we get on monday are reasonable, i'll close this issue

**Comment by alicequint** [comment]
even though the batch files that were ran over the weekend failed due to unrelated bugs, tests from today suggest that this feature is working.
