### ISSUE TITLE
Checkers end state error

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#380]
Visualizations are very useful.

I was playing Checkers, and the following state was labelled as a terminal state (I was playing against the piece differential heuristic and game over occurred).

![image](https://user-images.githubusercontent.com/8397236/26999148-6196626c-4d58-11e7-8943-b6d5e23d9e17.png)

Fix this error (make a JUnit test that verifies that this exact state is not terminal, and also try to test some similar potential errors)

**Comment by DarwinJohnson** [comment]
Changed the code in the CheckersState class pertaining to the Double Jump and Forced Jump. This appears to have fixed the EndState Error. Played through several Checkers games to ensure the code was working, and I was able to complete several matches without the game ending before an End State. I believe that this Issue can be closed.
