### ISSUE TITLE
Comment RL Glue Feature Extractors for Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#39]
Understand the existing RL Glue feature extractors.

Incidentally, the basic Tetris evolution example does not use any of these existing extractors. You should probably switch the default example bat/bash files to use one of these extractors, and see if they perform any better.

**Comment by Serenamidori** [comment]
To clarify, did you mean the RLGlue extractor that it was originally "using" or the BertsekaTsisiklisExtractor?

**Comment by schrum2** [comment]
BertsekaTsisiklisExtractor is good enough for now.

On Wed, May 18, 2016 at 10:11 AM, Gab notifications@github.com wrote:

> To clarify, did you mean the RLGlue extractor that it was originally
> "using" or the BertsekaTsisiklisExtractor?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/schrum2/MM-NEATv2/issues/39#issuecomment-220058107

## 

Jacob Schrum, Ph.D.
Assistant Professor of Computer Science
Department of Mathematics and Computer Science
Southwestern University
1001 E. University Ave.
Georgetown, TX 78626

Office: Mood-Bridwell Hall 141
Mail: SU Box 7341
Off-Campus Phone: (512) 863-1712
On-Campus Extension: x1712
E-mail: schrum2@southwestern.edu
WWW: http://southwestern.edu/~schrum2
