### ISSUE TITLE
Checkers players

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#399]
First, here is another paper to add to the repository and to mention in your writing:
https://pdfs.semanticscholar.org/91c9/d140267f3b008d00b330b6b0e9182fa4b62e.pdf

This paper is about evolving heuristics for checkers players. However, it includes discussion about many other heuristic-based techniques, and suggests useful features for a heuristic Checkers player. I would like to have a stronger static Checkers player to compete against, and think that this paper might provide guidance in this direction. See if you can use this paper or the papers it cites to develop a strong static heuristic Checkers player.

**Comment by schrum2** [comment]
Also, here is another Checkers paper that probably doesn't provide much practical guidance, but contains useful information that might be worth citing or discussing later:
http://library.msri.org/books/Book29/files/schaeffer.pdf

**Comment by schrum2** [comment]
This should be a very low priority issue.

**Comment by DarwinJohnson** [comment]
This Checkers Player is no longer being implemented due to its high use of human expertise. It may be useful as a Static Opponent later on, but for now, this Issue is being closed.
