### ISSUE TITLE
Enemy sequences: not happening, or not tracking the score?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#405]
I ran MicroRTS-MLPSMCTS-IterativeSet-HYPER.bat last night and it has reached 25 generations without error, which is great! However, despite using CompetitiveEnemySequence, the log does not indicate that any enemy switch/addition has ever occurred. 

Either the enemy switch/addition is not occurring, or it is not being logged correctly with the "other" score that tracks it.

Note that the log does indicate that a map switch occurred.

**Comment by alicequint** [comment]
the log now indicates when enemy switches occur
