### ISSUE TITLE
Othello: pass on no moves

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#408]
I was messing with Othello and the following state registered as Game Over:

![image](https://user-images.githubusercontent.com/8397236/27248597-7ea9b49e-52cb-11e7-9219-c1777c0db302.png)

While it is true that White cannot move, Black can. According to this site, http://www.ultraboardgames.com/othello/game-rules.php,
"When a player has no valid moves, he pass (sic) his turn and the opponent continues."

Fix the problem and set up unit tests to test for it.

**Comment by DarwinJohnson** [comment]
The new JUnit Tests for this given State now pass; the Passing mechanics in OthelloState have been changed. This bug should no longer occur.
