### ISSUE TITLE
Triple winner?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#409]
The feature that prints out the winners at the end of a watched game prints out the winner three times. Why are there three copies of the winner in the winner array? It looks like this:

Winner(s): [0, 0, 0]

**Comment by schrum2** [comment]
I notices similar problems in Checkers. I think I have actually fixed the problem in both games, but I want this issue unit tested. Also, I don't like the way I fixed it, since I simply added checks that the winners array was empty before anything was added, but the real problem is that the method(s) that add winners are maybe being called too many times? Look into it.

**Comment by DarwinJohnson** [comment]
This Issue can likely be closed.
