### ISSUE TITLE
Comment CooperativeCoevolutionMuLambda

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#41]
Comment and fix compiler warnings in CooperativeCoevolutionMuLambda. This class might be appropriate for performing cooperative coevolution in the pred/prey domain, but I'm not certain. Once you have commented it, perhaps you will have a sense of whether this code will work, or a different type of EA needs to be made

**Comment by Rollinsa** [comment]
Commented CooperativeCoevolutionMuLambda so that the class has a comment explaining in a general sense every method and class
