### ISSUE TITLE
Alpha-Beta Optimization

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#410]
There were some problems with the minimax search agent that will be committed soon. However, there is still a problem with alpha beta search. Look at my TODO comment in BoardGamePlayerMinimax. The alpha beta search is not fully optimized.

**Comment by schrum2** [comment]
Note: the trick is to make Alpha and Beta by Object references in Double classes, much like the ReferenceObject class that came up in the 2dTree project from CS2.

**Comment by DarwinJohnson** [comment]
The JUnit tests for the OthelloPieceDifferential Heuristic and the Minimax/AlphaBeta comparison now fail after trying to optimize the Alpha Beta Minimax Player. I'm not really sure why these tests are failing, especially in the case of the OthelloPieceDifferential; no code that I changed today should have affected that test. Any aid in resolving this issue would be appreciated.

**Comment by schrum2** [comment]
This is fixed. Alpha and beta did not actually need to persist as references, but they did need to be processed/updated at the initial kick-off call in takeAction.
