### ISSUE TITLE
JUnit tests for Othello Weighted Piece Counter

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#411]
The calculation for the Othello WPC is pretty straight-forward. I want you to make some JUnit tests for it.

In particular, it is very important to correct a misconception that I recently fixed throughout the code. Heuristic functions do not care who the current player is. They always rate the board from the perspective of Player 1, which therefore means that negative scores are good for Player 2. So, your heuristic test should return the same values regardless of who the current player is. Check some random board states and test them.

Also, play a game against the WPC now ... I'm hoping that from a human perspective, it comes across as a more difficult opponent.

**Comment by DarwinJohnson** [comment]
Completed the Othello WPC Heuristic JUnits testing. The heuristic functions properly.
