### ISSUE TITLE
Fix VizDoom Substrates

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#416]
The reason that VizDoom runs were crashing was because of errors made when the VizDoom substrates were generalized. Specifically, the output substrates are constructed incorrectly, in that they have the wrong sizes. I'll be making a commit soon that fixes the defend-the-center task, but you will need to fix all of the rest: launch each batch file to make sure it runs without crashing before closing this issue.

**Comment by schrum2** [comment]
The comment above fixes the issue for defend the center. The errors were introduced with this commit:
3322a1d8b99076e5fc847b9616059460377bd2f3
Note that the substrate sizes in the code that was added **should** have come from the Integer Pairs that are the first arguments to the Substrate constructors.

**Comment by DarwinJohnson** [comment]
Ran each of the VizDoom HyperNEAT Batch Files. Each of them appears to be working; they don't crash during start-up.
