### ISSUE TITLE
Allow general fitness functions for TorusEvolvedPreyVsStaticPredatorsTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#42]
The TorusEvolvedPreyVsStaticPredatorsTask currently uses the duration of the evaluation as a fitness function, but this is not necessarily the best option when there are multiple prey, and should be replaced by something more general. Allow for one or several fitness functions to be specified for torus domains. One fitness function will be the overall duration of evaluation, another can depend on how long each individual prey lives. Compare against the edu.utexas.cs.nn.tasks.mspacman.objectives package to see how multiple possible fitness functions might work.

**Comment by Rollinsa** [comment]
Implemented the ability for general fitness functions by making a gridTorus.objectives package and adding code to the TorusPredPrey task and its children that allowed for a variable list of fitness scores that could be activated by command line parameters
