### ISSUE TITLE
Make MicroRTS support the stepByStep parameter

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#425]
The stepByStep parameter makes it so that there is a pause after each step of the simulation so that an observer can more easily follow what is happening. The pause is inserted via the MiscUtil's wait method that you have used for troubleshooting. You can see an example of stepByStep used in BoardGameUtil.

Make microRTS support stepByStep for easier troubleshooting. Pause on every game cycle.

**Comment by alicequint** [comment]
this has been done, although when i tested it i decided that pausing every other game step would be better  because of how little changes during each one, and viewing every two steps is enough to see every stage of the fastest action
