### ISSUE TITLE
Game Match Log

### ISSUE THREAD

**Issue by DarwinJohnson** [schrum2/MM-NEATv2#426]
Create a Board Game Match Log that keeps track of each individual match between coevolved agents. The Log should say which two agents played against each other in a match, the fitness of each agent from the match, and the genotype IDs of the agents. Cross-reference this with the existing logs within the subdirectories. Create a "boardGameLog" boolean parameter that is defaulted to false, as this is computationally expensive. If the parameter is set to true, create the log and save a new one for each generation.

**Comment by schrum2** [comment]
This logging option can/should apply to evolving against static opponents as well, which is probably good, since you won't have to have special cases for evolution vs co-evolution.

**Comment by DarwinJohnson** [comment]
The Board Game Log has been created. Each Log contains the names of the Players, which positions the Players were at during a given Match, and the Fitness Scores and Other Scores of the Players from each Match. Setting the "evalReport" Parameter to true will create this Log for every Agent created within a Population. This Parameter is defaulted to false due to how computationally expensive this logging feature is, but it should be useful for troubleshooting.

**Comment by DarwinJohnson** [comment]
Scores in the EvalLog are now confirmed to be identical with those in the Parents Fitness Log.
