### ISSUE TITLE
Review all interactive evolution buttons

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#428]
A lot of buttons have been inherited into the various evolution tasks from InteractiveEvolution. These features were part of the original Picbreeder.

Make sure that all buttons work with all interactive tasks, and document any errors that you find.

Also, comment out the code in evolution task that adds the "Close" button. I don't think there is enough room in the interface for such an unnecessary button. Keep the code though ... just comment it.

**Comment by twerisa** [comment]
All buttons work for Picbreeder and Breedesizer.
For AnimationBreeder and 3DObjectBreeder, 

- The networks don't show up when the network button is clicked. This was fixed earlier in the week, but I think alwaysAnimate caused the problem again.

- The reset button causes the code to crash. Attempted to fix it by overriding reset(), but it caused the same error.

- The undo button is also causing the code to crash in the same way as the reset button.

- I'm not sure what the lineage button is supposed to do, but it doesn't seem to be doing anything for any of the interfaces.

**Comment by twerisa** [comment]
The evolve, undo, and reset buttons seem to work fine on the interface, but they all display an IndexOutOfBoundsException at the "setButtonImage(animations[imageID].get(frame), imageID);" command in the run() method of AnimationBreederTask.

**Comment by schrum2** [comment]
In animation breeder, the actions these buttons initiate need to be overridden to first stop all active animations. In some cases, you will also need to clear out the cached animation frames.

Regardless, do not commit a version that works worse than the current version ... keep problematic code in comments if you want to commit something that is a work in progress

**Comment by twerisa** [comment]
Network button functions for AnimationBreeder and 3DObjectBreeder both when alwaysAnimate is true and when alwaysAnimate is false. The only button debugging left at this point is resolving the error occurring when the reset button is clicked in 3DObjectBreeder (it works fine for AnimationBreeder).
