### ISSUE TITLE
Simple eval function again

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#433]
A lot of our effort has been focused on getting more and more complex evaluation functions to work. This is important because generating intelligent behavior with less expert knowledge is generally more interesting. However, winning these competitions can often involve lots of human knowledge.

Therefore, I would like you to launch some experiments with the simple evaluation function again ... the one that just takes basic information from the game state (unit counts, etc) without having any substrates that scale across the map. We should compare this simple approach with the more complicated HyperNEAT approach, and also see if there are some more high-level features that we can feed to the "simple" evaluation function.

To get the best result possible, we may need to "cheat" a bit.

**Comment by alicequint** [comment]
it is reworked, and tests with it run fast, but results so far are not promising.
with agent MLPSMCTS against randomBiasedAI, it ran 200 generations over the weekend and did not show any significant improvement. :disappointed:

**Comment by schrum2** [comment]
It is unfortunate that this does not work, but I guess I can go ahead and close this issue.
