### ISSUE TITLE
Feature extractor for Checkers

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#437]
Checkers needs a slightly specialized variant of the raw feature extractor that assigns a higher magnitude input value to Kings than to regular pieces. Refer to the HyperNEAT Checkers paper to see what values they used.

**Comment by DarwinJohnson** [comment]
Double-checked that the change to the CheckersState getDescription method didn't cause any errors. All calls to getDescription appear to be by the Network for evaluation, and therefore should be fine. Ran Checkers-Static.bat to ensure that this was the case. File did not crash after a full Generation, so it appears to be working.
