### ISSUE TITLE
Number of games against static opponent fitness/other score

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#444]
While re-reading the Othello coevolution paper (http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=10AB4B0966FEE51BE133255498065C42?doi=10.1.1.580.8400&rep=rep1&type=pdf) I noticed that they evaluated performance against the WPC by playing 5000 (!) games against it with randomized moves. That's a lot. We shouldn't do that much, but we probably should have a parameter that determines how many games are played against the static opponent. Currently, only one game is played ... the parameter can be used to play multiple games and average the win/lose/draw fitness (or whatever score is being tracked)

**Comment by DarwinJohnson** [comment]
Created the Static Opponent Trials Parameter called boardGameStaticOpponentRuns. The agents will face the Static Opponent a number of times equal to this Parameter, and the Scores from the runs will be averaged. This Parameter is defaulted to 1, so no previous Batch Files will be affected. Ran an Othello Batch File to see if this Score was being tracked correctly, and it appears to be working.

**Comment by schrum2** [comment]
One more small request before closing this:
Make the StaticOpponentFitness return a score that is the percentage of wins (using the new fitness from #445 ) instead of the WinLoseDraw average.

**Comment by DarwinJohnson** [comment]
Now the Static Opponent Fitness track the Win Percentage instead of the Simple Win-Lose-Draw Fitness.
