### ISSUE TITLE
Track win percent other score

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#445]
Although the win (1)/lose (-2)/draw (0) fitness is useful as a fitness function, when it comes to reporting results for a human to interpret, it would be better to simply know the win percentage. This can be encoded by a fitness that assigns 1 for winning and 0 for lose and draw. When averaged, the result can be interpreted as a win percentage.

Create such a "fitness" and have it always be present as an "other" score (not actually used as fitness, but tracked in the output).

**Comment by DarwinJohnson** [comment]
Created the Win Percentage Fitness Function and added it as an Other Score to all Board Game Tasks. Ran an Othello Batch File to see if it functioned properly, and tracking of this Fitness appears to be working. All Board Game Batch Files should now track the Win Percentage of evolved Generations.
