### ISSUE TITLE
Comment edu.utexas.cs.nn.tasks.gridTorus 

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#47]
comment edu.utexas.cs.nn.tasks.gridTorus because of the generalization of it in order to support multiple (specified in command line parameters) preys and predators, as well as the addition of the ability to evolve either preys or predators (also specified in command line parameters)

**Comment by schrum2** [comment]
When doing this, be sure that all method comments have information about each @param individually, even if it is tedious to write. No shortcuts.

**Comment by Rollinsa** [comment]
Extensively commented edu.utexas.cs.nn.tasks.gridTorus after it was generalized/redone to support multiple possible preys and an evolving set of predators with static preys in addition to the previous ability to have an evolving set of prey with static predators
