### ISSUE TITLE
Pred/Prey have option of sensing teammates

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#49]
Add a boolean parameter that turns on/off the availability of sensors corresponding to agents on the same team in the pred/prey torus domain. In other words, predators should have the option of sensing other predators the same way they sense prey and vice-versa.

**Comment by Rollinsa** [comment]
Allowed for the ability (can be turned on or off by command line parameter) for the predators and for the prey to sense their teammates. This works and helps both types of agents to evolve much more efficiently, and I have committed this to github and I am now planning on making the code more elegant and adding some comments.

**Comment by Rollinsa** [comment]
Completed cleaning up this code so that some confusing for loops were replaced with arraycopy and instead of repetitive and confusing code I implemented utility getter methods that find the offsets to the sensed predators or preys which I call instead.
