### ISSUE TITLE
Unit Testing for TWEANNCrossover

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#5]
In the package edu.utexas.cs.nn.evolution.crossover.network is a class called TWEANNCrossover.

This class has a main method at the bottom that performs some simple tests to assure that the code works. This informal tests need to be turned into proper JUnit tests. Tests beyond those in the main method may also need to be added.

Once all tests in the main method are replaced with proper JUnit tests, the code in the main method should be removed to keep things tidy.

While working on the TWEANNCrossover class, comments should also be added everywhere that they are missing.

**Comment by leg2015** [comment]
Commented TWEANN crossover class and added JUnit test class for TWEANN crossover
