### ISSUE TITLE
Complete TetrisAfterStateAgent

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#52]
This agent plays Tetris using the after state evaluator. It generates after states from the current state, and then picks the action leading to the desired state.

**Comment by Serenamidori** [comment]
The code is "finished" but not tested, and we'll test it Monday.

**Comment by schrum2** [comment]
The RLGlueTask is currently hard-coded to instantiate an RLGlueAgent. You need to allow the user to specify the RLGlue agent class as a command line parameter in order to make your tetris afterstate agent accessible.

Note that Alex is currently working on a similar issue regarding how to instantiate a class from a command line parameter.

**Comment by schrum2** [comment]
Your agent will need to override the outputLabels() method from the RLGlueAgent.
Just one output, which is the utility of the resulting afterstate.

**Comment by Serenamidori** [comment]
Are these still issues we need to address?

**Comment by Serenamidori** [comment]
Agent files is completed, and while the entire project still needs work, I'll close this issue for now unless something else regarding the Agent specifically comes up
