### ISSUE TITLE
Be able to use TetrisAfterStateAgent

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#53]
By default, RL Glue always uses the RLGlueAgent. You'll need to make a class type command line parameter that lets you specify the type of RLGlue agent to use, so that you can use this tetris-based agent instead. I believe the RLGlueTask is the place where the agent will be initialized.

**Comment by Serenamidori** [comment]
This is TODO #1 for Monday 5/16/2016

**Comment by Serenamidori** [comment]
You helped me create a parameter for the RLGlueAgent to allow a specified agent to be used, correct? If that's not the case, I won't close the issue.

**Comment by Serenamidori** [comment]
Double checked parameters, and yes we have added the class type command line parameter, so closing this issue now.
