### ISSUE TITLE
Make Unit Tests for various Pred/Prey domain methods

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#54]
You need to make JUnit tests that use the initializeParameters method of the Parameters class to artificially input a set of parameters. Then, check that your methods behave properly. For example, make sure the sensor and output labels are correct for predators evolving, prey evolving, various numbers of each, being able to sense teammates, and having the option of doing nothing as an action.

**Comment by Rollinsa** [comment]
Made JUnit tests for TorusAgent, TorusPredPreyGame, PreyRawalRajagopalanMiikkulainenObjective, and TorusPredatorsByProximitySensorBlock

**Comment by Rollinsa** [comment]
Made a JUnit test case for the PredatorMinimizeDistanceFromPreyObjective

**Comment by schrum2** [comment]
Make sure that all input blocks only ever return values in the range [0,1]. Use both unit tests and asserts to verify this.

**Comment by Rollinsa** [comment]
Do a JUnit test for the GroupPredPreyTask to test that none of its values (sensorLabels, outputLabels, numberPop, Objectives, etc) are null and that they are the correct size

**Comment by Rollinsa** [comment]
Worked a lot more on the TorusPredPreyTask Test

**Comment by Rollinsa** [comment]
Finished the TorusPredPreyTask JUnit Test
