### ISSUE TITLE
Add Half Linear Piecewise function

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#57]
Add a half-linear piecewise function to ActivationFunctions. It just prevents values above 1 and less than 0.

Note that introducing this also involves adding a unique id at the top of the file and a parameter for allowing the function in CPPNs (ask Gabby).

Additionally, this function can be used to prevent range errors when creating colors in the ImageMatchTask, since values outside the range [0,1] are not allowed.

**Comment by leg2015** [comment]
Added the half linear piecewise activation function to all necessary places in the code
