### ISSUE TITLE
Add a sawtooth activation function

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#58]
See this link for inspiration:
https://en.wikipedia.org/wiki/Sawtooth_wave

The function should be added to ActivationFunctions, and made accessible to CPPNs

**Comment by leg2015** [comment]
Added a sawtooth activation function to all necessary areas in the code

**Comment by schrum2** [comment]
You may not have actually synced these and other changes

On May 16, 2016, at 4:03 PM, leg2015 notifications@github.com wrote:

Closed #58.

**Comment by schrum2** [comment]
Nevermind ... they appear as part of Gabby's merge

On Mon, May 16, 2016 at 8:14 PM, Jacob Schrum schrum2@southwestern.edu
wrote:

> You may not have actually synced these and other changes
> 
> On May 16, 2016, at 4:03 PM, leg2015 notifications@github.com wrote:
> 
> Closed #58 https://github.com/schrum2/MM-NEATv2/issues/58.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/schrum2/MM-NEATv2/issues/58#event-662172715

## 

Jacob Schrum, Ph.D.
Assistant Professor of Computer Science
Department of Mathematics and Computer Science
Southwestern University
1001 E. University Ave.
Georgetown, TX 78626

Office: Mood-Bridwell Hall 141
Mail: SU Box 7341
Off-Campus Phone: (512) 863-1712
On-Campus Extension: x1712
E-mail: schrum2@southwestern.edu
WWW: http://southwestern.edu/~schrum2
