### ISSUE TITLE
Center coordinate frame in image match task

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#59]
CPPN results may be better if the origin of the coordinate plane is in the center of the image instead of the upper left of the image. This requires every coordinate to be translated back and forth between being used in different ways.

By the way, it might be a good idea to do some informal testing of CPPNs with a main method in the ImageMatchTask. Specifically, extract the code for drawing a CPPN image into its own method (it would take a TWEANNGenotype as input, draw the image on a new DrawingPanel, then wait for a key press to finish). Then, in the main method you can manually construct a CPPN with certain activation functions and hidden nodes (or just do lots of random mutations) and see what kind of images you get.

**Comment by schrum2** [comment]
I remembered something else important about CPPNs that I think is important to drawing good images: Not only should the coordinate frame be centered on the middle of the image, but you should also scale the x/y coordinate inputs to be in the range -1 to 1. So, a pixel in the upper left of the image would cause x,y inputs of (-1,1), and a point somewhere in the lower right would have a coordinate like (0.5, -0.5). If the coordinate values aren't scaled down, then they will always be too high, which will saturate most of the activation functions.

**Comment by leg2015** [comment]
Added a main method to test CPPN image functionalities and with some scaling and tweaking from RGB to HSB and adding a bias and distance input, got CPPN to create some cool images finally. Also centered frame of image to be in the center, not upper left-hand corner. Also a few activation functions were removed because they pass out-of-bounds values. Also added a nifty save command so pictures and networks can be saved as .bmp's for later use in presentations and such

**Comment by schrum2** [comment]
If you are interested, you could try creating a system something like Picbreeder. This would be more interesting than the image match task because there is work showing that an objective-based approach to evolving specific images with CPPNs seldom works. The power of Picbreeder is that subjective preferences search the space of possibilities in an interesting way. If you are interested, turn this into an Issue.

As for applying this to a game, a lot more work is needed first. CPPNs are only part of HyperNEAT. There are already some issues in GitHub associated with the implementation of HyperNEAT, specifically the creation of substrates. You can claim these issues for yourself when you are ready to pursue them.

Incidentally, Tetris needs some more work before HyperNEAT can be applied to it. A better place to start would be Alex's predator/prey domain. He is still working on this domain, but if we apply HyperNEAT here first then there is a much greater chance of success. Once we get it working there, then we can move on to Tetris and other domains.

I like the directions you are working in. Keep up the good work!

On May 16, 2016, at 3:35 PM, leg2015 notifications@github.com wrote:

Added a main method to test CPPN image functionalities and with some scaling and tweaking from RGB to HSB and adding a bias and distance input, got CPPN to create some cool images finally. Also centered frame of image to be in the center, not upper left-hand corner. Also a few activation functions were removed because they pass out-of-bounds values. Also added a nifty save command so pictures and networks can be saved as .bmp's for later use in presentations and such
