### ISSUE TITLE
Unit testing for TWEANNGenotype

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#6]
TWEANNGenotype in package edu.utexas.cs.nn.evolution.genotypes contains a main method with some informal tests. As many of these informal tests as possible need to be transformed into proper JUnit tests. In fact, the main method currently has exceptions when run, so these problems need to be diagnosed first.

**Comment by leg2015** [comment]
Added unit test for TWEANN genotype and commented/cleaned up TWEANNGenotype class
