### ISSUE TITLE
JUnit tests for classes in package edu.utexas.cs.nn.evolution.mutation.tweann

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#61]
All of the different mutation operators need JUnit tests. Some already have them, and some have informal tests. However, they all need formal tests.

**Comment by schrum2** [comment]
I feel like you've already done a lot of these tests, so I figured I'd assign this to you. Complete any remaining tests, and then close this issue. Note that even the ones that do not yet have informal tests need some kind of JUnit tests.

**Comment by leg2015** [comment]
After today, feel not all these classes need tests, but TWEANNGenotype definitely needs some more

**Comment by schrum2** [comment]
See my comment in https://github.com/schrum2/MM-NEATv2/commit/4c9ef6e5fe5c9efb401489eaf881b66de1aa6a73

**Comment by schrum2** [comment]
I'm sharing this with Gabby. Each of you can work together to fill out needed tests.

**Comment by leg2015** [comment]
Still need tests for polynomial weight mutation, redirect link mutation, and MMR

**Comment by schrum2** [comment]
Skip polynomial weight mutation, but complete the rest

**Comment by leg2015** [comment]
All that's left then is redirect and MMR

**Comment by leg2015** [comment]
worked on MMR test. Throws an annoying out of bounds error however that needs to be looked at

**Comment by leg2015** [comment]
Also added test for redirect link. Part of it doesn't pass however so it needs to be revisited at some point.

**Comment by leg2015** [comment]
Got all dem tests done!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
