### ISSUE TITLE
JUnit tests for BertsekasTsitsiklisTetrisExtractor

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#63]
Unit test this feature extractor by artificially constructing Tetris states and manually calculating what the features should be. Include tests for at least five distinct Tetris states with varying numbers of pre-filled blocks. However, make sure all of your Tetris states are valid states, meaning that they contain complete lines that need to be eliminated and scored.

Also try to clean up comments in this class. In particular, never leave any @param or @return tag blank, and make sure each method has a comment. Also try to remove compiler warnings, or suppress them if warranted.

**Comment by Serenamidori** [comment]
I've created 2 tests for the outputs from the BertsekasTsitsiklisTetrisExtractor, and both passed. Now I'm on issue #74 to make sure these outputs can be scaled.
