### ISSUE TITLE
JUnit testing for static agent controllers in Pred/Prey

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#64]
Create JUnit tests for all static predator and prey agents. Artificially fill a grid world with agents of each type and manually calculate the move that each agent should make according to its code. Then make sure that it actually chooses that move. Create at least 5 tests for each static agent.

**Comment by Rollinsa** [comment]
Made JUnit test for the PreyFleeClosestPredatorController

**Comment by Rollinsa** [comment]
Made a JUnit test for the AggressivePredatorController

**Comment by Rollinsa** [comment]
Tested the two used static controllers. Others unused
