### ISSUE TITLE
Comment and refactor code in Pred/Prey for fixing TWEANN log problems (track modeUsage)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#68]
Comment the code I hastily wrote to fix the modeUsage bug you were having. Refactor the code as well to reduce repetition and make it better however you can.

**Comment by Rollinsa** [comment]
Commented and cleaned up the code that was added in TorusPredPreyTask to fix the modeUsage bug. Made the code more compact with less repetition and explained why some of it was there (to make the agent an organism for the fitness function, and to save the modeUsage for when it is lost).
