### ISSUE TITLE
Add activation functions to ActivationFunctions

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#7]
In package edu.utexas.cs.nn.networks, add several functions to ActivationFunctions. These will mostly be wrappers for calls to Math class functions. The needed activation functions are Gaussian, sine, absolute value, and perhaps others, like the saw tooth function. These are functions generally associated with HyperNEAT CPPNs.

While adding these functions, comment all other code in the class.

**Comment by schrum2** [comment]
Additionally, any functions added here should be made accessible to Node class within the TWEANN class of edu.utexas.cs.nn.networks

**Comment by Serenamidori** [comment]
I added and commented the functions, but left out saw tooth per your request.
