### ISSUE TITLE
Pred/prey: monitor all agent network inputs

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#70]
When monitorInputs:true is set, a panel is displayed showing the sensor values of the neural network in use. However, in the pred/prey task there is one network available per evolved agent. There should be one panel per agent as well, so the sensors of all agents can be tracked.

**Comment by schrum2** [comment]
This seems to be a duplicate of #75. I guess I created this issue but forgot to assign it. Be sure to close it when you close the other.

**Comment by Rollinsa** [comment]
Finished up with monitorInputs so that a panel is displayed for every evolved agent
