### ISSUE TITLE
Finish creating monitorInput visuals for the Torus PredPrey world

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#75]
include a visual for each monitor input showing the inputs (offsets between this agent and the others), outputs (possible moves), and game time, which is all determined by parameters and all change throughout the game. The number of monitor input visuals is determined by the number of evolved agents

**Comment by Rollinsa** [comment]
completed this for the predators so that each predator has a visual with monitor inputs, but I have not implemented it for the prey yet and need to do that still

**Comment by Rollinsa** [comment]
Finished up with monitorInputs so that a panel is displayed for every evolved agent

**Comment by schrum2** [comment]
There is a small bug with this. An extra window is displayed with the title "Individual Info". Prevent this from showing up.

**Comment by Rollinsa** [comment]
Stopped "Individual Info" Panel from showing up with monitorInputs for predPrey
