### ISSUE TITLE
Clean up magic numbers in Tetris code

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#76]
The magic numbers in the tetris code are really starting to get confusing, but I have a way to fix it. Make some public static final int values in the TetrisState class with names like TETRIS_STATE_INDEX_FALLING_PIECE_X and TETRIS_STATE_INDEX_CURRENT_ROTATION. You'll need to figure out what the exact value of things like o.intArray.length - 5 and o.intArray.length - 3 are so you can set these values. These constants can replace some confusing code in TetrisState, and in your after state classes.

**Comment by Serenamidori** [comment]
Not going to close yet, but thanks to you I'm going through and replacing magic indices for some files. We've made some public ints to help us call certain numbers(features, height, width, etc.) I'll close when I check them all.

**Comment by Serenamidori** [comment]
Looked through all the files I've been working in a replaced all magic numbers, save for one that I'll need to do more testing to figure out what it should be (a comment was left in TetrisAfterStateGenerator explaining why)
