### ISSUE TITLE
Different sensor configurations for predator/prey

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#79]
Another change to the predator prey domain that might help is to allow for different sensor configurations. Currently, agents have (x,y) coordinate inputs for each other agent, but the order of these inputs is not very helpful to the agent. For example, if the network associates some kind of behavior with inputs 1 and 2, then it might be ignoring other inputs, even if they are associated with an agent that is closer.

So, instead of just ordering the sensors by the coincidental order of agents in the array, try ordering them in terms of proximity. In other words, for a predator, the first two sensors should correspond to the closest prey agent, which ever one it is. The next two sensors should correspond to the next closest agent and so on.

The option to use these sensors should come from the command line. Agents should still be able to use the previous types of sensors though ... this will allow us to compare them.

You might also want to allow a smaller set of sensors that only senses information about the closest agent, and ignores information about the rest. This is a special case of the other sensor configuration. Basically, having fewer sensors can sometimes be easier to learn with because there are fewer parameters to configure (though overall better behavior is theoretically better with more information.)

**Comment by Rollinsa** [comment]
By setting fs to false, the network is required to not ignore any input(s). This can also be turned back to true if we want to compare them. Still, if you want me to and you think it would be beneficial, I could try to implement the smaller set of sensors that only senses information about the closest agents. I could also try to implement a version where the agents in the array of sensors are ordered in terms of their proximity to one another

**Comment by Rollinsa** [comment]
Generalized the sensors for the predPrey agents and made the code a lot more compact and elegant (and commented it). Added a new sensor package so that all future sensor blocks can be added in much more simply, so sensors by proximity can be added next.

**Comment by Rollinsa** [comment]
Added sensor options so that the predators and the prey can sense by proximity (including sensing just enemies or also teammates). Also fixed a bug causing a null pointer exception with the sensor inputs before being instantiated by finding the number of inputs in the main method using the class option command line parameter (indicating type of agent being evolved, which speaks to how many number of inputs there will be).
