### ISSUE TITLE
Create CPPN

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#8]
There needs to be a way to evolve Compositional Pattern Producing Networks, which are used by HyperNEAT. CPPNs are essentially TWEANNs. I'm not sure whether the TWEANN class should be modified so that it can also support the additional activation functions that TWEANNs have, or if an actual separate CPPN class should be made that extends the TWEANN class (though this option seems more sensible).

Once the CPPN is made, a CPPNGenotype will also need to be made.

**Comment by Serenamidori** [comment]
We avoided the issue of creating a new CPPN class or extending TWEANN by simply adding a parameter of allowing a choice of multiple functions. This way, TWEANN becomes CPPN much easier, and it can all be done in the command line.
