### ISSUE TITLE
JUnit tests for CartesianGeometricUtilities

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#80]
Comment CartesianGeometricUtilities and provide unit tests for all methods. Note that I moved some methods here from the ImageMatchTask, so you can actually start this process by moving certain tests from ImageMatchTaskTest to the new testing class.

**Comment by leg2015** [comment]
Added a junit test for the method used by hyperNEAT. Will come back and add other tests later

**Comment by leg2015** [comment]
got a little farther on junit tests for this class

**Comment by leg2015** [comment]
Finished junit tests for this class
