### ISSUE TITLE
HyperNEAT: links are not always created

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#82]
The current first shot at HyperNEAT uses the CPPN outputs to define link weights. However, there is an extra complication that is required to get the full range of flexibility provided in the standard HyperNEAT (and there are also alternative approaches which I will mention in another issue).

The substrates are only meant to define every **potential** link in the controller network. Some of these links don't actually get created. The way to determine whether or not the link is created is based on the CPPN output. Specifically, there needs to be some threshold value (define this as a double Parameter with a default value of 0.2) that I'll call T. Let's call the output of the CPPN for a given link O. If the absolute value |O| < T then we do not create a link between the specified neurons. In other words, we do not create the link if -T < O < T.

However, we still want small weight values in the range -T to T to be possible, so we slide values outside this range. In other words, if O = 0.5 and T = 0.2, then the actual link weight will be O - T = 0.5 - 0.2 = 0.3. For negative values, we slide up, so that O = -0.7 results in a weight of O + T = -0.5.

In general O maps to the actual weight W like this:
                                                 -T      0     T
O  ------------------------------------+---- +----+------------------------------------------
                                                   \            /
                                                    \          /
                                                      \       /
                                                       \     /
                                                        \   /
                                                         \ /
W -------------------------------------------+-------------------------------------------------------

**Comment by schrum2** [comment]
My attempt at drawing a figure failed. Simply ask if confused.

**Comment by leg2015** [comment]
Added link expression to command line parameters and to the hyperneatCPPN class and junit test case.
