### ISSUE TITLE
Track all champions

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#86]
The code currently outputs the best individual (champion) in each objective in a special directory. The postBestObjectiveWatch batch file takes advantage of this and loads that neural network to evaluate it. However, in order to make it easy for this approach to find the champion, and in order to save disk space (not necessary in most cases) the program keeps writing the new champions from each generation over the old champions (it may explicitly delete the old ones first ... I'm not sure). However, I think we need a way to save all of the champions ... one from each generation. For example, it would be especially cool in the image task to watch a sequence of images going from the first champion to the last and see how it changes and hopefully improves over generations.

Please implement this feature. I think the best approach is to keep saving the best networks in the same directory, but to change the file names to include "genX" where X is the current generation so that all files will be distinguished. However, saving all of these files should be a command line option, not a requirement. Either way, make sure that postBestObjectiveWatch is able to look at the best network from the most recent generation (don't break what already works).

You will also need to add a way to go through the sequence of champions one by one ... we can talk about ideas of how to do this.

**Comment by leg2015** [comment]
Added code and a command line parameter to support saving either the best champion overall or the best champion from the each generation. Also added another batch objective eval that evaluates all champions from each generation, not just the best champion
