### ISSUE TITLE
Unit tests for NSGA2

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#9]
The NSGA2 class in package edu.utexas.cs.nn.evolution.nsga2 has main method with some informal testing. These need to be turned into proper unit tests using JUnit. In addition, the code in NSGA2 needs commenting

**Comment by schrum2** [comment]
Reassigning this.

**Comment by leg2015** [comment]
Finished commenting and adding JUnit class. Only tested the methods tested in main method because it looked like it checked all the core methods of the class
