### ISSUE TITLE
New Tetris Objective/Fitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#90]
When multiobjective Tetris is set (moTetris) the two objectives are the number of lines cleared and the duration of the game. Number of lines cleared is worthless unless the agent gets lucky. Increasing the duration of the game can help since you will live longer if you clear some lines, or at least spread the blocks out a bit. However, a third fitness would also be helpful:

Count the number of blocks that are filled in the world state when the game ends. If the number of blocks is higher, then it means the agent might have been close to actually clearing a row, so rewarding this outcome can help an agent that clears no rows begin to clear a few rows.

**Comment by Serenamidori** [comment]
Added the new fitness function, not sure if it's totally implemented or if it works well, testing now.

**Comment by Serenamidori** [comment]
It works! closing this for now
