### ISSUE TITLE
JUnit Test for Action Sequence

### ISSUE THREAD

**Issue by Serenamidori** [schrum2/MM-NEATv2#92]
May not be necessary, but I should write a test to make sure the action sequence that the agent chooses is the one that's being followed.

**Comment by schrum2** [comment]
Even though things seem to work, making some tests is a great idea. We want to make sure that if we change something in the future, we don't break anything.

**Comment by Serenamidori** [comment]
We did an informal debugging test in TetrisAfterStateAgent as a result of #102 and we may not need this JUnit Test.

**Comment by schrum2** [comment]
If we can figure out a way to write a JUnit test for this, we should. Go ahead and leave the issue open for now.

**Comment by Serenamidori** [comment]
Alright, I'll add this to my TODO list for Tuesday, unless something else comes up.

**Comment by Serenamidori** [comment]
Update: I've started an action sequence test, but had trouble starting. I was trying to test the getAction method directly, but this isn't possible unless that method is static and I didn't want to mess with that for a test.

Additionally, I couldn't get it to work in the test when using TetrisAfterStateAgent afterStateAgent = new TetrisAfterStateAgent(), because calling getAction gives a NullPointerException. I'll talk to you Monday about what to do.

**Comment by schrum2** [comment]
When doing unit tests for non-static methods, the general procedure is to create an instance of the class that needs to be tested in a setup method, and then test its methods in individual tests.

On June 10, 2016, at 4:39 PM, Gab notifications@github.com wrote:

Update: I've started an action sequence test, but had trouble starting. I was trying to test the getAction method directly, but this isn't possible unless that method is static and I didn't want to mess with that for a test.

**Comment by Serenamidori** [comment]
Currently the testing for the numbers in the actionList is working, but I'm having trouble starting the tests for the state changes themselves, as the state I set up never changes. I'm trying to find a way to allow the AfterStateAgent to use this state specifically, or at the very least find a way to check for changes in the piece's position

**Comment by Serenamidori** [comment]
(I had a problem with syncing earlier, so the github syncs are a mess I'M SORRY)
Synced the finished tests (a22e1f6fe6e98557d18f5145a15d6734ca0261c1) so it tests that the correct list of actions is returned and that taking the actions actually affects the tetris state and reaches the chosen afterState
