### ISSUE TITLE
Move scaleInputs to feature extractor

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#93]
Upon code review, the scaleInputs method in the TetrisAfterStateAgent class should actually be in the BertsekasTsitsiklisTetrisExtractor class. In fact, the FeatureExtractor interface should simply have a scaleInputs method. This means that all FeatureExtractors need a scaleInputs method ... but you can simply leave this undefined for now. There should be an auto-complete option to fix the error of not implementing a required method that simply creates a method that throws an exception. This is ok, since we currently only need to scale inputs from the BertsekasTsitsiklisTetrisExtractor

**Comment by Serenamidori** [comment]
Method has been moved and tested (Testing was fixed/improved to match afterstates better).
I'll close this issue unless something else occurs, but all issues have been fixed.
