### ISSUE TITLE
Tetris objective score management

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#94]
Make each of the three Tetris objectives an "other" score in addition to an "objective" score. Then replace the moTetris parameter with individual parameters for turning on/off each of the available fitness functions. Alex has been doing something similar with his domain, so you can ask him for help.

**Comment by schrum2** [comment]
This seems particularly important since there is apparently a maximum time limit on evaluations of 10,000 time steps. However, this means that some Tetris players finish without losing, which means they may have a very low score for Blocks on Screen. This is bad, because it punishes good players with a bad score in that objective. We should do two things:

1) Have an option to not use that objective (this is the original task assigned above ... all objectives are optional). Now that our after state evaluator is working, we may not need it.
2) Make is so that if the player ends an evaluation with the maximum time limit (finishes without dying) it artificially gets the maximum score for the "Blocks on screen" objective. This way, avoiding death will lead to a good score in this objective.

Incidentally, I've been letting the Tetris player evolve all night and it is still going, but some players reach the maximum time limit of 10,000 time steps. The best "RL Return" I've seen is slightly above 300, which is good, but I think we can do better.

**Comment by Serenamidori** [comment]
I've worked on part 2, and around line 182 in RLGlueTask I've added a check to find if we've hit the max number of steps, and then it sets numberOfBlocksInState to the max (height*width).
I still have question for part 1, so I'll wait to continue that until you're available next.

**Comment by Serenamidori** [comment]
Part 1 is finished now, two parameters created tetrisTimeSteps and tetrisBlocksOnScreen that we can set as true or false each batch file (edited now) and it replaces moTetris.
Part 2 will be confirmed when this exported version is tested tonight.

**Comment by Serenamidori** [comment]
Current objectives work on the Tetris agent tested last night!
