### ISSUE TITLE
Implement Picbreeder

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#95]
Take the code in the ImageMatch task and adapt it to create a system like Picbreeder that uses a human's subjective fitness preferences to evolve CPPNs that draw cool images. This would involve moving shared code from ImageMatch into a utility class used by both ImageMatch and the new Picbreeder task. This task would only be appropriate for small populations, and you would need to provide an interface that allows users to specify which genotypes to keep and which ones to toss from each generation. It might even necessitate making a new, but fairly simply, type of GA. For example, the human could select some agents to kill off in each population, and then select new individuals to either mutate or mate.

**Comment by schrum2** [comment]
I went ahead and assigned this to you. It's waiting if/when you want to do it. Note that to make a good user interface for this, you will probably need to do something more complex than use the existing DrawingPanels. Think back to the Calculator project from CS1: Try to create a window full of panels and buttons that the user can press to interact with the system. Refer to the original (http://picbreeder.org/) for inspiration ... you will probably need to use Firefox rather than Chrome in order to have Java access.

**Comment by leg2015** [comment]
Began to implement picBreeder task.

**Comment by schrum2** [comment]
I made some major changes you what you implemented so far. You can see the commit diff here:

Here is an explanation of the changes:
There shouldn't be a loadGenotypes method or a genotypes list. Genotypes should be passed into the task exclusively from elsewhere (the Evolutionary Algorithm is responsible for initializing the population and sending them to the task for evaluation). The private variable network is also not needed for similar reasons. The Picbreeder task also does not need to store an instance of itself.

I changed getImage to getImageButton, and changed it so that the image it generates is based on the genotype sent in rather than some other network. This required indicating in the class header that the type T extends Network.

I moved the image button code from the constructor into the evaluateAll method ... it doesn't work from there either, but conceptually, this is where it needs to go. Also, even though this task should probably only be used with small populations, try to write the code in a way that supports an arbitrary population size. Use loops to avoid repetition. I think the best way to do this is to set the width (number of pics per row) but allow the height to be flexible ... maybe we'll even figure out how to add a scroll bar, but don't worry about this for now.

Your major goal at this point is to make those image buttons actually show up on the panel. I ran the code several times, and one time some (but not all) buttons actually appeared! This makes me wonder is there is some find of refresh rate issue, or some other problem with listening/updating.

**Comment by schrum2** [comment]
Refer to commit 7d3c7784804460dede646548810632e10b0543a1

**Comment by leg2015** [comment]
Getting closer and closer to getting picbreeder implemented... Got all the buttons to (finally) show up and even got a cool evolve button set up. Also borders get highlighted when the button gets clicked and the correct score is saved. Need to get a new learning algorithm made and figure out how to replace the image on a button, but after that, it'll be close to being done!

**Comment by leg2015** [comment]
Got the replacing image problem solved and all the buttons lined up in order. Now I just need to tackle the EA task and make a batch file for testing purposes

**Comment by schrum2** [comment]
There are still some improvements to be made, but those are described in other issues. Once you have cleaned up un-needed testing code in the PicbreederTask, you can close this issue.

**Comment by schrum2** [comment]
I think this one is good to close. Still need to wrap up the other small issues though: #151 #160 #162 #163
