### ISSUE TITLE
Multiple RL Glue runs at once

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#96]
I think there is a way to have more than one RL Glue instance safely running on the same machine. The different components of the system communicate with each other via sockets/ports. Most of the RL Glue code is pre-compiled, so you can't look at it, but RL Glue classes like AgentLoader and EnvironmentLoader will at least let you know their method headers. I think the current problem is that RL Glue always uses the same port by default, so if you launch another instance you end up with a traffic jam. If we could just set each new run to use a different port, then they would get along.

**Comment by Serenamidori** [comment]
The file that uses "RL-Glue Java Experiment Codec" is NetGlue.Java that is in org.rlcommunity.rlglue.codec. It's not accesible to us, and I haven't been able to locate what file calls Netglue.Java. There is a public method "NetGlue(String host, int port)" that will set the Host and Port like with the Environment and Agent, but I'm not sure where this needs to be called. This is the one that still used the default "private int port = Network.kDefaultPort" so unless we have a way to change that Network.kDefaultPort, or at least a way to call NetGlue.Java from the task file, we may not have a way to have several instances of RLGlue running at once. I'll move onto another task for the time being.

**Comment by Serenamidori** [comment]
We changed the Runtime to a ProcessBuilder, and we also figured out how to change the Experiment Codec port number in NetGlue through the RLGlue.init(). There's now a parameter that we can use to change the port number of the current RLGlue instance, and the two post batch files we've been using to watch the games are set to different ports by default.
