### ISSUE TITLE
Comment and cleanup code in edu.utexas.cs.nn.tasks.mspacman.agentcontroller.pacman

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#97]
Time to learn a bit about Ms. Pac-Man. There are a lot of classes here, and not all of them are worth looking at. The ones to focus on are

NNMsPacMan
NNPacManController
NNDirectionalPacManController
NNCheckEachDirectionPacManController

More might be worth looking at later.

**Comment by Rollinsa** [comment]
Commented and looked at NNMsPacMan, NNPacManController, NNDirectionalPacManController, NNCheckEachDirectionPacManController
