### ISSUE TITLE
Comment/cleanup  edu.utexas.cs.nn.tasks.mspacman.sensors

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#98]
Specific files to focus on

MsPacManControllerInputOutputMediator
BlockLoadedInputOutputMediator
MultipleInputOutputMediator
UnionInputOutputMediator
VariableDirectionBlockLoadedInputOutputMediator

**Comment by Rollinsa** [comment]
Commented (and attempted to explain) MsPacManControllerInputOutputMediator, BlockLoadedInputOutputMediator, MultipleInputOutputMediator, UnionInputOutputMediator, and VariableDirectionBlockLoadedInputOutputMediator from the mspacman.sensors package
