### ISSUE TITLE
Make TorusPredPreyTask implement the HyperNEATTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#99]
Try to get the torus pred/prey grid world to work as a HyperNEAT domain. There are probably many issues we haven't considered you (create them as you discover them), but the basic starting point is to make TorusPredPreyTask  implement HyperNEATTask. An important thing to keep in mind is that we want to make applying HyperNEAT possible, while still allowing all of the regular NEAT evolution options that Alex is already using. We are adding, not replacing features. Many new command line parameters will likely also be needed to support selecting these options.

**Comment by leg2015** [comment]
Implemented hyperNEAT to torus pred/prey task (more or less)

**Comment by schrum2** [comment]
The code looks pretty good, though I did clean it up a bit. However, despite that, there still seems to be an error when I launch it using my newly added batch file: PredPreyTorus-CatchCloseQuickPredVsStaticPreyTeam-HyperNEAT.bat

Try to troubleshoot this error (and others that emerge). Start by running the batch file and go from there.

**Comment by schrum2** [comment]
I fixed a null pointer exception (eaten prey become null) and everything seems to work. However, it is extremely slow. This isn't too surprising, but I'm looking in to ways to speed things up. For example, this commit, https://github.com/schrum2/MM-NEATv2/commit/972d40b7238bcf6806a15d8e6b46fb300654517c, caches some of the relevant HyperNEAT information instead of re-calculating it every time.

Other steps are probably possible with HyperNEAT in general, so I'm going to close this issue and make a new one.
